bare-metal/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
Fix modules now that bootkube-terraform has migrated to purenetes org.
=> *: dghubble->purenetes

README.md, google-cloud/container-linux/controllers/controllers.tf, google-cloud/container-linux/workers/workers.tf
* In terraform-provider-google v0.1.3, it is no longer necessary to supply a (duplicated) value for the instance_template field automatic_restart
* Previously this field was set to match the scheduling automatic_restart since the field defaulted to true and would cause plan to always show changes were needed
Now that the field is removed in terraform-provider-google v0.1.3, users will see the following error:
```
* module.mycluster.module.controllers.google_compute_instance_template.controller: "automatic_restart": [REMOVED] Use 'scheduling.automatic_restart' instead.
* module.mycluster.module.workers.google_compute_instance_template.worker: "automatic_restart": [REMOVED] Use 'scheduling.automatic_restart' instead.
```
This PR removes Typhoon's use of the field to correspond.
Typhoon no …
=> google-cloud: Remove deprecated automatic_restart field

README.md
Fix the addons link, which is going to an old markdown doc. Point to the actual website, since this is what the other docs links do.
=> README.md: fix addons link

bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/variables.tf
* Add `networking` variable for bare-metal that allows "flannel" or "calico"
This is running in several bare-metal environments. Peering with routing hardware works as well. Still gaining confidence in it. Need separate experimentation on cloud providers (with separate MTU).
rel: https://github.com/poseidon/bootkube-terraform/pull/10
=> bare-metal: Add support for Calico networking

bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/variables.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/variables.tf, docs/bare-metal.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, google-cloud/container-linux/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/controllers/variables.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/cluster.tf, google-cloud/container-linux/kubernetes/network.tf, google-cloud/container-linux/kubernetes/variables.tf
* Add `networking` variable ("flannel" or "calico") for Google Cloud and Digital Ocean.
rel: Calico added as a networking option on bare-metal in #9.
* Runs production workloads on GCE.
* Digital Ocean firewalls don't yet support the IP tunneling protocol. You can run Calico if the cloud firewall is removed, but this isn't safe. This should be considered a partial implementation pending Digital Ocean improvements.
=> Add support for Calico networking on cloud platforms

README.md, aws/container-linux/kubernetes/ami.tf, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/cl/worker.yaml.tmpl, aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/elb.tf, aws/container-linux/kubernetes/ingress.tf, aws/container-linux/kubernetes/network.tf, aws/container-linux/kubernetes/ssh.tf, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers.tf, bare-metal/container-linux/kubernetes/ssh.tf, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/container-linux/kubernetes/ssh.tf, digital-ocean/container-linux/kubernetes/workers.tf, docs/aws.md, docs/bare-metal.md, docs/concepts.md, docs/google-cloud.md, docs/index.md, mkdocs.yml
Add AWS module as "alpha". Its not mature like the others (which I've used for years), but the basics are there:
* AWS networking in rather subpar compared with Google Cloud. Lower peak bandwidth and varies wildly.
* AWS provisioning is much slower because of the DNS -> ELB -> ASG setup (i.e. 10-20 min). As part of deprecating self-hosted etcd, controllers will be statically provisioned and this will be sped up greatly.
* Cluster deletion is also much slower than other platforms (i.e. 8 min). Feels sluggish.
* Kubernetes AWS integrations aren't enabled. I'll get to them, just not a major priority since my workloads are agnostic.
rel #6
=> Add AWS module and docs

bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/groups.tf, bare-metal/container-linux/kubernetes/profiles.tf
* Template bare-metal Container Linux configs with Terraform's (limited) template_file module. This allows rendering problems to be identified during `terraform plan` and is favored over using the Matchbox templating feature when the configs are served to PXE booting nodes.
* Writes a Matchbox profile for each machine, which will be served as-is. The effect is the same, each node gets provisioned with its own Container Linux config.
Provisions just as before.
=> bare-metal: Ues Terraform templating for Container Linux configs

aws/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
* On bare-metal, the bootkube-terraform module wasn't bumped to the v0.6.2 release SHA hash (like cloud platforms were). It was one commit behind. (fix)
* Switch all bootkube-terraform references to use the named tag for consistency and clarity
=> bare-metal: Update to using Kubernetes v1.7.5 assets

CHANGES.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/groups.tf, bare-metal/container-linux/kubernetes/variables.tf, docs/bare-metal.md
* Transition from discouraging self-hosted etcd for bare-metal, to removing it as an option
* See #13 and FAQ for self-hosted etcd discussion
=> bare-metal: Remove support for experimental_self_hosted_etcd

aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, google-cloud/container-linux/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/workers/cl/worker.yaml.tmpl
* Mounting NFS exports as volumes from some NFS servers fails because the kubelet isn't starting rpc-statd as expected. Describing pods that are stuck creating shows rpc.statd is required for remote locking
* Starting rpc-statd.service resolves the issue and all NFS mounts seem to be working.
* Recommended approach https://github.com/coreos/bugs/issues/2074
```
Mounting command: mount   
Mounting arguments: 10.3.0.14:/exports/example /var/lib/kubelet/pods/6a8f4a2e-a186-11e7-9952-6cae8b5b4268/volumes/kubernetes.io~nfs/data-volume nfs []
Output: mount.nfs: rpc.statd is not running but is required for remote locking.                          
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.                                   
mount.nfs: an incorrect mount option was …
```
=> Add Wants=rpc-statd.service to Kubelet

CHANGES.md, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/container-linux/kubernetes/ssh.tf, docs/topics/performance.md
* Run etcd peers with TLS across controller nodes
* Deprecate self-hosted-etcd on the Digital Ocean platform
* Distribute etcd TLS certificates as part of initial provisioning
* Check the status of etcd by running `systemctl status etcd-member`
* Side effect: Cuts down provisioning time from 5:05 to 3:30.
rel: #13
=> digital-ocean: Run etcd cluster on-host, across controllers

bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/variables.tf, bare-metal/container-linux/pxe-worker/variables.tf, docs/topics/performance.md
Completed tests on the bonded NIC test cluster show flannel hits the the same pod-to-pod bandwidth limit that Calico does. This strongly suggests the bottleneck lies below flannel/Calico so no need to pester Calico about it (docker limit? host misconfiguration? if we team do we get the same limit?)
For now, let's post the results and commit these temporary variables.
=> Add temporary variables for multi-nic testing

CHANGES.md, README.md, aws/container-linux/kubernetes/README.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/README.md, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, docs/aws.md, docs/bare-metal.md, docs/concepts.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md
* Update AWS, DigitalOcean, and bare-metal to Kubernetes v1.8.1
* Update from bootkube v0.7.0 to v0.8.0
* Leave Google Cloud update to a followup commit
Bootstraps clusters on all platforms. Usual functionality. Tested with workloads. Some issues found on Google Cloud are being investigated so Google Cloud is held back.
=> Update Kubernetes from v1.7.7 to v1.8.1

CHANGES.md, README.md, aws/container-linux/kubernetes/README.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/README.md, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, docs/aws.md, docs/bare-metal.md, docs/concepts.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
* Kubernetes v1.8.2 fixes a memory leak in the v1.8.1 apiserver
* Switch to using the `gcr.io/google_containers/hyperkube` for the
on-host kubelet and shutdown drains
* Update terraform-render-bootkube manifests generation
* Update flannel from v0.8.0 to v0.9.0
* Add `hairpinMode` to flannel CNI config
* Add `--no-negcache` to kube-dns dnsmasq
Tested on all platforms. Replaced v1.8.1 clusters with this.
Rel: https://github.com/poseidon/terraform-render-bootkube/pull/27
Closes #41
The rkt flag `--insecure-options=image` isn't as scary as it sounds. rkt had different ideas about image security and originally required GPG signed ACIs. When pulling `docker://` images, those signatures aren't present which is why rkt calls them insecure. In a post-OCI world, it doesn't have so much weight.
=> Update Kubernetes from v1.8.1 to v1.8.2

aws/container-linux/kubernetes/require.tf, bare-metal/container-linux/kubernetes/require.tf, digital-ocean/container-linux/kubernetes/require.tf, docs/aws.md, docs/bare-metal.md, docs/digital-ocean.md, docs/google-cloud.md, google-cloud/container-linux/kubernetes/require.tf
Requiring minimum versions of provider plugins makes Terraform more consistent. You don't have to guess which version of Terraform or which version of the "google" or "aws" plugins we developed against. When a version requirement changes, we'll bump it and you'll be prompted to update.
* Bump minimum Terraform version to v0.10.4
* Allow minor version updates for 1.0+ plugins
* Fix versions for plugins which are pre-1.0
If you've been using old versions of provider plugins, you'll see an error after updating your source ref=hash to this commit or beyond.
```
$ terraform get --update
$ terraform plan
Plugin reinitialization required. Please run "terraform init". …
```
=> Require minimum Terraform and plugin versions

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, docs/aws.md, docs/bare-metal.md, docs/digital-ocean.md, docs/google-cloud.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl
* Use the v0.8.1 tagged terraform-render-bootkube module
* Use the v0.8.1 quay.io/coreos/bootkube image to bootstrap
=> Bump bootkube and terraform-render-bootkube to v0.8.1

CHANGES.md, README.md, docs/google-cloud.md, docs/index.md, google-cloud/container-linux/kubernetes/cluster.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/controllers/controllers.tf, google-cloud/container-linux/kubernetes/controllers/variables.tf, google-cloud/container-linux/kubernetes/require.tf, google-cloud/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/workers/variables.tf, google-cloud/container-linux/kubernetes/workers/workers.tf
* Change Google Cloud module to require the `region` variable (CHANGE)
* Worker managed instance group creates workers across zones in a region.
* Example: region: us-central1 means a worker may go in us-central1-c, us-central1-f, us-central1-a, etc.
* Tolerate Google Cloud zone failures or capacity problems
* Tradeoff: Changing user-data will no longer automatically roll workers. You can delete old instances and they'll be replaced by new instances. Worthwhile tradeoff since mutating user-data should only be needed in special cases. See https://github.com/terraform-providers/terraform-provider-google/pull/394
* Improvement/Note for Preemptible VMs:
* If worker preemption is enabled, replacement instances can now be drawn from any zone in the region, which should avoid scheduling issues …
=> Google Cloud regional workers and improvements

addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* Fix typo in kube-state-metrics strategy
* Omit static resource requests/limits from kube-state-metrics
* Allow the addon-resizer to dynamically set resource values
* kubernetes/kube-state-metrics#285
=> addons: Update kube-state-metrics deployment

CHANGES.md, README.md, digital-ocean/container-linux/kubernetes/controllers.tf, docs/aws.md, docs/bare-metal.md, docs/faq.md, docs/google-cloud.md, docs/index.md, docs/topics/performance.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/cluster.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/controllers/controllers.tf, google-cloud/container-linux/kubernetes/controllers/network.tf, google-cloud/container-linux/kubernetes/controllers/outputs.tf, google-cloud/container-linux/kubernetes/controllers/variables.tf, google-cloud/container-linux/kubernetes/outputs.tf, google-cloud/container-linux/kubernetes/ssh.tf, google-cloud/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/workers/network.tf, google-cloud/container-linux/kubernetes/workers/variables.tf
Run etcd on-host, across controllers (etcd-member.service)
* Change controllers from a managed group to individual instances
* Create discrete DNS records to each controller's private IP for etcd
* Reduce time to bootstrap a cluster
* Deprecate self-hosted-etcd on the Google Cloud platform
Create controller instances across zones in the region
* Change controller instances to automatically span zones in a region
* Remove the `zone` required variable
rel: #35 #13
=> google: etcd on-host, controllers span zones in the region

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/elb.tf, aws/container-linux/kubernetes/ssh.tf, digital-ocean/container-linux/kubernetes/controllers.tf, docs/aws.md, docs/topics/performance.md, google-cloud/container-linux/kubernetes/controllers/controllers.tf
* Change controllers ASG to heterogeneous EC2 instances
* Create DNS records for each controller's private IP for etcd
* Change etcd to run on-host, across controllers (etcd-member.service)
* Reduce time to bootstrap a cluster
* Deprecate self-hosted-etcd on the AWS platform
=> Run etcd cluster on-host, across controllers on AWS

CHANGES.md, aws/container-linux/kubernetes/controllers.tf, google-cloud/container-linux/kubernetes/controllers/controllers.tf, google-cloud/container-linux/kubernetes/network.tf, google-cloud/container-linux/kubernetes/outputs.tf, google-cloud/container-linux/kubernetes/workers/workers.tf
* Whitelist internal traffic between controllers and workers
* Switch to tag-based firewall policies rather than source IP
* Output the google network name and self_link to allow users to add firewall rules for unique cases
* Cleanup old firewall rule for bootstrap self-hosted etcd (AWS)
I've tested all the usual kubectl operations, prometheus targets, and my own rules/alerts. If I've missed any internal communications, drop a note or open an issue.
=> Improve internal firewall rules on Google cloud

CHANGES.md, README.md, aws/container-linux/kubernetes/README.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/README.md, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, docs/aws.md, docs/bare-metal.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
Running this on clusters today (all platforms) without issue. I'll leave them running for a bit before tagging the individual module repos as `v1.8.3` https://github.com/poseidon
rel: https://github.com/kubernetes-incubator/bootkube/pull/765
=> Update Kubernetes from v1.8.2 to v1.8.3

google-cloud/container-linux/kubernetes/controllers/network.tf, google-cloud/container-linux/kubernetes/require.tf
* With google provider 1.2, target pool instances can use self_link
and zone/name formats without causing a diff on each plan
* Original workaround: 77fc14db719
=> Update min Google plugin and remove target pool workaround

addons/grafana/deployment.yaml, addons/prometheus/rules.yaml, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/pxe-worker/profiles.tf
* Update Grafana from v4.6.1 to v4.6.2 (https://github.com/grafana/grafana/releases/tag/v4.6.2)
* Fix prometheus K8SApiServerLatency alert rule (https://github.com/coreos/prometheus-operator/issues/751)
* Add prometheus rules for DaemonSets (https://github.com/coreos/prometheus-operator/pull/755)
=> Sync upstream addon changes

CHANGES.md, README.md, aws/container-linux/kubernetes/README.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/README.md, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, docs/aws.md, docs/bare-metal.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
* Update Kubernetes from v1.8.3 to v1.8.4
* Update docs and CHANGELOG
* Bump version of https://github.com/poseidon/terraform-render-bootkube
* Update hyperkube from v1.8.3 to v1.8.4
* Remove flock from bootstrap-apiserver and kube-apiserver
* Remove unused critical-pod annotations in manifests
* Use service accounts for kube-proxy and pod-checkpointer
* Update Calico from v2.6.1 to v2.6.3
* Update flannel from v0.9.0 to v0.9.1
* Remove Calico termination grace period to prevent calico from getting stuck for extended periods
=> Update to Kubernetes v1.8.4

CHANGES.md, docs/bare-metal.md, docs/google-cloud.md
* Container Linux stable and beta now provide Docker 17.09 (instead of 1.12). Recommend images which provide 17.09.
* Older clusters (with CLUO addon) auto-update node's Container Linux version and will begin using Docker 17.09. No issues were observed on running clusters which automatically updated.
rel: #47
=> Recommend Container Linux images with Docker 17.09

aws/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl
* bootkube/assets/experimental/* assets corresponded to self-hosted etcd manifests, which are no longer an option in Typhoon
@elemental-lf this is similar to your edit. No issues for you if these get removed right?
=> Eliminate steps to move self-hosted etcd assets

docs/addons/prometheus.md
"eg. 315" doesn't help nearly as much as a link to the same thing
=> Add link to dashboard 315

CHANGES.md, README.md, aws/container-linux/kubernetes/README.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/README.md, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, docs/addons/cluo.md, docs/aws.md, docs/bare-metal.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
* Update Kubernetes from v1.8.x to v1.9.1
* Update kube-dns for Kubernetes 1.9
* Update Calico from v2.6.4 to 2.6.5
* Change apiserver --admission-control for v1.9
* Enable portmap to fix hostPort with Calico
* Update etcd from 3.2.0 to 3.2.13
* Docs fixes
Don't use this branch directly in your infrastructure. Rebases and changes are expected so the hash may change and the branch won't stick around after release. Fork and reference that.*
Used for all clusters by the maintainer, across all platforms.
=> Batch updates from Kubernetes v1.8.6 to v1.9.1

CHANGES.md, README.md, docs/aws.md, docs/bare-metal.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, docs/topics/maintenance.md
* Add explicit "providers" section to modules for Terraform v0.11.x
* Retain support for Terraform v0.10.4+
* Add migration guide from Terraform v0.10.x to v0.11.x for those managing existing clusters (action required!)
Switched to Terraform v0.11.1 in December for all clusters. Migration was tricky, but led to writing this migration guide. No issues since getting all Terraform configs happy with v0.11.1.
rel: #93 
Closes #77
=> Add Terraform v0.11.x support and migration docs

CHANGES.md, bare-metal/container-linux/kubernetes/groups.tf, bare-metal/container-linux/kubernetes/profiles.tf
Create separate bare-metal `container-linux-install` (or `cached-container-linux-install`) profiles for each node in a cluster. Name the profile after the cluster and node name (should be unique):
* Fix contention bug around bare-metal "container-linux-install" profile `terraform apply`. Apply ensures Matchbox profiles and groups are created for each cluster and its nodes. "container-linux-install" is not namespaced, meaning deletion of a cluster requests the profile's deletion, but existing clusters request its creation (or continued existence). This can mean users have to run `terraform apply` more than once until the constraints are satisfied (i.e. a deletion and recreation occurs).
* Allows Container Linux installs to vary between clusters instead of using one global …
=> Create separate bare-metal container-linux-install profiles

digital-ocean/container-linux/kubernetes/network.tf
* Change port range from keyword "all" to "1-65535", which is the
same but with digitalocean provider 0.1.3 doesn't produce a diff
* Rearrange egress firewall rules to order the Digtial Ocean API
and provider returns. In current testing, this fixes the last diff
that was present on `terraform plan`.
With `digitalocean` provider 0.1.3 and the module at this commit, `terraform plan` seems to show no diff. This could change in future as it relies on some ordering and conventions on the Digital Ocean API side, but it should fix #3.
*Note: Its odd to specify ports for ICMP, but it seems to be the only way to satisfy the Terraform provider, which doesn't understand ICMP concepts. The Digital Ocean API just ignores the ICMP port value, correctly.*
=> Edit digital ocean port range and ordering to suppress diff

CHANGES.md, addons/cluo/update-agent.yaml, addons/cluo/update-operator.yaml
* Update CLUO from v0.4.1 to v0.5.0
* Earlier versions of CLUO fail to drain nodes on Kubernetes 1.9 so nodes drain one at a time repeatedly and Container Linux OS updates are not applied to nodes.
* Check current OS versions via `kubectl get nodes --show-labels`
rel: https://github.com/coreos/container-linux-update-operator/issues/163
=> addons: Update CLUO to fix compatability with Kubernetes 1.9

digital-ocean/container-linux/kubernetes/variables.tf, docs/digital-ocean.md
Digital Ocean have just [announced new droplet sizes](https://blog.digitalocean.com/new-droplet-plans/) with greater resources per price point compared with their previous offerings. They have also deprecated the existing sizes, which will be removed by July 1, 2018.
Users can now choose various combinations of CPU, memory, and disk resources, so the [droplet size names](https://developers.digitalocean.com/documentation/changelog/api-v2/new-size-slugs-for-droplet-plan-changes/) are a bit more complex.
* Update DO variable defaults to use the new sizes.
* Update docs with links to all available sizes.
I have just created a new cluster with these new default sizes and it seems to work fine. In fact it appears that even the slightly smaller `s-1vcpu-2gb` droplet can be used for a controller.
=> Update Digital Ocean variables / docs to use new droplet sizes

aws/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
Upgrade to the next major version of Calico. https://github.com/projectcalico/calico/releases/tag/v3.0.1
~Initial testing on GCE and AWS. This is a significant change and will simmer for some time.~
I've been using Calico 3.0.1 on GCE, AWS, and bare-metal clusters all week without issue.
=> Upgrade Calico from 2.6.6 to 3.0.x

CHANGES.md, addons/cluo/cluster-role-binding.yaml, addons/cluo/cluster-role.yaml, addons/cluo/update-agent.yaml, addons/cluo/update-operator.yaml, addons/grafana/deployment.yaml, addons/heapster/deployment.yaml, addons/nginx-ingress/aws/default-backend/deployment.yaml, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/aws/rbac/cluster-role-binding.yaml, addons/nginx-ingress/aws/rbac/cluster-role.yaml, addons/nginx-ingress/aws/rbac/role-binding.yaml, addons/nginx-ingress/aws/rbac/role.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/digital-ocean/default-backend/deployment.yaml, addons/nginx-ingress/digital-ocean/rbac/cluster-role-binding.yaml, addons/nginx-ingress/digital-ocean/rbac/cluster-role.yaml, addons/nginx-ingress/digital-ocean/rbac/role-binding.yaml, addons/nginx-ingress/digital-ocean/rbac/role.yaml, addons/nginx-ingress/google-cloud/default-backend/deployment.yaml, addons/nginx-ingress/google-cloud/deployment.yaml, addons/nginx-ingress/google-cloud/rbac/cluster-role-binding.yaml, addons/nginx-ingress/google-cloud/rbac/cluster-role.yaml, addons/nginx-ingress/google-cloud/rbac/role-binding.yaml, addons/nginx-ingress/google-cloud/rbac/role.yaml, addons/prometheus/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml, addons/prometheus/exporters/node-exporter/daemonset.yaml, addons/prometheus/rbac/cluster-role-binding.yaml, addons/prometheus/rbac/cluster-role.yaml
* Deployments now belong to the apps/v1 API group
* DaemonSets now belong to the apps/v1 API group
* RBAC types now belong to the rbac.authorization.k8s.io/v1 API group
=> addons: Switch to apps/v1 workload APIs

CHANGES.md, addons/heapster/cluster-role-binding.yaml, addons/heapster/deployment.yaml, addons/heapster/role-binding.yaml, addons/heapster/role.yaml, addons/heapster/service-account.yaml
* Switch to k8s.gcr.io vanity image name
* Add service account, Role, and ClusterRole for heapster
=> addons: Update Heapster from v1.5.0 to v1.5.1

aws/container-linux/kubernetes/ingress.tf, aws/container-linux/kubernetes/outputs.tf, aws/container-linux/kubernetes/require.tf, aws/container-linux/kubernetes/workers.tf
Typhoon clusters include an AWS load balancer for pairing with Ingress Controller deployments to terminate multiple HTTP and HTTPS applications exposed via Ingress.
Until now, Typhoon has used elastic load balancers (ELBs) (now called "classic balancers"). AWS now offers Network Load Balancers (NLBs) which can handle millions of requests per second. This is important given that the balancer multiplexes or terminates multiple end-user applications.
Impact:
* Create an Ingress network load balancer instead of an elastic load balancer
* Workers are added to `worker-http` and `workers-https` target groups (similar to GCP target pools)
* Relax the firewall rules to expose the Ingress health port. NLBs do not have their own security group, so they cannot be independently permitted to health …
=> Switch Ingress ELB to a network load balancer

README.md, docs/index.md
The author no longer works for CoreOS or Red Hat. There is no longer any ambiguity that this project is independently maintained so there isn't a real need for the disclosure.
Typhoon development continues as usual.
=> Remove author employment disclosure note

CHANGES.md, docs/advanced/overview.md, docs/advanced/worker-pools.md, docs/google-cloud.md, google-cloud/container-linux/kubernetes/cluster.tf, google-cloud/container-linux/kubernetes/outputs.tf, google-cloud/container-linux/kubernetes/workers/variables.tf, mkdocs.yml
* Allow "pools" of homogeneous workers to be created using the `google-cloud/kubernetes/workers` Terraform (sub)module
* Examples: Add workers with a different machine type, larger disk, different preemptibility, GPUs (upcoming), etc.
Given a cluster "google-cloud-yavin" was created following the [tutorial](https://typhoon.psdn.io/google-cloud/), worker pool(s) can be attached with:
```
module "yavin-worker-pool" {
source = "git::https://github.com/poseidon/typhoon//google-cloud/container-linux/kubernetes/workers?ref=v1.9.4"
network      = "${module.google-cloud-yavin.network_name}"
region       = "us-central1"
count        = 2
machine_type = "n1-standard-16"
preemptible  = true
cluster_name = "yavin-16x"
ssh_authorized_key = "${var.ssh_authorized_key}"
kubeconfig = …
```
=> Add support for worker pools on Google Cloud

docs/advanced/worker-pools.md, google-cloud/container-linux/kubernetes/cluster.tf, google-cloud/container-linux/kubernetes/workers/ingress.tf, google-cloud/container-linux/kubernetes/workers/variables.tf, google-cloud/container-linux/kubernetes/workers/workers.tf
* Fix issue where worker firewall rules didn't apply to additional workers attached to a GCP cluster using the new "worker pools" feature (unreleased, #148). Solves host connection timeouts and pods not being scheduled to attached worker pools.
* Add `name` field to GCP internal worker module to represent the unique name of the worker pool
* Use `cluster_name` field of GCP internal worker module for passing the name of the cluster to which workers should be attached
No security impact. The worker pool firewalls default to disallow. This issue is about lacking whitelisting rules (i.e. they're too strict) that should be present.
No breakages. The new required `name` field is not covered in the changelog because through the v1.9.3 release, the Terraform "worker" submodule was considered …
=> Fix overly strict firewall for GCP "worker pools"

CHANGES.md, addons/grafana/dashboard-providers.yaml, addons/grafana/dashboards.yaml, addons/grafana/datasources.yaml, addons/grafana/deployment.yaml, addons/prometheus/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/service.yaml, addons/prometheus/rules.yaml, addons/prometheus/service.yaml
* Annotate Prometheus service to scrape metrics from Prometheus itself (enables Prometheus* alerts)
* Update kube-state-metrics addon-resizer to 1.7
* Use port 8080 for kube-state-metrics
* Add PrometheusNotIngestingSamples alert rule
* Change K8SKubeletDown alert rule to fire when 10% of kubelets are down, not 1%
* coreos/prometheus-operator#1032
* Update from Grafana v4.6.3 to v5.0.1
* Change dashboard org role to Viewer
=> Update Prometheus and Grafana monitoring stack

CHANGES.md, aws/container-linux/kubernetes/workers/workers.tf
Fix AWS worker launch configs and worker pool launch configs to stop producing a diff when Container Linux releases a new AMI.
* AWS controllers were protected by the fix https://github.com/poseidon/typhoon/commit/c8313751d7ec4af5766cc93c7cd29ccbc2cb7a7d
* AWS workers were not, because the `image_id` field is on the launch config, not the scaling group.
=> Add ignore_changes for AWS worker image_id

CHANGES.md, aws/container-linux/kubernetes/apiserver.tf, aws/container-linux/kubernetes/require.tf, aws/container-linux/kubernetes/workers/ingress.tf
Cross zone load balancing is a new feature available now that we use NLBs. According to the AWS blog [announcement](https://aws.amazon.com/about-aws/whats-new/2018/02/network-load-balancer-now-supports-cross-zone-load-balancing/),
* Before: "Prior to this support, Network Load Balancer routed requests only to targets located in the same Availability Zone. This meant that in scenarios where the clients were caching the DNS information of a zonal Network Load Balancer, some targets could receive a disproportionally higher number of inbound requests."
* Enabled: "requests are distributed equally to your targets regardless of the Availability Zone in which they are located"
We're opting to enable cross zone load balancing for the apiserver and ingress.
Testing: In Progress
Requires: …
=> Enable AWS NLB cross-zone load balancing

CHANGES.md, google-cloud/container-linux/kubernetes/require.tf, google-cloud/container-linux/kubernetes/workers/variables.tf, google-cloud/container-linux/kubernetes/workers/workers.tf
**Warning**: This does **not** magically make GPUs work on Container Linux or Kubernetes. It simply allows advanced users to begin experimenting with them. Like the comments imply, this feature is unofficial, undocumented, unsupported, and may be changed or removed at any time.
Caveats:
* Requires changes to Google Cloud default quotas
* Requires using `terraform-provider-google` 1.6.0 or higher to work with "0" GPUs properly
* Requires compiling your own kernel modules on Container Linux. (It's possible, I've done it. Just lots of rough edges)
* Some instances will remain un-created forever, because no GPU model is uniformly available across zones and workers are randomized into zones within a region automatically (a Typhoon feature). We just have to fiddle with the count until GCP …
=> Allow Google accelerators (i.e. GPUs) on workers

CHANGES.md, README.md, aws/container-linux/kubernetes/README.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/README.md, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, docs/advanced/worker-pools.md, docs/aws.md, docs/bare-metal.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, docs/topics/maintenance.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#v194
Upstream made a breaking change https://github.com/kubernetes/kubernetes/pull/58720. It impacts the Grafana addon.
> "Secret, configMap, downwardAPI and projected volumes will be mounted as read-only volumes. Applications that attempt to write to these volumes will receive read-only filesystem errors. Previously, applications were allowed to make changes to these volumes, but those changes were reverted at an arbitrary interval by the system. Applications should be re-configured to write derived files to another location."
Grafana attempts to chown any dashboards its given, so I'm not sure of the workaround.
=> Update Kubernetes from v1.9.3 to v1.9.4

aws/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl
* Add a `node-role.kubernetes.io/controller="true"` node label to controllers so Prometheus service discovery can filter to services that only run on controllers (i.e. masters)
* Leave `node-role.kubernetes.io/master=""` untouched as its a Kubernetes convention
Value: Users who choose to deploy the Prometheus addon, can now discover etcd (unblocks #14). These key=value labels may also be useful for end-users pinning special applications to controllers.
Related:
* https://github.com/coreos/tectonic-installer/issues/1439
* https://github.com/kubernetes-incubator/kubespray/issues/2108
Terminology note: We say "controller" in Typhoon (being progressive and all). For all intensive purposes, this means the same as "master" in other distributions.
=> Add a new key=value label to controller nodes

CHANGES.md, aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/container-linux/kubernetes/variables.tf, digital-ocean/container-linux/kubernetes/workers.tf, docs/advanced/customization.md, docs/aws.md, docs/digital-ocean.md, docs/google-cloud.md, docs/topics/maintenance.md, google-cloud/container-linux/kubernetes/cluster.tf, google-cloud/container-linux/kubernetes/controllers/controllers.tf, google-cloud/container-linux/kubernetes/controllers/variables.tf, google-cloud/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/workers/variables.tf, google-cloud/container-linux/kubernetes/workers/workers.tf
Introduce the ability for users to supply Container Linux Config "snippets" for controllers or workers. Snippets are valid Container Linux Configs which are additively merged into the base Container Linux Configs that Typhoon uses to provision controllers and workers. Configs are validated, merged into a single config for use in instance user-data. Validation errors are shown with line numbers during `terraform plan`.
This is a major feature and has been long awaited.
* Allows users to add custom systemd units, network configs, files, raid arrays, or other customizations related to on-host disk provisioning that is supported by Container Linux Configs (at Ignition v2.0.0).
* Reduces user temptation to add a Terraform variable for every option. This helps keep Typhoon modules readable and …
=> Add support for Container Linux Config snippets

CHANGES.md, aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/ssh.tf, bare-metal/container-linux/kubernetes/ssh.tf, digital-ocean/container-linux/kubernetes/ssh.tf, google-cloud/container-linux/kubernetes/controllers/controllers.tf, google-cloud/container-linux/kubernetes/ssh.tf, google-cloud/container-linux/kubernetes/variables.tf
* Ensure etcd secrets are only distributed to controller hosts (Digital Ocean)
* On DO, etcd secrets were erroneously distributed to worker nodes. Note etcd secrets always had permission 500 and were owned by etcd:etcd. But still, workers don't need these secrets.
* Remove redundant kubeconfig copy on AWS and GCP
* AWS and Google Cloud make use of auto-scaling groups and managed instance groups, respectively. As such, the kubeconfig is already held in cloud user-data
* Controller instances are provisioned with a kubeconfig from user-data. Its redundant to use a Terraform remote file copy step for the kubeconfig
* Use consistent naming of remote provision steps
* Replace usage of /home/core with $HOME
=> Cleanup remote provision steps across platforms

CHANGES.md, addons/grafana/dashboard-providers.yaml, addons/grafana/dashboards.yaml, addons/grafana/datasources.yaml, addons/grafana/deployment.yaml
This commit undoes the revert of https://github.com/poseidon/typhoon/pull/153
rel: https://github.com/grafana/grafana-docker/issues/140
=> addons: Update from Grafana v4.6.3 to v5.0.4

CHANGES.md, aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, docs/aws.md
* Change EBS volume type from `standard` ("prior generation) to `gp2` (SSD). Prometheus alerts are tuned for SSDs
* Other platforms have fast enough disks by default
rel: #175
=> Add disk_type variable for EBS volume type on AWS

CHANGES.md, addons/prometheus/config.yaml, addons/prometheus/deployment.yaml, addons/prometheus/rules.yaml, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/security.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/network.tf
* Use etcd v3.3 `--listen-metrics-urls` to expose only metrics data via http://0.0.0.0:2381 on controllers
* Add Prometheus discovery for etcd peers on controller nodes
* Enables etcd related alerts and populates the etcd Grafana dashboard
* Note: These benefits require the optional Prometheus and Grafana addons be applied.
Hold off on allowing workers firewall access (can't think of any concrete concern with workloads seeing this). Move Prometheus to a controller node for a while (maybe drop). Adjust firewall rules now that Prometheus can run on a controller, rather than a worker
Made possible by:
* https://github.com/coreos/etcd/issues/8060 thanks @gyuho @brancz
* https://github.com/coreos/etcd/pull/8242
Closes #114
=> Add etcd metrics, Prometheus scrapes, and Grafana dash

addons/prometheus/deployment.yaml, aws/container-linux/kubernetes/security.tf, google-cloud/container-linux/kubernetes/network.tf
* Expose etcd metrics to workers so Prometheus can run on a worker, rather than a controller
* Drop temporary firewall rules allowing Prometheus to run on a controller and scrape targes
* Related to https://github.com/poseidon/typhoon/pull/175
=> Return Prometheus deployment to be a worker workload

CHANGES.md, addons/nginx-ingress/aws/default-backend/deployment.yaml, addons/nginx-ingress/digital-ocean/default-backend/deployment.yaml, addons/nginx-ingress/google-cloud/default-backend/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
* Kubernetes recommends using the alias to fetch images from the nearest GCR regional mirror, to abstract the use of GCR, and to drop names containing 'google'
* https://groups.google.com/forum/#!msg/kubernetes-dev/ytjk_rNrTa0/3EFUHvovCAAJ
=> Use k8s.gcr.io instead of gcr.io/google_containers

CHANGES.md, bare-metal/container-linux/kubernetes/cl/container-linux-install.yaml.tmpl, bare-metal/container-linux/kubernetes/groups.tf, bare-metal/container-linux/kubernetes/profiles.tf, docs/bare-metal.md
* Terraform v0.11.4 introduced changes to remote-exec that mean Typhoon bare-metal clusters require multiple runs of terraform apply to ssh and bootstrap.
* Bare-metal installs PXE boot a live instance to install to disk and then reboot from disk as controllers/workers.Terraform remote-exec has no way to "know" to wait until the reboot has occurred to kickoff Kubernetes bootstrap. Previously Typhoon created a "debug" user during this install phase to allow an admin to SSH, but remote-exec would hang, trying to connect as user "core". Terraform v0.11.4 changes this behavior so remote-exec fails and a user must re-run terraform apply until succeeding.
* A new way to "trick" remote-exec into waiting for the reboot into the disk install is to run SSH on a non-standard port during the disk …
=> Fix bare-metal multiple apply/ssh on Terraform v0.11.4+

docs/topics/hardware.md
Previous example may have been outdated. It resulted in `error: unable to recognize "example.yaml": no matches for /, Kind=bgpPeer` .
See https://docs.projectcalico.org/v3.0/reference/calicoctl/resources/bgppeer.
=> Update example BGPPeer manifest

CHANGES.md, docs/google-cloud.md, docs/topics/performance.md, google-cloud/container-linux/kubernetes/apiserver.tf, google-cloud/container-linux/kubernetes/controllers.tf, google-cloud/container-linux/kubernetes/ssh.tf
* Allow multi-controller clusters on Google Cloud
* GCP regional network load balancers have a long open bug in which requests originating from a backend instance are routed to the instance itself, regardless of whether the health check passes or not. As a result, only the 0th controller node registers. We've recommended just using single master GCP clusters for a while
* https://issuetracker.google.com/issues/67366622
* Workaround issue by switching to a GCP TCP Proxy load balancer. TCP proxy lb routes traffic to a backend service (global) of instance group backends. In our case, spread controllers across 3 zones (all regions have 3+ zones) and organize them in 3 zonal unmanaged instance groups that serve as backends. Allows multi-controller cluster creation
* GCP network load balancers …
=> Switch GCP network lb to global TCP proxy lb

CHANGES.md, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, aws/fedora-atomic/kubernetes/variables.tf, aws/fedora-atomic/kubernetes/workers.tf, aws/fedora-atomic/kubernetes/workers/variables.tf, aws/fedora-atomic/kubernetes/workers/workers.tf, docs/advanced/worker-pools.md, docs/atomic/aws.md, docs/cl/aws.md
* Add `worker_price` to allow worker spot instances. Defaults to empty string for the worker autoscaling group to use regular on-demand instances.
* Add `spot_price` to internal `workers` module for spot [worker pools](https://typhoon.psdn.io/advanced/worker-pools/)
* Note: Unlike GCP `preemptible` workers, spot instances require you to pick a bid price.
=> Allow preemptible workers on AWS via spot instances

CHANGES.md, addons/prometheus/deployment.yaml
* A data volume (emptyDir) is mounted to `/var/lib/prometheus`
* Users could swap emptyDir for any desired volume if data persistence is desired. Prometheus previously defaulted to keeping its data in ./data relative to /prometheus. Override this behavior to store data in `/var/lib/prometheus`
=> Fix Prometheus data dir to /var/lib/prometheus

CHANGES.md, aws/container-linux/kubernetes/require.tf, aws/fedora-atomic/kubernetes/require.tf, bare-metal/container-linux/kubernetes/require.tf, bare-metal/fedora-atomic/kubernetes/require.tf, digital-ocean/container-linux/kubernetes/require.tf, digital-ocean/fedora-atomic/kubernetes/require.tf, google-cloud/container-linux/kubernetes/require.tf, google-cloud/fedora-atomic/kubernetes/require.tf
* Raise minimum Terraform version to v0.11.0
* Terraform v0.11.x has been supported since Typhoon v1.9.2 and Terraform v0.10.x was last released in Nov 2017. I'd like to stop worrying about v0.10.x and remove migration docs as a later followup
* Migration docs docs/topics/maintenance.md#terraform-v011x
=> Require Terraform v0.11.x, drop v0.10.x support

CHANGES.md, aws/container-linux/kubernetes/ami.tf, aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers.tf, aws/container-linux/kubernetes/workers/ami.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, docs/advanced/worker-pools.md, docs/cl/aws.md
* Change AWS optional os_channel variable to represent an AMI channel for a Container Linux derivative
* Allow the Flatcar Linux Container Linux derivative os_channel on AWS with `flatcar-stable`, `flatcar-beta`, `flatcar-alpha`. Nice drop-in replacement.
* Require values `stable`, `beta`, `alpha` be changed to `coreos-stable` (default), `coreos-beta`, `coreos-alpha` if they were set
```
$ kubectl describe nodes
...
System Info:
Machine ID:                 8c859f2bde9e41155bca40d2d85aebb5
System UUID:                EC2F0AE5-55A4-0FDD-8F06-4F2FC5EA09A3
Boot ID:                    5d08c248-c559-4687-9bd5-21f79fd03b56
Kernel Version:             4.14.32-flatcar
OS Image:                   Flatcar Linux by Kinvolk 1688.5.3 (Rhyolite)
Operating System:           linux
Architecture: …
```
=> Allow Flatcar Linux os_channel on AWS

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, aws/fedora-atomic/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, aws/fedora-atomic/kubernetes/workers/cloudinit/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/worker.yaml.tmpl, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/workers/cloudinit/worker.yaml.tmpl
* Require Webhook authorization to the Kubelet
* Switch apiserver X509 client cert org to systems:masters to grant the apiserver admin and satisfy the authorization requirement. kubectl commands like logs or exec that have the apiserver make requests of a kubelet continue to work as before
* https://kubernetes.io/docs/admin/kubelet-authentication-authorization/
* https://github.com/poseidon/typhoon/issues/215
=> Allow bearer token authn/authz to the Kubelet

CHANGES.md, addons/prometheus/config.yaml, addons/prometheus/rbac/cluster-role.yaml, aws/container-linux/kubernetes/security.tf, aws/fedora-atomic/kubernetes/security.tf, google-cloud/container-linux/kubernetes/network.tf, google-cloud/fedora-atomic/kubernetes/network.tf
* Use Kubelet bearer token authn/authz to scrape metrics
* Drop RBAC permission from nodes/proxy to nodes/metrics
* Stop proxying kubelet scrapes through the apiserver, since this required higher privilege (nodes/proxy) and can add load to the apiserver on large clusters
=>  Configure Prometheus to scrape Kubelets directly

CHANGES.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/variables.tf, docs/cl/bare-metal.md
* Allow setting the Calico host IPv4 address autodetection method
* Use Calico's default "first-found" method to support single NIC and bonded NIC nodes
* Allow methods like `can-reach=IP` or `interface=REGEX` for multi NIC nodes
* https://docs.projectcalico.org/v3.1/reference/node/configuration#ip-autodetection-methods
Note: I've only added this to Container Linux for now.
Closes #124
=> Add bare-metal network_ip_autodetection_method variable for multi-NIC

CHANGES.md, bare-metal/container-linux/kubernetes/cl/install.yaml.tmpl, bare-metal/container-linux/kubernetes/groups.tf, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/variables.tf, docs/cl/bare-metal.md
* Allow for Container Linux derivatives
* Replace container_linux_channel variable with `os_channel`
* Replace `container_linux_version` variable with `os_version`
* Please change values `stable`, `beta`, or `alpha` to `coreos-stable`, `coreos-beta`, `coreos-alpha` (action required!)
* Deprecate `container_linux_oem`
=> Rename container_linux_ bare-metal variables

CHANGES.md, bare-metal/container-linux/kubernetes/cl/install.yaml.tmpl, bare-metal/container-linux/kubernetes/groups.tf, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/variables.tf, docs/cl/bare-metal.md
* Choose the Container Linux derivative Flatcar Linux on bare-metal by setting os_channel to flatcar-stable, flatcar-beta or flatcar-alpha
* As with Container Linux from Red Hat, the version (os_version) must correspond to the channel being used
* Thank you to @dongsupark from Kinvolk
atop: #219
rel: #209 #211
=>  Allow Flatcar Linux os_channel on bare-metal

CHANGES.md, digital-ocean/fedora-atomic/kubernetes/variables.tf
* Fedora Atomic 27 images disappeared from DigitalOcean and forced this early update (there are known bugs)
Fixes #223
=> Update Fedora Atomic from 27 to 28 on DigitalOcean

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl
* https://github.com/coreos/etcd/releases/tag/v3.3.8
=> Update etcd from v3.3.7 to v3.3.8

CHANGES.md, aws/container-linux/kubernetes/apiserver.tf, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/security.tf, aws/fedora-atomic/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/security.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/network.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/network.tf, docs/addons/ingress.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Change load balancers, firewall rules, security groups, and generated kubeconfig's
=> Change apiserver port from 443 to 6443 (except GCP)

CHANGES.md, aws/container-linux/kubernetes/nlb.tf, aws/container-linux/kubernetes/outputs.tf, aws/container-linux/kubernetes/workers/ingress.tf, aws/container-linux/kubernetes/workers/outputs.tf, aws/fedora-atomic/kubernetes/nlb.tf, aws/fedora-atomic/kubernetes/outputs.tf, aws/fedora-atomic/kubernetes/workers/ingress.tf, aws/fedora-atomic/kubernetes/workers/outputs.tf
* Simplify clusters to come with a single NLB
* Listen for apiserver traffic on port 6443 and forward to controllers (with healthy apiserver)
* Listen for ingress traffic on ports 80/443 and forward to workers (with healthy ingress controller)
* Reduce cost of default clusters by 1 NLB ($18.14/month)
* Keep using CNAME records to the NLB's `ingress_dns_name` (module output) and the `nginx-ingress` addon for Ingress (up to a few million RPS). No change.
* Users with heavy traffic (many million RPS) can create their own separate NLB(s) for Ingress and use the new output worker target groups
* Fix issue where additional worker pools came with an extraneous network load balancer.
Overall, folks don't need to make any changes. No cluster variables or outputs have changed. In the next release, …
=>  Combine AWS NLBs to use one NLB per cluster

CHANGES.md, aws/container-linux/kubernetes/workers/workers.tf, aws/fedora-atomic/kubernetes/workers/workers.tf
* Basic monitoring (free) is sufficient for casual console browsing
* Detailed monitoring (paid) is not leveraged for CloudWatch anyway
* Favor Prometheus for cloud-agnostic metrics, aggregation, and alerting
For context here, detailed monitoring was only ever enabled on workers because its defaulted to on in launch configurations. Its never been enabled for controllers. While the additional fees are modest, there's simply not a justification for it.
=> Disable AWS detailed monitoring on worker nodes

CHANGES.md, aws/fedora-atomic/kubernetes/ami.tf, aws/fedora-atomic/kubernetes/workers/ami.tf
=> Update Fedora Atomic from 27 to 28 on AWS

CHANGES.md, bare-metal/fedora-atomic/kubernetes/groups.tf, bare-metal/fedora-atomic/kubernetes/kickstart/fedora-atomic.ks.tmpl, bare-metal/fedora-atomic/kubernetes/profiles.tf, bare-metal/fedora-atomic/kubernetes/variables.tf, docs/atomic/bare-metal.md
Validated on Supermicro servers. Had difficulties getting Anaconda to install on some IBM systems.
I'd recommend choosing Container Linux. If you do need Fedora Atomic, evaluate each release on your hardware carefully. Mileage varies a lot.
=> Update Fedora Atomic from 27 to 28 on bare-metal

CHANGES.md, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/variables.tf, docs/advanced/customization.md, docs/cl/bare-metal.md
Introduce [Container Linux Config snippets](https://typhoon.psdn.io/advanced/customization/#container-linux) on bare-metal. These were introduced for AWS/Google/DO previously.
* Validate and additively merge custom Container Linux Configs during terraform plan
* Define files, systemd units, dropins, networkd configs, mounts, users, and more
* [Require](https://typhoon.psdn.io/cl/bare-metal/#terraform-setup) `terraform-provider-ct` plugin v0.2.1 (action required!)
Container Linux config snippets provide a mechanism for adding host customizations and enforcing those customizations merge to produce valid Ignition. It also eliminates advanced use cases that previously required forking (just to name a few from my own clusters - custom RAID setups, bonded NICs, custom mount units). The actual …
=> Support Container Linux Config snippets on bare-metal

CHANGES.md, aws/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, aws/fedora-atomic/kubernetes/workers/cloudinit/worker.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/worker.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/worker.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/workers/cloudinit/worker.yaml.tmpl
* Release [v1.11.1](https://github.com/poseidon/typhoon/releases/tag/v1.11.1) erroneously left Fedora Atomic clusters using the v1.11.0 Kubelet. The rest of the control plane ran v1.11.1 as expected
* Update Kubelet from v1.11.0 to v1.11.1 so Fedora Atomic matches Container Linux
* Container Linux modules were not affected
=> Fix Kublet version for Fedora Atomic modules

CHANGES.md, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/variables.tf
* Remove controller_networkds and worker_networkds variables. These variables were always listed as experimental, unsupported, and excluded from documentation in anticipation of Container Linux Config snippets
* Use Container Linux Config snippets on bare-metal instead. They provide safer, more powerful, and more elegant host customization
=> Remove unofficial bare-metal *_networkds variables

CHANGES.md, google-cloud/container-linux/kubernetes/network.tf, google-cloud/fedora-atomic/kubernetes/network.tf
* Nginx Ingress addon no longer uses hostNework so Prometheus may scrape port 10254 via the CNI network, rather than via the host address
rel: https://github.com/poseidon/typhoon/commit/2eaf04c68b3d469aeded276a0dc37d377451d61b
=> Remove GCP firewall rule allowing Nginx Ingress health

CHANGES.md, aws/container-linux/kubernetes/security.tf, aws/fedora-atomic/kubernetes/security.tf
* Deny ICMP packets for consistency across Typhoon clusters on various clouds and because there isn't much need to allow them
=> Remove AWS security rule allowing ICMP packets to nodes

google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers.tf, google-cloud/container-linux/kubernetes/workers/workers.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/controllers.tf
* Remove the last usage of `null_resource.repeat`, which has always been an eyesore for creating the etcd server list
* Originally, #224 switched to templating the etcd_servers list for all clouds, but had to revert on GCP in #237
=> Template etcd_servers list to replace null_resource.repeat

CHANGES.md, docs/topics/performance.md, google-cloud/container-linux/kubernetes/network.tf, google-cloud/fedora-atomic/kubernetes/network.tf
* Broaden internal-etcd firewall rule to allow etcd client traffic (2379) from other controller nodes
* Previously, kube-apiservers were only able to connect to their node's local etcd peer. While master node outages were tolerated, reaching a healthy peer took longer than necessary in some cases
* Reduce time needed to bootstrap a cluster
=> Fix firewall to allow etcd client traffic between controllers

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Manifest changes in https://github.com/poseidon/terraform-render-bootkube/pull/74
* Add new bird and felix readiness checks
* Read MTU from ConfigMap veth_mtu
* Add RBAC read for serviceaccounts
* Remove invalid description from CRDs
=> Update Calico from v3.1.3 to v3.2.1

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Continue to ensure scheduler and controller-manager run at least two replicas to support performing kubectl edits on single-master clusters (no change)
* For multi-master clusters, set scheduler / controller-manager replica count to the number of masters (e.g. a 3-master cluster previously used replicas:2, now replicas:3)
Motivation:
`kube-apiserver` has always been run as a DaemonSet across controllers to provide high availability, but `scheduler` and `controller-manager` were always run with replicas 2 (sufficient to support kubectl edits of the control plane without downtime). But if a cluster is running multiple controller nodes, we might as well run a higher replica count, tending toward one per node (users are paying for the nodes either way).
=> Raise scheduler/controller-manager replicas in multi-master

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Run at least two replicas of CoreDNS to better support rolling updates (previously, kube-dns had a pod nanny)
* On multi-master clusters, set the CoreDNS replica count to match the number of masters (e.g. a 3-master cluster previously used replicas:1, now replicas:3)
* Add AntiAffinity preferred rule to favor distributing CoreDNS pods across controller nodes nodes
=>  Raise CoreDNS replica count to at least 2

CHANGES.md, addons/cluo/update-agent.yaml, addons/cluo/update-operator.yaml, addons/grafana/deployment.yaml, addons/nginx-ingress/aws/default-backend/deployment.yaml, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/default-backend/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/default-backend/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/digital-ocean/default-backend/deployment.yaml, addons/nginx-ingress/google-cloud/default-backend/deployment.yaml, addons/nginx-ingress/google-cloud/deployment.yaml, addons/prometheus/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml, addons/prometheus/exporters/node-exporter/daemonset.yaml, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Annotate pods, deployments, and daemonsets to start containers with the Docker runtime's default seccomp profile
* Overrides Kubernetes default behavior which started containers with seccomp=unconfined
* https://docs.docker.com/engine/security/seccomp/#pass-a-profile-for-a-container
rel: https://github.com/poseidon/terraform-render-bootkube/commit/2437023c1050609b749850e9b2301a6f00713680
=> Add docker/default seccomp to control plane and addons

CHANGES.md, addons/heapster/cluster-role-binding.yaml, addons/heapster/cluster-role.yaml, addons/heapster/deployment.yaml
* Heapster can now get nodes (i.e. kubelets) from the apiserver and source metrics from the Kubelet authenticated API (10250) instead of the Kubelet HTTP read-only API (10255)
* https://github.com/kubernetes/heapster/blob/master/docs/source-configuration.md
* Use the heapster service account token via Kubelet bearer token authn/authz.
* Permit Heapster to skip CA verification. The CA cert does not contain IP SANs and cannot since nodes get random IPs that aren't known upfront. Heapster obtains the node list from the apiserver, so the risk of spoofing a node is limited. For the same reason, Prometheus scrapes must skip CA verification for scraping Kubelet's provided by the apiserver.
* https://github.com/poseidon/typhoon/blob/v1.12.1/addons/prometheus/config.yaml#L68
* Create a heapster …
=> Configure Heapster to source metrics from Kubelet authenticated API

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/security.tf, aws/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, aws/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, aws/fedora-atomic/kubernetes/security.tf, aws/fedora-atomic/kubernetes/workers/cloudinit/worker.yaml.tmpl, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, azure/container-linux/kubernetes/security.tf, azure/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/worker.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/network.tf, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/network.tf, google-cloud/fedora-atomic/kubernetes/workers/cloudinit/worker.yaml.tmpl
* We can finally disable the Kubelet read-only port 10255!
* The lengthy background on getting to this milestone: https://github.com/poseidon/typhoon/issues/322#issuecomment-431073073
Closes: #322
=> Disable Kubelet read-only port 10255

CHANGES.md, digital-ocean/container-linux/kubernetes/outputs.tf, digital-ocean/container-linux/kubernetes/workers.tf, docs/addons/ingress.md
* Improve the workers "round-robin" DNS FQDN that is created with each cluster by adding AAAA records
* CNAME's resolving to the DigitalOcean `workers_dns` output can be followed to find a droplet's IPv4 or IPv6 address
* The CNI portmap plugin doesn't support IPv6. Hosting IPv6 apps is possible, but requires editing the nginx-ingress addon with `hostNetwork: true`
=> Add DigitalOcean AAAA DNS records resolving to workers

CHANGES.md, docs/addons/ingress.md, docs/architecture/aws.md, docs/architecture/azure.md, docs/architecture/bare-metal.md, docs/architecture/digitalocean.md, docs/architecture/google-cloud.md, google-cloud/container-linux/kubernetes/ingress.tf, google-cloud/container-linux/kubernetes/outputs.tf, google-cloud/fedora-atomic/kubernetes/ingress.tf, google-cloud/fedora-atomic/kubernetes/outputs.tf, mkdocs.yml
* Allowing serving IPv6 applications via Kubernetes Ingress on Typhoon Google Cloud clusters
* Add `ingress_static_ipv6` output variable for use in AAAA DNS records
=> Add an IPv6 address and forwarding rules on Google Cloud

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* loop sends an initial query to detect infinite forwarding loops in configured upstream DNS servers and fast exit with an error (its a fatal misconfiguration on the network that will otherwise cause resolvers to consume memory/CPU until crashing, masking the problem)
* https://github.com/coredns/coredns/tree/master/plugin/loop
* loadbalance randomizes the ordering of A, AAAA, and MX records in responses to provide round-robin load balancing (as usual, clients may still cache responses though)
* https://github.com/coredns/coredns/tree/master/plugin/loadbalance
=> Enable CoreDNS loop and loadbalance plugins

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* https://coredns.io/2018/11/05/coredns-1.2.6-release/
=> Update CoreDNS from v1.2.4 to v1.2.6

CHANGES.md, azure/container-linux/kubernetes/require.tf, azure/container-linux/kubernetes/workers/workers.tf
* Fix known issue that Azure defaults to Deallocate eviction policy, which required manually restarting deallocated workers
* Require terraform-provider-azurerm v1.19+ to support setting the eviction_policy
=> Use eviction policy Delete for Low priority VMSS workers

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/variables.tf, aws/fedora-atomic/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/variables.tf, azure/container-linux/kubernetes/bootkube.tf, azure/container-linux/kubernetes/variables.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/variables.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/variables.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/variables.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/variables.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/variables.tf
* Calico Felix has been reporting anonymous usage data about the version and cluster size, which violates Typhoon's privacy policy where analytics should be opt-in only
* Add a variable enable_reporting (default: false) to allow opting in to reporting usage data to Calico (or future components)
rel: https://github.com/poseidon/terraform-render-bootkube/pull/90
=> Disable Calico Felix usage reporting, require opt-in

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Updates pod-checkpointer to prefer the Kubelet secure API (before falling back to the Kubelet read-only API that is disabled on Typhoon clusters since https://github.com/poseidon/typhoon/pull/324)
* Previously, pod-checkpointer checkpointed an initial set of pods during bootstrapping so recovery from power cycling clusters was unaffected, but logs were noisy
* https://github.com/poseidon/terraform-render-bootkube/pull/91
Related:
* https://github.com/kubernetes-incubator/bootkube/pull/1027
* https://github.com/kubernetes-incubator/bootkube/pull/1025
=> Update pod-checkpointer image to query Kubelet secure API

README.md, aws/container-linux/kubernetes/README.md, aws/fedora-atomic/kubernetes/README.md, azure/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/README.md, bare-metal/fedora-atomic/kubernetes/README.md, digital-ocean/container-linux/kubernetes/README.md, digital-ocean/fedora-atomic/kubernetes/README.md, docs/cl/aws.md, docs/index.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/fedora-atomic/kubernetes/README.md
* Remove bullet about isolating workloads on workers, its now common practice and new users will assume it
* List advanced features available in each module
* Fix erroneous Kubernetes version listing for Google Cloud Fedora Atomic
=> Improve features and modules list docs

CHANGES.md, docs/architecture/concepts.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/topics/maintenance.md
* Switch tutorials from using ~/.terraformrc to the Terraform [3rd-party plugin](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins) directory `~/.terraform.d/plugins` so plugin versions may be pinned
* Allows pinning `terraform-provider-ct` and `terraform-provider-matchbox` versions
* Improves safety of later plugin version migrations
* Continue to show using terraform-provider-ct v0.2.2. Updating to a newer version is only safe for clusters v1.12.2 or higher
Related: #296
=> Recommend switch from ~/.terraformrc to 3rd-party plugin dir

CHANGES.md, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl
* Allow using iSCSI with Container Linux bare-metal clusters
* Warning, iSCSI isn't part of Kubernetes conformance and isn't regularly evaluated
Adapts https://github.com/poseidon/typhoon/pull/103, closes #310
=> Add Kubelet /etc/iscsi and iscsiadm mounts on bare-metal

CHANGES.md, addons/grafana/deployment.yaml
* Example manifests aim to provide a read-only dashboard visible to any users with network access (i.e. kubectl port-forward, LAN)
* Problem: Grafana always has an admin user, even with the user
management system disabled
* Disable the login form to prevent admin login
=> Disable Grafana login form, admin user can't be disabled

aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/network.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/network.tf
* Add kube-router for pod networking and NetworkPolicy as an experiment
* Experiments are not documented or supported in any way, and may be removed without notice. They have known issues and aren't enabled without special options.
Functions on bare-metal and AWS. Does not work on Google Cloud.
=> Add experimental kube-router CNI provider

google-cloud/fedora-atomic/kubernetes/network.tf
This commit fixes a minor typo that was introduced in 76d993cdaefc2d6b88bc524bdec69ffc152d974b.
=> google-cloud/fedora-atomic/kubernetes: bgp typo

CHANGES.md, google-cloud/container-linux/kubernetes/apiserver.tf, google-cloud/fedora-atomic/kubernetes/apiserver.tf
* On GCP, kubectl port-forward connections to pods are closed after a timeout (unlike AWS NLB's or Azure load balancers)
* Increase the GCP apiserver backend service timeout from 1 minute to 5 minutes to be more similar to AWS/Azure LB behavior
=>  Increase GCP TCP proxy apiserver backend timeout to 5 minutes

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
Update Calico from v3.3.2 to [v3.4.0](https://docs.projectcalico.org/v3.4/releases/)
* Install CNI plugins with an init container rather than a sidecar
* Improve the `calico-node` ClusterRole
rel: https://github.com/poseidon/terraform-render-bootkube/pull/98
=> Update Calico from v3.3.2 to v3.4.0

CHANGES.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/topics/maintenance.md
* Provide migration instructions for upgrading terraform-provider-ct in-place for v1.12.2+ clusters
* Require switching from `~/.terraformrc` to the Terraform third-party plugins directory `~/.terraform.d/plugins/`
* Require Container Linux 1688.5.3 or newer
Closes #296
=> Update terraform-provider-ct plugin from v0.2.1 to v0.3.0

CHANGES.md, aws/container-linux/kubernetes/variables.tf, aws/fedora-atomic/kubernetes/variables.tf, docs/atomic/aws.md, docs/cl/aws.md, docs/topics/performance.md
T3 is the next generation general purpose burstable instance type. Compared with t2.small, the t3.small is cheaper, has 2 vCPU (instead of 1) and provides 5 Gbps of pod-to-pod bandwidth (instead of 1 Gbps)
references:
* https://aws.amazon.com/ec2/instance-types/
* https://aws.amazon.com/ec2/pricing/on-demand/
=> Change AWS default type from t2.small to t3.small

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Add separate ServiceAccounts and ClusterRoleBindings for kube-apiserver and kube-scheduler
* Remove the ClusterRoleBinding for the kube-system default ServiceAccount
* Rename the CA certificate CommonName for consistency with upstream
rel: https://github.com/poseidon/terraform-render-bootkube/pull/99
=> Add ServiceAccounts for kube-apiserver and kube-scheduler

aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/outputs.tf, aws/fedora-atomic/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/outputs.tf, azure/container-linux/kubernetes/bootkube.tf, azure/container-linux/kubernetes/outputs.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/outputs.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/outputs.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/outputs.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/outputs.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/outputs.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/outputs.tf
* Use a single admin kubeconfig for initial bootkube bootstrap and for use by a human admin. Previously, an admin kubeconfig without a named context was used for bootstrap and direct usage
with KUBECONFIG=path, while one with a named context was used for `kubectl config use-context` style usage. Confusing.
* Provide the admin kubeconfig via `assets/auth/kubeconfig`, `assets/auth/CLUSTER-config`, or output `kubeconfig-admin`
=> Use a single format of the admin kubeconfig

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* System components that require certificates signed by the cluster CA can submit a CSR to the apiserver, have an administrator inspect and approve it, and be issued a certificate
* Configure kube-controller-manager to sign Approved CSR's using the cluster CA private key
* Admins are responsible for approving or denying CSRs, otherwise, no certificate is issued. Read the Kubernetes docs carefully and verify the entity making the request and the authorization level
Related:
* #366
* https://github.com/poseidon/terraform-render-bootkube/pull/103
* https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
=> Enable the certificates.k8s.io API to issue cluster certificates

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Disable kube-scheduler and kube-controller-manager HTTP ports
rel: https://github.com/poseidon/terraform-render-bootkube/pull/105
=> Use HTTPS liveness probes for kube-scheduler and kube-controller-manager

CHANGES.md, aws/container-linux/kubernetes/outputs.tf, aws/fedora-atomic/kubernetes/outputs.tf
* DNS zones served by AWS Route53 may use AWS's special alias records (other DNS providers would use a CNAME) to resolve the ingress NLB.
* Alias records require the NLB DNS name's DNS zone id (not the cluster `dns_zone_id`). For example, the DNS zone of `cluster-nlb-123456789.elb.us-west-1.amazonaws.com`
=> Add AWS ingress_zone_id output with NLB DNS name's Route53 zone id

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Fix a regression caused by lowering the Kubelet TLS client certificate to system:nodes group (#100) since dropping cluster-admin dropped the Kubelet's ability to delete nodes.
* On clouds where workers can scale down (manual terraform apply, AWS spot termination, Azure low priority deletion), worker shutdown runs the delete-node.service to remove a node to prevent NotReady nodes from accumulating
* Allow Kubelets to delete cluster nodes via system:nodes group. Kubelets acting with system:node and kubelet-delete ClusterRoles is still an improvement over acting as cluster-admin
=> Fix instance shutdown automatic worker deletion on clouds

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/cluster-role.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/resizer-role-binding.yaml, addons/prometheus/exporters/kube-state-metrics/resizer-role.yaml
* Update kube-state-metrics ClusterRole to allow collecting poddisruptionbudget metrics (exported as `kube_poddisruptionbudget_*`)
* https://github.com/kubernetes/kube-state-metrics/pull/551
* Bump addon-resizer from v1.7 to v1.8.4
=> Allow kube-state-metrics PodDisruptionBudget metrics

CHANGES.md, addons/grafana/dashboards.yaml, addons/prometheus/exporters/node-exporter/daemonset.yaml, addons/prometheus/rules.yaml
* node-exporter renamed multiple metrics that are reflected in changes to Prometheus rules and Grafana dashboard expressions
* https://github.com/prometheus/node_exporter/blob/master/docs/example-16-compatibility-rules.yml
=> Update node-exporter from v0.15.2 to v0.17.0

docs/index.md
Considering the reader of each, the Github README module links can go to module source code and docs module links can go to the associated tutorial docs for the platform/OS
Closes #385
=> Fix per platform/OS links on the docs home page

CHANGES.md, azure/container-linux/kubernetes/controllers.tf, azure/container-linux/kubernetes/lb.tf, azure/container-linux/kubernetes/require.tf
* azurerm_public_ip (used internally) added a field `allocation_method` to replace the field `public_ip_address_allocation` (deprecated)
* Require terraform-provider-azurerm v1.21+
* https://github.com/terraform-providers/terraform-provider-azurerm/pull/2576
Fixes:
```
Warning: module.somecluster.azurerm_public_ip.apiserver-ipv4: "public_ip_address_allocation": [DEPRECATED] this property has been deprecated in favor of `allocation_method` to better match the api
...
```
=> Fix azure provider warning, rename a public_ip field

docs/architecture/digitalocean.md
I was reading the docs and found an `AWS` title for a `DigitalOcean` section.
Go to https://typhoon.psdn.io/architecture/digitalocean/ check title is not `AWS` anymore.
=> Fix section title in architecture docs

CHANGES.md, addons/prometheus/config.yaml
* Add Kubernetes pod name to metrics discovered from service endpoints
* Prometheus queries from some upstreams use joins of node-exporter and kube-state-metrics metrics by (namespace,pod). Add the Kubernetes `pod` name to service endpoint metrics
* Rename the `kubernetes_namespace` field to `namespace`
* Honor labels since kube-state-metrics already include a `pod` field that should not be overridden 
* Drop metrics that are unset, high cardinality, or extraneous
* https://github.com/coreos/prometheus-operator/pull/2387
* https://github.com/coreos/prometheus-operator/pull/1959
=> Improve Prometheus relabeling and drop extraneous metrics

CHANGES.md, docs/atomic/bare-metal.md, docs/cl/bare-metal.md, docs/topics/maintenance.md
* https://github.com/coreos/terraform-provider-matchbox/releases/tag/v0.2.3
Excerpts:
Add the [terraform-provider-matchbox](https://github.com/coreos/terraform-provider-matchbox) plugin binary for your system to `~/.terraform.d/plugins/`, noting the final name.
```sh
wget https://github.com/coreos/terraform-provider-matchbox/releases/download/v0.2.3/terraform-provider-matchbox-v0.2.3-linux-amd64.tar.gz
tar xzf terraform-provider-matchbox-v0.2.3-linux-amd64.tar.gz
mv terraform-provider-matchbox-v0.2.3-linux-amd64/terraform-provider-matchbox ~/.terraform.d/plugins/terraform-provider-matchbox_v0.2.3
```
Configure the Matchbox provider to use your Matchbox API endpoint and client certificate in a `providers.tf` file.
```tf
provider "matchbox" {
version     = "0.2.3"
endpoint    = …
```
=> Document and recommend terraform-provider-matchbox v0.2.3

CHANGES.md, google-cloud/container-linux/kubernetes/controllers.tf, google-cloud/container-linux/kubernetes/workers/workers.tf, google-cloud/fedora-atomic/kubernetes/controllers.tf, google-cloud/fedora-atomic/kubernetes/workers/workers.tf
* Intel Haswell or better is available in every zone around the world
* Neither Kubernetes nor Typhoon have a particular minimum processor family. However, a few Google Cloud zones still default to Sandy/Ivy bridge (scheduled to shift April 2019). Price is only based on machine type so it is beneficial to opt for the next processor family
* Intel Haswell is a suitable minimum since it still allows plenty of liberty in choosing any region or machine type
* Likely a slight increase to preemption probability in a few zones, but any lower probability on Sandy/Ivy bridge is due to lower desirability as they're phased out
* https://cloud.google.com/compute/docs/regions-zones/
=> Set the Google Cloud minimum CPU platform to Intel Haswell

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Assign pod priorityClassNames to critical cluster and node components (higher is higher priority) to inform node out-of-resource eviction order and scheduler preemption and scheduling order
* Priority Admission Controller has been enabled since Typhoon v1.11.1
=> Assign Pod Priority classes to critical cluster and node components

CHANGES.md, docs/atomic/google-cloud.md, docs/cl/google-cloud.md, google-cloud/container-linux/kubernetes/controllers.tf, google-cloud/container-linux/kubernetes/require.tf, google-cloud/fedora-atomic/kubernetes/controllers.tf, google-cloud/fedora-atomic/kubernetes/require.tf
* Support terraform-provider-google v1.19.0, v1.19.1, v1.20.0 and v2.0+ (and allow for future 2.x.y releases)
* Require terraform-provider-google v1.19.0 or newer. v1.19.0 introduced `network_interface` fields `network_ip` and `nat_ip` to deprecate `address` and `assigned_nat_ip`. Those deprecated fields are removed in terraform-provider-google v2.0
* https://github.com/terraform-providers/terraform-provider-google/releases/tag/v2.0.0
=> Upgrade to support terraform-provider-google v2.0+

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Resolve in-addr.arpa and ip6.arpa DNS PTR requests for Kubernetes service IPs and pod IPs
* Previously, CoreDNS was configured to resolve in-addr.arpa PTR records for service IPs (but not pod IPs)
Before:
```
$ dig 1.0.3.10.in-addr.arpa PTR
...
1.0.3.10.in-addr.arpa.  5       IN      PTR     kubernetes.default.svc.cluster.local.
$ 8.1.2.10.in-addr.arpa PTR
8.1.2.10.in-addr.arpa.  30      IN      PTR     ip-10-2-1-8.CLOUD_SPECIFIC_UPSTREAM
```
After:
```
$ dig 1.0.3.10.in-addr.arpa PTR
...
1.0.3.10.in-addr.arpa.  5       IN      PTR     kubernetes.default.svc.cluster.local.
$ 8.1.2.10.in-addr.arpa PTR
8.1.2.10.in-addr.arpa.  30      IN      PTR     10-2-1-8.prometheus.monitoring.svc.cluster.local.
```
Related:
* https://coredns.io/plugins/kubernetes/
* …
=>  Resolve in-addr.arpa and ip6.arpa zones with CoreDNS kubernetes plugin

CHANGES.md, aws/container-linux/kubernetes/require.tf, aws/fedora-atomic/kubernetes/require.tf, docs/atomic/aws.md, docs/atomic/bare-metal.md, docs/atomic/digital-ocean.md, docs/atomic/google-cloud.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md
* Allow `terraform-provider-aws` >= v1.13, but < 3.0. No change to the minimum version, but allow using v2.x.y releases
* Verify compatability with terraform-provider-aws v2.1.0
* https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v2.1.0
=> Add support for terraform-provider-aws v2.0+

CHANGES.md, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/variables.tf, docs/cl/bare-metal.md, docs/topics/hardware.md
* Require an iPXE-enabled network boot environment with support for TLS downloads. PXE clients must chainload to iPXE firmware compiled with `DOWNLOAD_PROTO_HTTPS` enabled ([crypto](https://ipxe.org/crypto))
* iPXE's pre-compiled firmware binaries do _not_ enable TLS. Admins should build iPXE from source with support enabled
* Affects the Container Linux and Flatcar Linux install profiles that install from public downloads. No effect when cached_install=true or using Fedora Atomic, as those download from Matchbox
* Add `download_protocol` variable. In iPXE environments lacking support, set the protocol to "http" for the old behavior (discouraged)
=> Change iPXE kernel/initrd download from HTTP to HTTPS

aws/container-linux/kubernetes/controllers.tf, aws/fedora-atomic/kubernetes/controllers.tf, azure/container-linux/kubernetes/controllers.tf, bare-metal/container-linux/kubernetes/groups.tf, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/fedora-atomic/kubernetes/groups.tf, bare-metal/fedora-atomic/kubernetes/profiles.tf, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/fedora-atomic/kubernetes/controllers.tf, google-cloud/container-linux/kubernetes/controllers.tf, google-cloud/container-linux/kubernetes/workers/workers.tf, google-cloud/fedora-atomic/kubernetes/controllers.tf, google-cloud/fedora-atomic/kubernetes/workers/workers.tf
* Terraform v0.11 allows explicit or implicit map assignments. In some cases, a mix has been used.
* Terraform v0.12 will require map assignments be explicit (e.g. `key = {}`)
=> Fix implicit map assignments to be explicit

CHANGES.md, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/worker.yaml.tmpl, docs/atomic/digital-ocean.md, docs/cl/digital-ocean.md
* Restore the original special-casing of DigitalOcean Kubelets
* Fix node metadata InternalIP being set to the IP of the default gateway on DigitalOcean nodes (regressed in v1.12.3)
* Reverts the "pretty" node names on DigitalOcean (worker-2 vs IP)
* Closes #424 (full details)
I'm sad to have to re-introduce this. But DigitalOcean is still a special case unfortunately. Reverts part of #337
=> Re-add Kubelet metadata service dependency on DigitalOcean

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Add calico-ipam CRDs and RBAC permissions
* Switch IPAM from host-local to calico-ipam
* `calico-ipam` subnets `ippools` (defaults to pod CIDR) into `ipamblocks` (defaults to /26, but set to /24 in Typhoon)
* `host-local` subnets the pod CIDR based on the node PodCIDR field (set via kube-controller-manager as /24's)
* Create a custom default IPv4 IPPool to ensure the block size is kept at /24 to allow 110 pods per node (Kubernetes default)
* Retaining host-local was slightly preferred, but Calico v3.6 is migrating all usage to calico-ipam. The codepath that skipped calico-ipam for KDD was removed
Related: https://github.com/poseidon/terraform-render-bootkube/pull/120
=> Update Calico from v3.5.2 to v3.6.0

addons/cluo/update-agent.yaml, addons/cluo/update-operator.yaml, addons/grafana/deployment.yaml, addons/prometheus/deployment.yaml
* Set resource requests and limits for Grafana and CLUO
* Set resource requests for Prometheus, but allow usage to grow since needs vary widely
* Leave nginx without resource requests/limits for now, its typically well behaved
=> Set cpu/memory resources requests/limits for some addons

CHANGES.md, addons/prometheus/network-policy.yaml
* Allow traffic from Grafana to Prometheus in monitoring
* Allow traffic from Prometheus to Prometheus in monitoring
* NetworkPolicy denies non-whitelisted traffic. Define policy to allow other access
=> Add NetworkPolicy to limit traffic into Prometheus

CHANGES.md, docs/atomic/aws.md, docs/atomic/google-cloud.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/topics/maintenance.md, requirements.txt
* Recommend provider plugin versions that are currently used by the author
* Recommend updating terraform-provider-ct plugin from v0.3.0 to v0.3.1
* https://github.com/coreos/terraform-provider-ct/releases
Updating from v0.3.0 to v0.3.1 does not alter the generated Ignition, so it should not produce a diff. To update from prior versions has special requirements. See the [guide](https://typhoon.psdn.io/topics/maintenance/#upgrade-terraform-provider-ct).
=> Update mkdocs and plugin versions used in tutorials

CHANGES.md, README.md, docs/announce.md, docs/atomic/aws.md, docs/atomic/bare-metal.md, docs/atomic/digital-ocean.md, docs/atomic/google-cloud.md, docs/index.md
* Thank you Project Atomic team and users!
* See the deprecation announcement https://typhoon.psdn.io/announce/#march-27-2019
=> Fedora Atomic modules won't be updated beyond v1.13.x

CHANGES.md, bare-metal/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/controllers.tf, google-cloud/container-linux/kubernetes/workers/workers.tf, google-cloud/fedora-atomic/kubernetes/controllers.tf, google-cloud/fedora-atomic/kubernetes/workers/workers.tf
* Google Cloud API implements `min_cpu_platform` to mean "use exactly this CPU"
* Fix error creating clusters in newer regions lacking Haswell platform (e.g. europe-west2) (#438)
* Reverts #405, added in v1.13.4
* Original goal of ignoring old Ivy/Sandy bridge CPUs in older regions will be achieved shortly anyway. Google Cloud is deprecating those CPUs in April 2019
* https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform#how_selecting_a_minimum_cpu_platform_works
=> Remove Haswell minimum CPU platform requirement

CHANGES.md, google-cloud/container-linux/kubernetes/network.tf, google-cloud/container-linux/kubernetes/outputs.tf, google-cloud/container-linux/kubernetes/workers/outputs.tf, google-cloud/container-linux/kubernetes/workers/target_pool.tf, google-cloud/container-linux/kubernetes/workers/workers.tf
* Background: Existing managed instance group of workers is used in backend services for global load balancing (HTTP/HTTPS Ingress) and output for custom global load balancing use cases
* Add and output a target pool of workers to allow load balancing for TCP/UDP applications (NodePort or proxied)
* Health check for workers with a healthy Ingress controller. Forward rules (regional) to target pools don't support different external and internal ports so choosing nodes with Ingress allows proxying
* A target pool is a logical grouping only. It doesn't add costs to clusters or worker pools
=> Add ability to load balance TCP/UDP applications on Google Cloud

CHANGES.md, aws/container-linux/kubernetes/outputs.tf, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, docs/cl/aws.md
* Add ability to load balance TCP applications (e.g. NodePort)
* Output the network load balancer ARN as `nlb_id`
* Accept a `worker_target_groups` (ARN) list to which worker instances should be added
* AWS NLBs and target groups don't support UDP
=> Add ability to load balance TCP applications on AWS

CHANGES.md, digital-ocean/container-linux/kubernetes/network.tf, digital-ocean/container-linux/kubernetes/outputs.tf
* Define firewall rules on DO to match rules used on AWS, GCP, Azure
* Output `controller_tag` and `worker_tag` to simplify custom firewall rule creation
=> Harden internal firewall rules on DigitalOcean

CHANGES.md, azure/container-linux/kubernetes/outputs.tf
* Add ability to load balance TCP/UDP applications (e.g. NodePort)
* Output the load balancer ID as `loadbalancer_id`
* Output `worker_security_group_name` and `worker_address_prefix` for extending firewall rules
=> Add ability to load balance TCP/UDP applications on Azure

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/cluster-role.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* Adds a metrics collector for Ingress resources and other improvements
* https://github.com/kubernetes/kube-state-metrics/pull/640
* https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.6.0-rc.0
=> Update kube-state-metrics from v1.5.0 to v1.6.0-rc.0

google-cloud/container-linux/kubernetes/workers/target_pool.tf
If no region is set at the Google provider level, Terraform fails to
create the google_compute_target_pool.workers resource and complains
with "Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'."
This commit fixes the issue by explicitly setting the region for the
google_compute_target_pool.workers resource.
=> Fix "google_compute_target_pool.workers: Cannot determine region"

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/cluster-role.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* This reverts commit 6e5d66cf666a2700ad3e540698a6e243651b96d9
* kube-state-metrics v1.6.0-rc.0 fires KubeDeploymentReplicasMismatch alerts where its own Deployment doesn't have replicas available, (kube_deployment_status_replicas_available) even though all replicas are available according to kubectl inspection
* This problem was present even with the CSR ClusterRole fix (https://github.com/kubernetes/kube-state-metrics/pull/717)
=> Revert "Update kube-state-metrics from v1.5.0 to v1.6.0-rc.0"

CHANGES.md, docs/announce.md, docs/atomic/bare-metal.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/topics/maintenance.md
* Matchbox, terraform-provider-matchbox, and terraform-provider-ct have moved to the poseidon Github organization
* https://groups.google.com/forum/#!topic/coreos-user/aWX6ygkeGSY
=> Update links to Matchbox, terraform-provider-ct, etc.

addons/nginx-ingress/aws/rbac/role.yaml, addons/nginx-ingress/azure/rbac/role.yaml, addons/nginx-ingress/bare-metal/rbac/role.yaml, addons/nginx-ingress/digital-ocean/rbac/role.yaml, addons/nginx-ingress/google-cloud/rbac/role.yaml
The "Ingress" role doesn't need to create/update endpoints as per
the upstream definition [1]. See also this commit [2]
[1]: https://github.com/kubernetes/ingress-nginx/blob/master/deploy/mandatory.yaml#L147
[2]: https://github.com/kubernetes/ingress-nginx/commit/a9168f276e97e2922ebefb5a8a476aef659abd6a#diff-ed87be01cf41ec539ce3a7542634323aL104
=> Nginx RBAC: sync role definition with upstream

aws/container-linux/kubernetes/workers.tf, aws/fedora-atomic/kubernetes/workers.tf, azure/container-linux/kubernetes/workers.tf, google-cloud/container-linux/kubernetes/workers.tf, google-cloud/fedora-atomic/kubernetes/workers.tf
With TF 0.11 it is strongly encouraged to use "./" prefix in module
path to indicate that the address is a relative filesystem
path. See [1]
With TF 0.12 this is now required. See [2].
This patch adds the "./" prefix where needed to ensure compatibility
with TF 0.12.
[1] https://www.terraform.io/docs/modules/sources.html#local-paths
[2] https://github.com/hashicorp/terraform/issues/19745
=> TF 0.12: module source: explicit usage of relative path

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl
* Skip updating etcd for Fedora Atomic clusters, now that Fedora Atomic has been deprecated
=> Update etcd from v3.3.12 to v3.3.13 on Container Linux

CHANGES.md, digital-ocean/container-linux/kubernetes/ssh.tf, digital-ocean/fedora-atomic/kubernetes/ssh.tf
* DigitalOcean clusters must secure copy a kubeconfig to worker nodes, but Terraform could decide to try copying before firewall rules have been added to allow SSH access.
* Add an explicit dependency on adding firewall rules first
=> Fix race condition in DigitalOcean cluster create

docs/atomic/aws.md, docs/atomic/bare-metal.md, docs/atomic/digital-ocean.md, docs/atomic/google-cloud.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md
* Fix install kubectl link to refer to upstream docs. Link to coreos.com is now outdated and directed users to install kubectl v1.8.4
* Reported in https://github.com/poseidon/typhoon/issues/476
=> Fix docs link for installing kubectl

CHANGES.md, azure/container-linux/kubernetes/bootkube.tf, azure/container-linux/kubernetes/variables.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/ssh.tf, digital-ocean/container-linux/kubernetes/variables.tf, digital-ocean/fedora-atomic/kubernetes/ssh.tf, docs/cl/azure.md, docs/cl/digital-ocean.md, docs/topics/performance.md
* Introduce "calico" as a `networking` option on Azure and DigitalOcean using Calico's new VXLAN support (similar to flannel). Flannel remains the default on these platforms for now.
* Historically, DigitalOcean and Azure only allowed Flannel as the CNI provider, since those platforms don't support IPIP traffic that was previously required for Calico.
* Looking forward, its desireable for Calico to become the default across Typhoon clusters, since it provides NetworkPolicy and a consistent experience
* No changes to AWS, GCP, or bare-metal where Calico remains the default CNI provider. On these platforms, IPIP mode will always be used, since its available and more performant than vxlan
=> Allow Calico networking on Azure and DigitalOcean

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Fix to remove a trailing slash that was erroneously introduced in the scripting that updated from v1.14.1 to v1.14.2
* Workaround in v1.14.2 release is to re-run `terraform init` once
=> Fix terraform-render-bootkube to remove trailing slash

CHANGES.md, azure/container-linux/kubernetes/require.tf, azure/container-linux/kubernetes/workers/workers.tf
* Fix Terraform provider azure warning about `azurerm_autoscale_setting`
* Require terraform-provider-azure v1.22+ version that introduces the new `azurerm_monitor_autoscale_setting` resource
* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1220-february-11-2019
=> Replace deprecated `azurerm_autoscale_setting`

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* Add `ready` plugin to improve readinessProbe
* https://coredns.io/2019/04/06/coredns-1.5.0-release/
=> Update CoreDNS from v1.3.1 to v1.5.0

CHANGES.md, aws/container-linux/kubernetes/workers.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, azure/container-linux/kubernetes/workers.tf, azure/container-linux/kubernetes/workers/variables.tf, azure/container-linux/kubernetes/workers/workers.tf, docs/advanced/worker-pools.md, google-cloud/container-linux/kubernetes/workers.tf, google-cloud/container-linux/kubernetes/workers/variables.tf, google-cloud/container-linux/kubernetes/workers/workers.tf
* This change affects users who use worker pools on AWS, GCP, or Azure with a Container Linux derivative
* Rename worker pool modules' `count` variable to `worker_count`, because `count` will be a reserved variable name in Terraform v0.12
=> Rename worker pool modules' count variable to worker_count

CHANGES.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md
* Recomment updating Terraform provider plugins `terraform-provider-ct`
and `terraform-provider-matchbox` to prepare for the upcoming Terraform
v0.12 migration
* https://github.com/poseidon/terraform-provider-ct/releases/tag/v0.3.2
* https://github.com/poseidon/terraform-provider-matchbox/releases/tag/v0.3.0
=> Recommend updating Terraform providers ct and matchbox

CHANGES.md, digital-ocean/container-linux/kubernetes/variables.tf, docs/cl/digital-ocean.md
* On DigitalOcean, `s-1vcpu-1gb` worker nodes have 1GB of RAM, which is too small as a default, even for most cost constrained developers
=> Change DO worker_type default from s-1vcpu-1gb to s-1vcpu-2gb

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v6.2.2
=> Update Grafana from v6.2.1 to v6.2.2

CHANGES.md, aws/container-linux/kubernetes/ami.tf, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers/ami.tf, aws/container-linux/kubernetes/workers/variables.tf, bare-metal/container-linux/kubernetes/variables.tf, docs/cl/aws.md, docs/cl/bare-metal.md, docs/index.md
* On AWS, use Flatcar Linux Edge by setting `os_image` to "flatcar-edge"
* On bare-metal, Flatcar Linux Edge by setting `os_channel` to "flatcar-edge"
Flatcar Linux Edge requires manually setting the Kubelet `--cgroup-driver=systemd` until #496
=> Allow using Flatcar Linux Edge on bare-metal and AWS

CHANGES.md, aws/container-linux/kubernetes/ami.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers/ami.tf, aws/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/variables.tf, docs/architecture/operating-systems.md, docs/cl/aws.md, docs/cl/bare-metal.md, docs/index.md
* For Container Linux or Flatcar Linux alpha/beta/stable, continue using the `cgroupfs` driver
* For Fedora Atomic, continue using the `systemd` driver
* For Flatcar Linux Edge, use the `systemd` driver
Related: #480
=>  Configure Kubelet cgroup-driver for Flatcar Linux Edge 

CHANGES.md, google-cloud/container-linux/kubernetes/apiserver.tf, google-cloud/container-linux/kubernetes/controllers.tf
* google_compute_backend_services use nested blocks to define backends (instance groups heterogeneous controllers)
* Use Terraform v0.12.x dynamic blocks so the apiserver backend service can refer to (up to zone-many) controller instance groups
* Previously, with Terraform v0.11.x, the apiserver backend service had to list a fixed set of backends to span controller nodes across zones in multi-controller setups. 3 backends were used because each
GCP region offered at least 3 zones. Single-controller clusters had the cosmetic ugliness of unused instance groups
* Allow controllers to span more than 3 zones in a region, if the region offers more than 3 zones (e.g. us-central1)
Related:
* https://www.terraform.io/docs/providers/google/r/compute_backend_service.html
* …
=> Improve apiserver backend service zone spanning on GCP

CHANGES.md, google-cloud/container-linux/kubernetes/network.tf
* Raise the network deletion timeout to 6m to ensure apply only needs to be run once to remove a cluster. Removal of a Google Cloud cluster often required 2 runs of `terraform apply` because network resource deletes timeout after 4m. 
* Fix a GCP errata item https://github.com/poseidon/typhoon/wiki/Errata
=> Increase GCP network deletion timeout from 4m to 6m

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/apiserver.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/network.tf
* Run kube-apiserver as a non-root user (nobody). User no longer needs to bind low number ports.
* On most platforms, the `kube-apiserver` load balancer listens on 6443 and fronts controllers with kube-apiserver pods using port 6443. Google Cloud TCP proxy load balancers cannot listen on 6443. However, GCP's load balancer can be made to listen on 443, while kube-apiserver uses 6443 across all platforms.
Related: https://github.com/poseidon/terraform-render-bootkube/pull/142 https://github.com/poseidon/terraform-render-bootkube/pull/141
=> Run kube-apiserver with lower privilege user (nobody)

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.11.0-rc.0
=> Update Prometheus from v2.10.0 to v2.11.0-rc.0

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/aws/rbac/cluster-role.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/azure/rbac/cluster-role.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/bare-metal/rbac/cluster-role.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/digital-ocean/rbac/cluster-role.yaml, addons/nginx-ingress/google-cloud/deployment.yaml, addons/nginx-ingress/google-cloud/rbac/cluster-role.yaml
* Support networking.k8s.io/v1beta1 apiVersion
* Update RBAC cluster-role for networking.k8s.io/v1beta1
* https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.25.0
=> Upgrade nginx-ingress from v0.24.1 to v0.25.0

CHANGES.md, aws/container-linux/kubernetes/versions.tf, azure/container-linux/kubernetes/versions.tf, bare-metal/container-linux/kubernetes/versions.tf, digital-ocean/container-linux/kubernetes/versions.tf, google-cloud/container-linux/kubernetes/versions.tf
* Allow updating terraform-provider-ct to any release beyond v0.3.2, but below v1.0. This relaxes the prior constraint that allowed only v0.3.y provider versions
=> Relax terraform-provider-ct version constraint

google-cloud/container-linux/kubernetes/apiserver.tf
* Intended as part of #504 improvement
* Single controller clusters only require one controller instance group (previously created zone-many)
* Multi-controller clusters must "wrap" controllers over zonal heterogeneous instance groups. For example, 5 controllers over 3 zones (no change)
=> Avoid creating extraneous GCE controller instance groups

CHANGES.md, azure/container-linux/kubernetes/controllers.tf
* Add all Azure controllers to the apiserver load balancer backend address pool
* Previously, kube-apiserver availability relied on the 0th controller being up. Multi-controller was just providing etcd data redundancy
=> Fix to add all Azure controller nodes to address pool

CHANGES.md, addons/grafana/dashboards-coredns.yaml, addons/grafana/dashboards-nginx-ingress.yaml, addons/grafana/deployment.yaml
* Add a CoreDNS dashboard originally based on an upstream dashboard, but now generated and customized according to preferences
* Add an Nginx Ingress Controller based on an upstream dashboard, but now generated and customized according to preferences
=> Add Grafana dashboards for CoreDNS and Nginx Ingress Controller

CHANGES.md, aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/versions.tf, aws/container-linux/kubernetes/workers/workers.tf, aws/fedora-coreos/kubernetes/controllers.tf, aws/fedora-coreos/kubernetes/versions.tf, aws/fedora-coreos/kubernetes/workers/workers.tf
* terraform-provider-aws v2.23.0 allows AWS root block devices to enable encryption by default
* Require updating terraform-provider-aws to v2.23.0 or higher (**action required**)
* Enable root EBS device encryption by default for controller instances and worker instances in auto-scaling groups
For comparison:
* Google Cloud persistent disks have been encrypted by default for years
* Azure managed disk encryption is not ready yet (terraform-provider-azurerm#486)
=> Enable AWS root block device encryption by default

docs/cl/google-cloud.md
High-level description of the change.
* Update doc spelling of worker_preemeptible to match the variable value(worker_preemptible) in one location in the document.
Ran terraform plan after trying variable worker_preemeptible and terraform failed asking if I meant worker_preemptible. I updated spelling in my tf to worker_preemptibleand did terraform plan and all was good.
rel: issue number (if applicable)
=> Variable spelling fix

CHANGES.md, addons/grafana/dashboards-coredns.yaml, addons/grafana/dashboards-etcd.yaml, addons/grafana/dashboards-nginx-ingress.yaml
* Use unique dashboard ID so that multiple replicas of Grafana serve dashboards with uniform paths
* Fix issue where refreshing a dashboard served by one replica could show a 404 unless the request went to the same replica
=> Use stable IDs for etcd, CoreDNS, and Ngnix dashboards

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl
* No functional changes, just changes to vendoring tools (go modules -> glide). Still, update to v3.3.15 anyway
* https://github.com/etcd-io/etcd/compare/v3.3.14...v3.3.15
=> Update etcd from v3.3.14 to v3.3.15

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-coreos/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-coreos/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
k8s.gcr.io now hosts CoreDNS v1.6.2
* https://coredns.io/2019/06/26/coredns-1.5.1-release/
* https://coredns.io/2019/07/03/coredns-1.5.2-release/
* https://coredns.io/2019/07/28/coredns-1.6.0-release/
* https://coredns.io/2019/08/02/coredns-1.6.1-release/
* https://coredns.io/2019/08/13/coredns-1.6.2-release/
=> Update CoreDNS from v1.5.0 to v1.6.2

CHANGES.md, azure/container-linux/kubernetes/variables.tf
* Change default `controller_type` to `Standard_B2s`. The `B2s` is cheaper by $17/month and provides 2 vCPU, 4GB RAM (vs 1 vCPU, 3.5GB RAM)
* Change default `worker_type` to `Standard_DS1_v2`. `F1` was the previous generation. The `DS1_v2` is newer, similar cost, more memory, and still supports Low Priority mode, if desired
=> Change Azure default controller_type and worker_type

aws/container-linux/kubernetes/bootkube.tf, aws/fedora-coreos/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-coreos/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
* Rename the organization in generated CA certificates from bootkube to typhoon. Avoid confusion with the bootkube project
* https://github.com/poseidon/terraform-render-bootstrap/pull/149
=> Rename CA org from bootkube to typhoon

aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/ssh.tf, aws/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/ssh.tf, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, azure/container-linux/kubernetes/ssh.tf, azure/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/ssh.tf, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/ssh.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/ssh.tf, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/ssh.tf, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
* Fix issue (present since bootkube->bootstrap switch) where controller asset copy could fail if /etc/kubernetes/manifests wasn't created in time on platforms using path activation for the Kubelet (observed on DigitalOcean, also possible on bare-metal)
* Sort Kubelet ExecStartPre mkdir commands
* Remove unused inactive-manifests and checkpoint-secrets directories (were used by bootkube self-hosting)
=> Fix /etc/kubernetes/manifests mkdir and organize Kubelet ExecStartPre's

CHANGES.md, README.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/bare-metal.md, docs/index.md
* Clarify the removal of the legacy node roles and the addition of renamed node labels for the convenience of anyone relying on node label selectors (rather than using the default master taints to keep workloads off master nodes)
=> Update CHANGES and docs for v1.16.0 release

CHANGES.md, bare-metal/container-linux/kubernetes/ssh.tf, bare-metal/fedora-coreos/kubernetes/ssh.tf, digital-ocean/container-linux/kubernetes/ssh.tf
* Introduced in bare-metal and DigitalOcean in #544 while addressing possible ordering race, but after the v1.16 upgrade validation
Closes #548
=> Fix missing comma separator on bare-metal and DO

aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers.tf, aws/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers.tf, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, aws/fedora-coreos/kubernetes/workers/variables.tf, aws/fedora-coreos/kubernetes/workers/workers.tf, azure/container-linux/kubernetes/variables.tf, azure/container-linux/kubernetes/workers.tf, azure/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, azure/container-linux/kubernetes/workers/variables.tf, azure/container-linux/kubernetes/workers/workers.tf, google-cloud/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/workers.tf, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/variables.tf, google-cloud/container-linux/kubernetes/workers/workers.tf
* Add `node_labels` variable to kubernetes module (currently only for aws/container-linux)
Launched a new cluster with extra labels that were successfully applied on the worker nodes.
----
This is a quick fix I needed for dedicated worker pools and nodeSelector. I guess that for this to be merged it'd require uniformity across all cloud/distro variants.
I'm submitting it just to see if this would be an acceptable feature. If so, I can add it to the rest of the platforms/distros.
Thanks!
=> Add node_labels variable to aws/container-linux/kubernetes/

CHANGES.md, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers/variables.tf, azure/container-linux/kubernetes/variables.tf, azure/container-linux/kubernetes/workers/variables.tf, docs/advanced/worker-pools.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/google-cloud.md, docs/fedora-coreos/aws.md, google-cloud/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/workers/variables.tf
* Document worker pools `node_labels` variable to set the initial node labels for a homogeneous set of workers
* Document `worker_node_labels` convenience variable to set the initial node labels for default worker nodes
=> Update docs and variable types for worker node_labels

CHANGES.md, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers/variables.tf, aws/fedora-coreos/kubernetes/workers/workers.tf, docs/advanced/worker-pools.md, docs/cl/aws.md, docs/fedora-coreos/aws.md
* Review variables available in AWS kubernetes and workers modules and documentation
* Switching between spot and on-demand has worked since Terraform v0.12
* Generally, there are too many knobs. Less useful ones should be de-emphasized or removed
* Remove `cluster_domain_suffix` documentation
=> Add stricter types for AWS modules and update docs

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* Add lifecycle hook to allow draining connections for up to 5 minutes
* https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.26.0
* https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.26.1
=> Update nginx-ingress from v0.25.1 to v0.26.1

CHANGES.md, docs/advanced/worker-pools.md, docs/cl/google-cloud.md, google-cloud/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/workers/variables.tf
* Review variables available in google-cloud kubernetes and workers modules and in documentation
=> Add stricter types for GCP modules

CHANGES.md, azure/container-linux/kubernetes/variables.tf, azure/container-linux/kubernetes/workers/variables.tf, docs/advanced/worker-pools.md, docs/cl/azure.md
* Review variables available in Azure kubernetes and workers
modules and sync with documentation
* Fix internal `workers` module default type to `Standard_DS1_v2`
=> Add stricter types to Azure modules

CHANGES.md, addons/prometheus/config.yaml
* Prometheus was configured to use kubernetes discovery of etcd targets based on nodes matching the node label `node-role.kubernetes.io/controller=true`
* Kubernetes v1.16 stopped permitting node role labels node-role.kubernetes.io/* so Typhoon renamed these labels (no longer any association with roles) to `node.kubermetes.io/controller=true`
* As a result, Prometheus didn't discover etcd targets, etcd metrics were missing, etcd alerts were ineffective, and the etcd Grafana dashboard was empty
* Introduced: https://github.com/poseidon/typhoon/pull/543
=> Fix Prometheus etcd target discovery

CHANGES.md, bare-metal/container-linux/kubernetes/cl/install.yaml.tmpl, bare-metal/container-linux/kubernetes/groups.tf, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/profiles.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, docs/cl/bare-metal.md, docs/fedora-coreos/bare-metal.md
* Review variables available in bare-metal kubernetes modules for Container Linux and Fedora CoreOS
* Deprecate `cluster_domain_suffix` variable
* Remove deprecated `container_linux_oem` variable
=> Add stricter types for bare-metal modules

CHANGES.md, bare-metal/fedora-coreos/kubernetes/profiles.tf, docs/fedora-coreos/bare-metal.md
* Fedora CoreOS changed the kernel, initramfs, and raw
image asset download paths and names in 30.20191002.0
=> Use new Fedora CoreOS kernel/initrd/raw asset names

CHANGES.md, aws/fedora-coreos/kubernetes/ami.tf, aws/fedora-coreos/kubernetes/workers/ami.tf, docs/fedora-coreos/aws.md
* Detect the most recent Fedora CoreOS AMI to allow usage
of Fedora CoreOS in supported regions (previously just
us-east-1)
* Unpin the Fedora CoreOS AMI image which was pinned to
images that had been checked. This does mean if Fedora
publishes a broken image, it will be selected
* Filter out "dev" images which have similar naming
=> Detect most recent Fedora CoreOS AMI in region

CHANGES.md, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/groups.tf, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/ssh.tf, bare-metal/container-linux/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/groups.tf, bare-metal/fedora-coreos/kubernetes/profiles.tf, bare-metal/fedora-coreos/kubernetes/ssh.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, docs/cl/bare-metal.md, docs/fedora-coreos/bare-metal.md
* Define bare-metal `controllers` and `workers` as a complex type `list(object{name=string, mac=string, domain=string})` to allow clusters with many machines to be defined more cleanly
* Remove `controller_names` list variable
* Remove `controller_macs` list variable
* Remove `controller_domains` list variable
* Remove `worker_names` list variable
* Remove `worker_macs` list variable
* Remove `worker_domains` list variable
Using the tutorial docs example, a cluster previously defined as:
```
module "bare-metal-mercury" {
source = "git::https://github.com/poseidon/typhoon//bare-metal/container-linux/kubernetes?ref=v1.16.1"
...
controller_names   = ["node1"]
controller_macs    = ["52:54:00:a1:9c:ae"]
controller_domains = ["node1.example.com"]
worker_names = [
"node2",
"node3",
]
worker_macs …
```
=> Introduce controllers and workers list of detail objects for bare-metal

aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* Remove unneeded control plane flags that correspond to defaults
* Adopt Terraform v0.12 type constraints in bootstrap module
=> Update bootstrap module control plane manifests and type constraints

CHANGES.md, azure/container-linux/kubernetes/variables.tf, digital-ocean/container-linux/kubernetes/variables.tf, docs/cl/azure.md, docs/cl/digital-ocean.md, docs/topics/security.md
* Change `networking` default from flannel to calico on Azure and DigitalOcean
* AWS, bare-metal, and Google Cloud continue to default to Calico (as they have since v1.7.5)
* Typhoon now defaults to using Calico and supporting NetworkPolicy on all platforms
=> Default to Calico as the CNI provider on Azure/DigitalOcean

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* Kubernetes v1.11 considered kube-proxy IPVS mode GA
* Many problems were found #321
* Since then, major blockers seem to have been addressed
=> Switch kube-proxy from iptables mode to ipvs mode

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, docs/topics/hardware.md, google-cloud/container-linux/kubernetes/bootstrap.tf
* Allow advertising Kubernetes service ClusterIPs to BGPPeer routers via a BGPConfiguration
* https://docs.projectcalico.org/v3.10/release-notes/
* https://docs.projectcalico.org/v3.10/networking/advertise-service-ips
=> Upgrade Calico v3.9.2 to v3.10.0

azure/container-linux/kubernetes/outputs.tf
Add an output variable to the azure module named `resource_group_id`.
Actively using this patch with a pre-production cluster that uses
azure-csi-driver configured with a service principal and role assignment e.g.:
resource "azurerm_role_assignment" "some_role" {
name                 = "some-name"
scope                = "${module.typhoon_cluster.resource_group_id}"
role_definition_name = "Contributor"
principal_id         = "${azuread_service_principal.some_sp.object_id}"
}
=> expose resource group id in Azure

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl
* etcd v3.4.3 builds with Go v1.12.12 instead of v1.12.9 and adds a few minor metrics fixes
* https://github.com/etcd-io/etcd/compare/v3.4.2...v3.4.3
=> Update etcd from v3.4.2 to v3.4.3

CHANGES.md, addons/prometheus/deployment.yaml
* Happy PromCon 2019!
* https://github.com/prometheus/prometheus/releases/tag/v2.14.0-rc.0
=> Update Prometheus from v2.13.1 to v2.14.0-rc.0

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* Add health `lameduck` option 5s. Before CoreDNS shuts down, it will wait and report unhealthy for 5s to allow time for plugins to shutdown cleanly
* Minor bug fixes over a few releases
* https://coredns.io/2019/08/31/coredns-1.6.3-release/
* https://coredns.io/2019/09/27/coredns-1.6.4-release/
* https://coredns.io/2019/11/05/coredns-1.6.5-release/
=> Update CoreDNS from v1.6.2 to v1.6.5

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* Set small CPU requests on static pods kube-apiserver, kube-controller-manager, and kube-scheduler to align with upstream tooling and for edge cases
* Effectively, a practical case for these requests hasn't been observed. However, a small static pod CPU request may offer a slight benefit if a controller became overloaded and the below mechanisms were insufficient
Existing safeguards:
* Control plane nodes are tainted to isolate them from ordinary workloads. Even dense workloads can only compress CPU resources on worker nodes.
* Control plane static pods use the highest priority class, so contention favors control plane pods (over say node-exporter) and CPU is compressible too.
See: https://github.com/poseidon/terraform-render-bootstrap/pull/161
=> Add small CPU resource requests to static pods

CHANGES.md, google-cloud/container-linux/kubernetes/versions.tf, google-cloud/container-linux/kubernetes/workers/workers.tf
* terraform-provider-google v2.19.0 deprecates `instance_template` within `google_compute_region_instance_group_manager` in order to support a scheme with multiple version blocks. Adapt our single version to the new format to resolve deprecation warnings.
* Fixes: Warning: "instance_template": [DEPRECATED] This field will be replaced by `version.instance_template` in 3.0.0
* Require terraform-provider-google v2.19.0+ (action required)
=> Use GCP region_instance_group_manager version block format

CHANGES.md, addons/grafana/dashboards-node-exporter.yaml, addons/grafana/deployment.yaml, addons/prometheus/rules.yaml
* Add Nodes Grafana dashboard for node-exporter
* Add node-exporter alerts to Prometheus. Exclude node-exporter recording rules since they are not required for the Nodes dashboard
=> Add node-exporter monitoring alerts and dashboard

aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* Fix deletion of bootstrap module pinned SHA, which was introduced recently through an automation mistake creating https://github.com/poseidon/typhoon/pull/589. This didn't make its way into a release.
=> Fix recent deletion of bootstrap module pinned SHA

digital-ocean/container-linux/kubernetes/outputs.tf
* Fix list output variables for DigitalOcean
I've tested by creating a cluster with Terraform 0.12.16. Referencing variables such as `workers_ipv4` would fail since it was a 1-element tuple containing a list. After my fix it works AFAICT, at least it parses without problems.
=> DigitalOcean: Fix outputs

CHANGES.md, addons/prometheus/config.yaml
* Stop mapping node labels to targets discovered via Kubernetes nodes (e.g. etcd, kubelet, cadvisor). It is rarely useful to store node labels (e.g. kubernetes.io/os=linux) on these metrics
* kube-apiserver's apiserver_request_duration_seconds_bucket metric has a high cardinality that includes labels for the API group, verb, scope, resource, and component for each object type, including for each CRD. This one metric has ~10k time series in a typical cluster (btw 10-40% of total)
* Removing the apiserver request duration outright would make latency alerts a NoOp and break a Grafana apiserver panel. Instead, drop series that have a "group" label. Effectively, only request durations for core Kubernetes APIs will be kept (e.g. cardinality won't grow with each CRD added). This reduces the …
=> Reduce apiserver metrics cardinality and extraneous labels

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* Reduce time to delete pods on unready nodes from 5m to 1m
* Present since v1.13.3, but mistakenly removed in v1.16.0 static pod control plane migration
Related:
* https://github.com/poseidon/terraform-render-bootstrap/pull/148
* https://github.com/poseidon/terraform-render-bootstrap/pull/164
=> Reduce kube-controller-manager pod eviction timeout from 5m to 1m

digital-ocean/container-linux/kubernetes/outputs.tf
* Allow the raw kubelet kubeconfig to be consumed via Terraform output
=> Add Kubelet kubeconfig output for DigitalOcean

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* https://coredns.io/2019/12/11/coredns-1.6.6-release/
Related: https://github.com/poseidon/terraform-render-bootstrap/pull/167
=> Update CoreDNS from v1.6.5 to v1.6.6

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/container-linux/kubernetes/workers/cl/worker.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/container-linux/kubernetes/workers/cl/worker.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/worker.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/container-linux/kubernetes/cl/worker.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml
* Change kubelet.service on Container Linux nodes to ExecStart Kubelet inline to replace the use of the host OS kubelet-wrapper script
* Express rkt run flags and volume mounts in a clear, uniform way to make the Kubelet service easier to audit, manage, and understand
* Eliminate reliance on a Container Linux kubelet-wrapper script
* Typhoon for Fedora CoreOS developed a kubelet.service that similarly uses an inline ExecStart (except with podman instead of rkt) and a more minimal set of volume mounts. Adopt the volume improvements:
* Change Kubelet `/etc/kubernetes` volume to read-only
* Change Kubelet `/etc/resolv.conf` volume to read-only
* Remove unneeded `/var/lib/cni` volume mount
Background:
* kubelet-wrapper was added in CoreOS around the time of Kubernetes v1.0 to simplify running …
=> Inline Container Linux kubelet.service, deprecate kubelet-wrapper

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/container-linux/kubernetes/workers/cl/worker.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/container-linux/kubernetes/workers/cl/worker.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/container-linux/kubernetes/cl/worker.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml
* Kubelet runs a healthz server listening on 127.0.0.1:10248 by default. Its unused by Typhoon and can be disabled
* https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
=> Disable Kubelet 127.0.0.1.10248 healthz endpoint

CHANGES.md, addons/prometheus/discovery/kube-controller-manager.yaml, addons/prometheus/discovery/kube-proxy.yaml, aws/container-linux/kubernetes/bootstrap.tf, aws/container-linux/kubernetes/security.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/security.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/security.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/network.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/network.tf
* Configure kube-proxy `--metrics-bind-address=0.0.0.0` (default `127.0.0.1`) to serve metrics
* Add firewall rules to allow Prometheus (resides on a worker) to scrape kube-proxy service endpoints on controllers or workers
* Add a `clusterIP: None` Service for kube-proxy endpoint discovery
Related: https://github.com/poseidon/terraform-render-bootstrap/pull/168
=> Enable kube-proxy metrics and allow Prometheus scrapes

CHANGES.md, addons/prometheus/exporters/node-exporter/daemonset.yaml
* Change `node-exporter` DaemonSet tolerations from tolerating all possible NoSchedule taints to tolerating the master taint and the not-ready taint
* Users who add custom node taints must add their custom taints to the addon node-exporter DaemonSet. As an addon, its expected users copy and manipulate manifests out-of-band in their own systems
=> Reduce Prometheus addon's node-exporter tolerations

bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/worker.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/container-linux/kubernetes/cl/worker.yaml
* [Inlining the Kubelet service](https://github.com/poseidon/typhoon/pull/606) removed the need for the `kubelet.env` file declared in Ignition. However, on some platforms, this removed the guarantee that `/etc/kubernetes` exists at boot. Bare-Metal and DigitalOcean distribute the Kubelet kubeconfig through Terraform file provisioner (scp) and place it in (now missing) `/etc/kubernetes` (failing)
* Fix bare-metal and DigitalOcean Ignition to ensure the `/etc/kubernetes` directory exists following first boot from disk
* Cloud platforms with worker pools distribute the kubeconfig through Ignition user data (no impact or need)
Closes #612
=> Ensure /etc/kubernetes exists following Kubelet inlining

CHANGES.md, docs/cl/google-cloud.md, google-cloud/container-linux/kubernetes/versions.tf
* Typhoon Google Cloud is compatible with `terraform-provider-google` v3.x releases
* No v3.x specific features are used, so v2.19+ versions are still allowed
=> Allow terraform-provider-google v3.x plugin versions

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.9.1
=> Update kube-state-metrics from v1.9.0 to v1.9.1

aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml
* /var/run symlinks to /run (already mounted)
=> Remove unneeded Kubelet /var/run mount on Fedora CoreOS

aws/fedora-coreos/kubernetes/ami.tf, aws/fedora-coreos/kubernetes/workers/ami.tf
* Select the most recent fedora-coreos-31 AMI on AWS, instead of the most recent fedora-coreos-30 AMI (Nov 27, 2019)
* Evaluated with fedora-coreos-31.20200108.2.0-hvm
=> Update AWS AMI filter for fedora-coreos-31

CHANGES.md, bare-metal/fedora-coreos/kubernetes/profiles.tf, docs/fedora-coreos/bare-metal.md
* Use Fedora CoreOS production download streams (change)
* Use live PXE kernel and initramfs images
* https://getfedora.org/coreos/download/
* Update docs example to use public images (cache is still recommended at large scale) and stable stream
=> Update bare-metal Fedora CoreOS image location

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* Change runAsUser from 33 to 101 for new alpine-based image
* https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.27.0
* https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.27.1
=> Update nginx-ingress from v0.26.1 to v0.27.1

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.9.3
=> Update kube-state-metrics from v1.9.2 to v1.9.3

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* https://docs.projectcalico.org/release-notes/#v3120
* Remove reverse packet filter override, since Calico no longer relies on the setting
* https://github.com/coreos/fedora-coreos-tracker/issues/219
* https://github.com/projectcalico/felix/pull/2189
=> Update Calico from v3.11.2 to v3.12.0

CHANGES.md, README.md, docs/cl/google-cloud.md, docs/fedora-coreos/google-cloud.md, docs/index.md
* Add docs on manually uploading a Flatcar Linux GCE/GCP gzipped tarball image as a Compute Engine image for use with the Typhoon container-linux module
* Set status of Flatcar Linux on Google Cloud to alpha
=> Add guide for Typhoon with Flatcar Linux on Google Cloud

CHANGES.md, bare-metal/fedora-coreos/kubernetes/profiles.tf
* Align bare-metal kernel arguments with upstream docs
* Add missing initrd argument which can cause issues if not present. Fix #638
* Add tty0 and ttyS0 consoles (matches Container Linux)
* Remove unused coreos.inst=yes
=> Update Fedora CoreOS kernel arguments to align with upstream

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Fix the last minor issue for Fedora CoreOS clusters to pass CNCF's Kubernetes conformance tests
* Kubelet supports a seldom used feature `kubectl logs --limit-bytes=N` to trim a log stream to a desired length. Kubelet handles this in the CRI driver. The Kubelet docker shim only supports the limit bytes feature when Docker is configured with the default `json-file` logging driver
* CNCF conformance tests started requiring limit-bytes be supported, indirectly forcing the log driver choice until either the Kubelet or the conformance tests are fixed
* Fedora CoreOS defaults Docker to use `journald` (desired). For now, as a workaround to offer conformant clusters, the log driver can be set back to `json-file`. RHEL CoreOS likely won't have noticed the non-conformance since its using crio …
=> Set docker log driver to json-file on Fedora CoreOS

CHANGES.md, README.md, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/container-linux/kubernetes/workers.tf, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/index.md
* Add docs on manually uploading a Flatcar Linux DigitalOcean bin image as a custom image and using a data reference
* Set status of Flatcar Linux on DigitalOcean to alpha
* IPv6 is not supported for DigitalOcean custom images
=> Add guide for Typhoon with Flatcar Linux on DigitalOcean

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.16.0
=> Update Prometheus from v1.15.2 to v1.16.0

aws/container-linux/kubernetes/cl/controller.yaml, aws/container-linux/kubernetes/workers/cl/worker.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/container-linux/kubernetes/workers/cl/worker.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/container-linux/kubernetes/cl/worker.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
In container linux change the kubelet's `/var/lib/calico` mount to
`readOnly`. Kubelet only needs to read this and not make any amendments
to the file.
=> container linux kubelet: Make calico mount readonly

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://coredns.io/2020/01/28/coredns-1.6.7-release/
=> Update CoreDNS from v1.6.6 to v1.6.7

CHANGES.md, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Add Terraform strip markers to consume beginning and trailing whitespace in templated Kubelet arguments for podman (Fedora CoreOS only)
* Fix initial `worker_node_labels` being quietly ignored on Fedora CoreOS cloud platforms that offer the feature
* Close https://github.com/poseidon/typhoon/issues/650
=> Fix worker_node_labels for initial Fedora CoreOS

CHANGES.md, addons/prometheus/exporters/node-exporter/daemonset.yaml, addons/prometheus/rules.yaml
* Update mdadm alert rule; node-exporter adds `state` label to `node_md_disks` and removes `node_md_disks_active`
* https://github.com/prometheus/node_exporter/releases/tag/v1.0.0-rc.0
=> Update node-exporter from v0.18.1 to v1.0.0-rc.0

CHANGES.md, aws/container-linux/kubernetes/network.tf, aws/fedora-coreos/kubernetes/network.tf, docs/architecture/aws.md
* Allow users to extend the route table using a data reference and adding route resources (e.g. unusual peering setups)
* Note: Internally connecting AWS clusters can reduce cross-cloud flexibility and inhibits blue-green cluster patterns. It is not recommended
=> Use a route table with separate (rather than inline) routes

CHANGES.md, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* On clouds where workers can scale down or be preempted (AWS, GCP, Azure), shutdown runs delete-node.service to remove a node a prevent NotReady nodes from lingering
* Add the delete-node.service that wasn't carried over from Container Linux and port it to use podman
=> Add automatic worker deletion on Fedora CoreOS clouds

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml
* Quay has historically generated ACI signatures for images to facilitate rkt's notions of verification (it allowed authors to actually sign images, though `--trust-keys-from-https` is in use since etcd and most authors don't sign images). OCI standardization didn't adopt verification ideas and checking signatures has fallen out of favor.
* Fix #658 where Quay no longer seems to be generating ACI signatures for new images (e.g. quay.io/coreos/etcd:v.3.4.4)
* Don't be alarmed by rkt `--insecure-options=image`. It refers to disabling image signature checking (i.e. docker pull doesn't check signatures either)
* System containers for Kubelet and bootstrap have transitioned to the docker:// transport, so there is precedent and this brings all the system containers on Container Linux …
=> Change Container Linux etcd-member to fetch with docker://

CHANGES.md, addons/grafana/dashboards-k8s-nodes.yaml, addons/grafana/dashboards-k8s-resources-1.yaml, addons/grafana/dashboards-k8s-resources-2.yaml, addons/grafana/dashboards-k8s.yaml, addons/grafana/dashboards-prom.yaml, addons/prometheus/rules.yaml
* Refresh Prometheus rules and alerts and Grafana dashboards
* Add 2 min wait before KubeNodeUnreachable to be less noisy on premeptible clusters
* Add a BlackboxProbeFailure alert for any failing probes for services annotated `prometheus.io/probe: true`
=> Refresh Prometheus alerts and Grafana dashboards

CHANGES.md, azure/container-linux/kubernetes/controllers.tf, azure/container-linux/kubernetes/network.tf, azure/container-linux/kubernetes/ssh.tf, azure/container-linux/kubernetes/versions.tf, azure/container-linux/kubernetes/workers.tf, azure/container-linux/kubernetes/workers/workers.tf, docs/cl/azure.md
* Add support for `terraform-provider-azurerm` v2.0+. Require `terraform-provider-azurerm` v2.0+ and drop v1.x support since the Azure provider major release is not backwards compatible
* Use Azure's new Linux VM and Linux VM Scale Set resources
* Change controller's Azure disk caching to None
* Associate subnets (in addition to NICs) with security groups (aesthetic)
End-user:
* If set, change `worker_priority` from `Low` to `Spot` (action required)
Related:
* https://www.terraform.io/docs/providers/azurerm/guides/2.0-upgrade-guide.html
=> Upgrade terraform-provider-azurerm to v2.0+

CHANGES.md, bare-metal/container-linux/kubernetes/cl/worker.yaml, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/profiles.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, docs/cl/bare-metal.md, docs/fedora-coreos/bare-metal.md
* Add `worker_node_labels` map from node name to a list of initial node label strings
* Add `worker_node_taints` map from node name to a list of initial node taint strings
* Unlike cloud platforms, bare-metal node labels and taints are defined via a map from node name to list of labels/taints. Bare-metal clusters may have heterogeneous hardware so per node labels and taints are accepted
* Only worker node names are allowed. Workloads are not scheduled on controller nodes so altering their labels/taints isn't suitable
```
module "mercury" {
...
worker_node_labels = {
"node2" = ["role=special"]
}
worker_node_taints = {
"node2" = ["role=special:NoSchedule"]
}
}
```
Related: https://github.com/poseidon/typhoon/issues/429
=> Accept initial worker node labels and taints map on bare-metal

CHANGES.md, README.md, azure/container-linux/kubernetes/controllers.tf, azure/container-linux/kubernetes/variables.tf, azure/container-linux/kubernetes/workers/workers.tf, docs/cl/azure.md, docs/index.md
* Accept `os_image` "flatcar-stable" and "flatcar-beta"
* Use of Flatcar Linux on Azure requires accepting their Marketplace terms
=> Add support for Flatcar Linux on Azure

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://docs.projectcalico.org/v3.13/release-notes/
=> Update Calico from v3.12.0 to v3.13.1

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v6.7.0
=> Update Grafana from v6.6.2 to v6.7.0

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/container-linux/kubernetes/cl/controller.yaml, aws/container-linux/kubernetes/workers/cl/worker.yaml, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/container-linux/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/cl/controller.yaml, azure/container-linux/kubernetes/workers/cl/worker.yaml, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/worker.yaml, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/container-linux/kubernetes/cl/worker.yaml, docs/architecture/operating-systems.md, docs/topics/security.md, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Kubernetes plans to stop releasing the hyperkube container image
* Upstream will continue to publish `kube-apiserver`, `kube-controller-manager`, `kube-scheduler`, and `kube-proxy` container images to `k8s.gcr.io`
* Upstream will publish Kubelet only as a binary for distros to package, either as a DEB/RPM on traditional distros or a container image on container-optimized operating systems
* Typhoon will package the upstream Kubelet (checksummed) and its dependencies as a container image for use on CoreOS Container Linux, Flatcar Linux, and Fedora CoreOS
* Update the Typhoon container image security policy to list `quay.io/poseidon/kubelet`as an official distributed artifact
Hyperkube: https://github.com/kubernetes/kubernetes/pull/88676
Kubelet Container Image: …
=> Switch from upstream hyperkube image to individual images

CHANGES.md, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/container-linux/kubernetes/variables.tf, digital-ocean/container-linux/kubernetes/workers.tf, docs/cl/digital-ocean.md
* Rename variable `image` to `os_image` to match the naming used for the same purpose on other supported platforms (e.g. AWS, Azure, GCP)
=> Rename DigitalOcean image variable to os_image

CHANGES.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/google-cloud.md
* Remove docs for the `asset_dir` variable and deprecate it in CHANGES. It will be removed in an upcoming release
* Typhoon v1.17.0 introduced a new mechanism for managing and distributing generated assets that stopped relying on writing out to disk. `asset_dir` became optional and defaulted to being unset / off (recommended)
=> Deprecate asset_dir variable and remove docs

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Before Kubernetes v1.18.0, Kubelet only supported kubectl `--limit-bytes` with the Docker `json-file` log driver so the Fedora CoreOS default was overridden for conformance. See https://github.com/poseidon/typhoon/pull/642
* Kubelet v1.18+ implemented support for other docker log drivers, so the Fedora CoreOS default `journald` can be used again
Rel: https://github.com/kubernetes/kubernetes/issues/86367
=> Set docker log driver to journald on Fedora CoreOS

CHANGES.md
* Recommend that users who have not yet tried Fedora CoreOS or Flatcar Linux do so. Likely, Container Linux will reach EOL and platform support / stability ratings will be in a mixed state. Nevertheless, folks should migrate by September.
=> Recommend choosing Fedora CoreOS or Flatcar Linux

aws/container-linux/kubernetes/workers/cl/worker.yaml, azure/container-linux/kubernetes/workers/cl/worker.yaml, digital-ocean/container-linux/kubernetes/cl/worker.yaml, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Fix delete-node service that runs on worker (cloud-only) shutdown to delete a Kubernetes node. Regressed in #669 (unreleased)
* Use podman `--entrypoint` to invoke the kubectl binary in the kubelet image on Fedora CoreOS
* Use rkt `--exec` to invoke kubectl binary in the kubelet image on Container Linux
=> Fix delete-node.service kubectl service exec's

CHANGES.md, aws/fedora-coreos/kubernetes/ami.tf, aws/fedora-coreos/kubernetes/workers/ami.tf
* Fix issue observed in us-east-1 where AMI filters chose the latest testing channel release, rather than the stable chanel
* Fedora CoreOS AMI filter selects the latest image with a matching name, x86_64, and hvm, excluding dev images. Add a filter for "Fedora CoreOS stable", which seems to be the only
distinguishing metadata indicating the channel
=> Fix Fedora CoreOS AMI to filter for stable images

CHANGES.md, bare-metal/fedora-coreos/kubernetes/profiles.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, docs/advanced/customization.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/google-cloud.md
* Refresh snippets customization docs
* Requires terraform-provider-ct v0.5+
=> Add support for Fedora CoreOS snippets

CHANGES.md, docs/fedora-coreos/google-cloud.md, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* Problem: Fedora CoreOS images are manually uploaded to GCP. When a cluster is created with a stale image, Zincati immediately checks for the latest stable image, fetches, and reboots. In practice,
this can unfortunately occur exactly during the initial cluster bootstrap phase.
* Recommended: Upload the latest Fedora CoreOS image regularly
* Mitigation: Allow a failed bootstrap.service run (which won't touch the done ConditionalPathExists) to be re-run by running `terraforma apply` again. Add a known issue to CHANGES
* Update docs to show the current Fedora CoreOS stable version to reduce likelihood users see this issue
Longer term ideas:
* Ideal: Fedora CoreOS publishes a stable channel. Instances will always boot with the latest image in a channel. The problem disappears since it works …
=> Allow bootstrap re-apply for Fedora CoreOS GCP

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* Change kube-proxy, flannel, and calico-node DaemonSet tolerations to tolerate `node.kubernetes.io/not-ready` and `node-role.kubernetes.io/master` (i.e. controllers) explicitly, rather than tolerating all taints
* kube-system DaemonSets will no longer tolerate custom node taints by default. Instead, custom node taints must be enumerated to opt-in to scheduling/executing the kube-system DaemonSets
* Consider setting the daemonset_tolerations variable of terraform-render-bootstrap at a later date
Background: Tolerating all taints ruled out use-cases where certain nodes might legitimately need to keep kube-proxy or CNI networking disabled
Related: https://github.com/poseidon/terraform-render-bootstrap/pull/179
=> Change default kube-system DaemonSet tolerations

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* Fix bootstrap error for missing `manifests-networking/crd*yaml` when `networking = "flannel"`
* Cleanup manifest-networking directory left during bootstrap
* Regressed in v1.18.0 changes for Calico https://github.com/poseidon/typhoon/pull/675
=> Fix bootstrap regression when networking="flannel"

CHANGES.md, aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, azure/container-linux/kubernetes/controllers.tf, azure/container-linux/kubernetes/variables.tf, azure/container-linux/kubernetes/workers.tf, azure/container-linux/kubernetes/workers/variables.tf, azure/container-linux/kubernetes/workers/workers.tf, bare-metal/container-linux/kubernetes/profiles.tf, bare-metal/container-linux/kubernetes/variables.tf, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/container-linux/kubernetes/variables.tf, digital-ocean/container-linux/kubernetes/workers.tf, docs/advanced/customization.md, docs/advanced/worker-pools.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, google-cloud/container-linux/kubernetes/controllers.tf, google-cloud/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/workers.tf, google-cloud/container-linux/kubernetes/workers/variables.tf, google-cloud/container-linux/kubernetes/workers/workers.tf
* Rename controller_clc_snippets to controller_snippets (cloud platforms)
* Rename worker_clc_snippets to worker_snippets (cloud platforms)
* Rename clc_snippets to snippets (bare-metal)
=> Rename Container Linux snippets variable for consistency

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://github.com/coreos/flannel/releases/tag/v0.12.0
=> Update flannel from v0.11.0 to v0.12.0

CHANGES.md, azure/container-linux/kubernetes/lb.tf
* Add "lb" outbound rule for worker TCP _and_ UDP traffic
* Fix Azure worker nodes clock synchronization being inactive
due to timeouts reaching the CoreOS / Flatcar NTP pool
* Fix Azure worker nodes not providing outbount UDP connectivity
Background:
Azure provides VMs outbound connectivity either by having a public
IP or via an SNAT masquerade feature bundled with their virtual
load balancing abstraction (in contrast with, say, a NAT gateway).
Azure worker nodes have only a private IP, but are associated with
the cluster load balancer's backend pool and ingress frontend IP.
Outbound traffic uses SNAT with this frontend IP. A subtle detail
with Azure SNAT seems to be that since both inbound lb_rule's are
TCP only, outbound UDP traffic isn't SNAT'd (highlights the reasons
Azure shouldn't …
=> Fix Azure worker UDP outbound SNAT and clock sync timeouts

CHANGES.md, README.md, digital-ocean/fedora-coreos/kubernetes/LICENSE, digital-ocean/fedora-coreos/kubernetes/README.md, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/controllers.tf, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/network.tf, digital-ocean/fedora-coreos/kubernetes/outputs.tf, digital-ocean/fedora-coreos/kubernetes/ssh.tf, digital-ocean/fedora-coreos/kubernetes/variables.tf, digital-ocean/fedora-coreos/kubernetes/versions.tf, digital-ocean/fedora-coreos/kubernetes/workers.tf, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, docs/index.md
* Add `digital-ocean/fedora-coreos/kubernetes` module
* DigitalOcean custom uploaded images do not permit droplet IPv6 networking
=> Add support for Fedora CoreOS on DigitalOcean

CHANGES.md, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers/variables.tf, azure/container-linux/kubernetes/variables.tf, azure/container-linux/kubernetes/workers/variables.tf, bare-metal/container-linux/kubernetes/variables.tf, digital-ocean/container-linux/kubernetes/variables.tf, docs/advanced/worker-pools.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, google-cloud/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/workers/variables.tf
* No change to Fedora CoreOS modules
* For Container Linx AWS and Azure, change the `os_image` default from coreos-stable to flatcar-stable
* For Container Linux GCP and DigitalOcean, change `os_image` to be required since users should upload a Flatcar Linux image and set the variable
* For Container Linux bare-metal, recommend users change the `os_channel` to Flatcar Linux. No actual module change.
=> Change container-linux module preference to Flatcar Linux

aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* In v1.18.0, kubectl apply would fail to apply manifests if any single manifest was unable to validate. For example, if a CRD and CR were defined in the same directory, apply would fail since the CR would be invalid as the CRD wouldn't exist
* Typhoon temporary workaround was to separate CNI CRD manifests and explicitly apply them first. No longer needed in v1.18.1+
* Kubernetes v1.18.1 restored the prior behavior where kubectl apply applies as many valid manifests as it can. In the example above, the CRD would be applied and the CR could be applied if the kubectl apply was re-run (allowing for apply loops).
* Upstream fix: https://github.com/kubernetes/kubernetes/pull/89864
=> Remove temporary workaround for v1.18.0 apply issue

CHANGES.md, azure/container-linux/kubernetes/controllers.tf, azure/container-linux/kubernetes/variables.tf, azure/container-linux/kubernetes/workers/workers.tf, docs/cl/azure.md, docs/fedora-coreos/azure.md
* Initial support for Flatcar Linux on Azure used the Flatcar Linux Azure Marketplace images (e.g. `flatcar-stable`) in https://github.com/poseidon/typhoon/pull/664
* Flatcar Linux Azure Marketplace images have some unresolved items https://github.com/poseidon/typhoon/issues/703
* Until the Marketplace items are resolved, revert to requiring Flatcar Linux's images be manually uploaded (like GCP and DigitalOcean)
=> Revert Flatcar Linux Azure to manual upload images

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* Race: During initial bootstrap, static control plane pods could hang with Permission denied to bootstrap secrets. A manual fix involved restarting Kubelet, which relabeled mounts. The race had no effect on subsequent reboots.
* bootstrap.service runs podman with a private unshared mount of `/etc/kubernetes/bootstrap-secrets` which uses an SELinux MCS label with a category pair. However, bootstrap-secrets should
be shared as its mounted by Docker pods `kube-apiserver`, `kube-scheduler`, and `kube-controller-manager`. Restarting Kubelet was a manual fix because Kubelet relabels all `/etc/kubernetes`
* Fix bootstrap Pod to use the shared volume label, which leaves bootstrap-secrets files with SELinux level s0 without MCS
=> Fix bootstrap mount to use shared volume SELinux label

CHANGES.md, digital-ocean/container-linux/kubernetes/network.tf, digital-ocean/fedora-coreos/kubernetes/network.tf
* DigitalOcean firewall rules should reference Terraform tag resources rather than using tag strings. Otherwise, terraform apply can fail (neeeds rerun) if a tag has not yet been created
=> Fix race condition creating DigitalOcean firewall rules

aws/container-linux/kubernetes/controllers.tf, aws/fedora-coreos/kubernetes/controllers.tf
This PR re-introduces `element` in the AWS modules to look up subnet IDs for controllers. In these situations, `element`'s wrap around behavior is required. Otherwise, if `length(var.controller_count) > length(aws_subnet.public.*.id)`, Terraform fails.
With `controller_count = 5` in `us-west-2`, for example:
```
Error: Invalid index
on .terraform/modules/green.typhoon/aws/container-linux/kubernetes/controllers.tf line 52, in resource "aws_instance" "controllers":
52:   subnet_id = aws_subnet.public.*.id[count.index]
|----------------
| aws_subnet.public is tuple with 4 elements
| count.index is 4
The given key does not identify an element in this collection value.
```
I merged this change into our fork and can successfully plan. 
This regression was introduced in …
=> aws: use element() to look up controller subnet_id with wrap around

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.0.0-beta1
=> Update Grafana from v6.7.2 to v7.0.0-beta1

CHANGES.md, addons/nginx-ingress/aws/class.yaml, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/aws/rbac/cluster-role.yaml, addons/nginx-ingress/azure/class.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/azure/rbac/cluster-role.yaml, addons/nginx-ingress/bare-metal/class.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/bare-metal/rbac/cluster-role.yaml, addons/nginx-ingress/digital-ocean/class.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/digital-ocean/rbac/cluster-role.yaml, addons/nginx-ingress/google-cloud/class.yaml, addons/nginx-ingress/google-cloud/deployment.yaml, addons/nginx-ingress/google-cloud/rbac/cluster-role.yaml
* Add support for IngressClass and RBAC authorization
* Since our nginx ingress controller example uses the flag `--ingress-class=public`, add an IngressClass to go along with it
=> Update nginx-ingress from v0.30.0 to v0.32.0

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.18.0
=> Update Prometheus from v2.18.0-rc.1 to v2.18.0

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.0.0-beta2
=> Update Grafana from v7.0.0-beta1 to v7.0.0-beta2

CHANGES.md, docs/advanced/worker-pools.md, docs/fedora-coreos/google-cloud.md, google-cloud/fedora-coreos/kubernetes/controllers.tf, google-cloud/fedora-coreos/kubernetes/image.tf, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/workers.tf, google-cloud/fedora-coreos/kubernetes/workers/image.tf, google-cloud/fedora-coreos/kubernetes/workers/variables.tf, google-cloud/fedora-coreos/kubernetes/workers/workers.tf
* Add `os_stream` variable to set a Fedora CoreOS stream to `stable` (default), `testing`, or `next`
* Deprecate `os_image` variable. Remove docs about uploading Fedora CoreOS images manually, this is no longer needed
* https://docs.fedoraproject.org/en-US/fedora-coreos/update-streams/
Rel: https://github.com/coreos/fedora-coreos-docs/pull/70
=> Use Fedora CoreOS image streams on Google Cloud

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* Set a consistent MCS level/range for Calico install-cni
* Note: Rebooting a node was a workaround, because Kubelet relabels /etc/kubernetes(/cni/net.d)
Background:
* On SELinux enforcing systems, the Calico CNI install-cni container ran with default SELinux context and a random MCS pair. install-cni places CNI configs by first creating a temporary file and then moving them into place, which means the file MCS categories depend on the containers SELinux context.
* calico-node Pod restarts creates a new install-cni container with a different MCS pair that cannot access the earlier written file (it places configs every time), causing the init container to error and calico-node to crash loop
* https://github.com/projectcalico/cni-plugin/issues/874
```
mv: inter-device move failed: …
```
=> Fix Calico install-cni crashloop on Pod restarts

CHANGES.md, aws/fedora-coreos/kubernetes/ami.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers.tf, aws/fedora-coreos/kubernetes/workers/ami.tf, aws/fedora-coreos/kubernetes/workers/variables.tf
* Add `os_stream` variable to set the stream to stable (default), testing, or next
* Remove unused os_image variable on Fedora CoreOS AWS
=> Support Fedora CoreOS OS image streams on AWS

README.md, aws/container-linux/kubernetes/README.md, aws/fedora-coreos/kubernetes/README.md, azure/fedora-coreos/kubernetes/README.md, bare-metal/fedora-coreos/kubernetes/README.md, digital-ocean/fedora-coreos/kubernetes/README.md, docs/index.md, docs/topics/security.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/fedora-coreos/kubernetes/README.md
* Highlight SELinux enforcing as an available feature (when Fedora CoreOS is used). This is similar to listing NetworkPolicy being available (assuming Calico is chosen)
* In the security docs, mention that SELinux is enforcing on Fedora CoreOS and permissive on Flatcar Linux
* Also list CSI on clouds where there are known good CSI providers
=> Highlight SELinux enforcing mode in feature

CHANGES.md, azure/container-linux/kubernetes/controllers.tf, azure/container-linux/kubernetes/variables.tf, azure/container-linux/kubernetes/workers/variables.tf, azure/container-linux/kubernetes/workers/workers.tf, docs/advanced/worker-pools.md, docs/cl/azure.md
* Switch Flatcar Linux Azure to use the Marketplace image from Kinvolk (offer `flatcar-container-linux-free`)
* Accepting Azure Marketplace terms is still neccessary, update docs to show accepting the free offer rather than BYOL
Upstream Flatcar: https://github.com/flatcar-linux/Flatcar/issues/82
Typhoon: https://github.com/poseidon/typhoon/issues/703
=> Restore use of Flatcar Linux Azure Marketplace image

CHANGES.md, azure/container-linux/kubernetes/controllers.tf, azure/container-linux/kubernetes/network.tf, azure/container-linux/kubernetes/versions.tf, azure/container-linux/kubernetes/workers/workers.tf, azure/fedora-coreos/kubernetes/network.tf, azure/fedora-coreos/kubernetes/versions.tf
* Update Azure subnet `address_prefix` to `azure_prefixes` list
* Fix warning that `address_prefix` is deprecated
* Require `terraform-provider-azurerm` v2.8.0+ (action required)
Rel: https://github.com/terraform-providers/terraform-provider-azurerm/pull/6493
=> Use new Azure subnet to set address_prefixes list

CHANGES.md, addons/grafana/deployment.yaml
* https://grafana.com/docs/grafana/latest/guides/whats-new-in-v7-0/
Note: We found v7.0.0-beta3 to be broken, v7.0.0-beta2 was what was actually used in our environment.
=> Update Grafana from v7.0.0-beta2 to v7.0.0

google-cloud/fedora-coreos/kubernetes/controllers.tf, google-cloud/fedora-coreos/kubernetes/workers/workers.tf
* With Fedora CoreOS image stream support (#727), the latest resolved image will change over the lifecycle of a cluster.
* Fix issue where an image diff proposed replacing a Fedora CoreOS controller on GCP, introduced in #727 (unreleased)
* Also ignore image diffs to the GCP managed instance group of workers. This aligns with worker AMI diffs being ignored on AWS and similar on Azure, since workers update themselves.
Background:
* Controller nodes should strictly not be recreated by Terraform, they are stateful (etcd) and should not be replaced
* Across cloud platforms, OS image diffs are ignored since both Flatcar Linux and Fedora CoreOS nodes update themselves. For workers, user-data or disk size diffs (where relevant) are allowed to recreate workers templates/configs since these are …
=> Fix Fedora CoreOS on GCP proposing controller recreate

aws/container-linux/kubernetes/cl/controller.yaml, aws/container-linux/kubernetes/workers/cl/worker.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/container-linux/kubernetes/workers/cl/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/container-linux/kubernetes/cl/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Write the systemd kubelet.service to use `KUBELET_IMAGE` as the Kubelet. This provides a nice way to use systemd dropins to temporarily override the image (e.g. during a registry outage)
Note: Only Typhoon Kubelet images and registries are supported
=> Set Kubelet image via kubelet.service KUBELET_IMAGE

.github/ISSUE_TEMPLATE/bug_report.md
* Create a stricter bug report template
* Highlight topics that are not accepted in issues: operation, support, debugging, advice, or Kubernetes concepts
* Add a section to strongly suggest bug reports link a PR or describe a solution. This may be able to weed out topics that aren't focused bug reports
=> Update Github issue template to use drop-downs

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/container-linux/kubernetes/workers/cl/worker.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/container-linux/kubernetes/workers/cl/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/container-linux/kubernetes/cl/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, docs/advanced/customization.md, docs/topics/security.md, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Build Kubelet container images internally and publish to Quay and Dockerhub (new) as an alternative in case of registry outage or breach
* Use our infra to build single and multi-arch (default) Kublet images for possible future use
* Docs: Show how to use alternative Kubelet images via snippets and a systemd dropin (builds on #737)
Changes:
* Update docs with changes to Kubelet image building
* If you prefer to trust images built by Quay/Dockerhub, automated image builds are still available with unique tags (albeit with some limitations):
* Quay automated builds are tagged `build-{short_sha}` (limit: only amd64)
* Dockerhub automated builts are tagged `build-{tag}` and `build-master` (limit: only amd64, no shas)
Links:
* Kubelet: https://github.com/poseidon/kubelet
* Docs: …
=> Changes Kubelet container image publishing

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.19.0-rc.0
=> Update Prometheus from v2.18.1 to v2.19.0-rc.0

docs/fedora-coreos/aws.md
* Fedora CoreOS image `os_stream` stable, testing, and next have been configurable since v1.18.3
* Remove mention of outdated `os_image` variable
Related: https://communityblog.fedoraproject.org/contribute-at-the-fedora-coreos-test-day/
=> Fix Fedora CoreOS docs for selecting a stream

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.19.0
=> Update Prometheus from v2.19.0-rc.0 to v2.19.0

CHANGES.md, addons/prometheus/exporters/node-exporter/daemonset.yaml
* https://github.com/prometheus/node_exporter/releases/tag/v1.0.1
=> Update node-exporter from v1.0.0 to v1.0.1

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* Remove node label `node.kubernetes.io/master` from controller nodes
* Use `node.kubernetes.io/controller` (present since v1.9.5, [#160](https://github.com/poseidon/typhoon/pull/160)) to node select controllers
* Rename controller NoSchedule taint from `node-role.kubernetes.io/master` to `node-role.kubernetes.io/controller`
* Tolerate the new taint name for workloads that may run on controller nodes and stop tolerating `node-role.kubernetes.io/master` taint
=> Rename controller node label and NoSchedule taint

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Fedora CoreOS `kubelet.service` can start before the hostname
is set. Kubelet reads the hostname to determine the node name to
register. If the hostname was read as localhost, Kubelet will
continue trying to register as localhost (problem)
* This race manifests as a node that appears NotReady, the Kubelet
is trying to register as localhost, while the host itself (by then)
has an AWS provided hostname. Restarting kubelet.service is a
manual fix so Kubelet re-reads the hostname
* This race could only be shown on AWS, not on Google Cloud or
Azure despite attempts. Bare-metal and DigitalOcean differ and
use hostname-override (e.g. afterburn) so they're not affected
* Wait for nodes to have a non-localhost hostname in the oneshot
that awaits /etc/resolve.conf. Typhoon has no valid cases for …
=> Fix Kubelet starting before hostname set on FCOS AWS

CHANGES.md, azure/fedora-coreos/kubernetes/bootstrap.tf
* Change the Calico VXLAN interface for MTU from 1450 to 1410
* VXLAN on Azure should support MTU 1450. However, there is history where performance measures have shown that 1410 is needed to have expected performance. Flatcar Linux has the same MTU 1410 override and note
* FCOS 31.20200323.3.2 was known to perform fine with 1450, but now in 31.20200517.3.0 the right value seems to be 1410
=> Reduce Calcio MTU on Fedora CoreOS Azure

aws/container-linux/kubernetes/bootstrap.tf, aws/container-linux/kubernetes/security.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/security.tf, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/container-linux/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/security.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/security.tf, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/network.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/network.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/network.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/network.tf, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Accept experimental CNI `networking` mode "cilium"
* Run Cilium v1.8.0-rc4 with overlay vxlan tunnels and a minimal set of features. We're interested in:
* IPAM: Divide pod_cidr into /24 subnets per node
* CNI networking pod-to-pod, pod-to-external
* BPF masquerade
* NetworkPolicy as defined by Kubernetes (no L7 Policy)
* Continue using kube-proxy with Cilium probe mode
* Firewall changes:
* Require UDP 8472 for vxlan (Linux kernel default) between nodes
* Optional ICMP echo(8) between nodes for host reachability (health)
* Optional TCP 4240 between nodes for endpoint reachability (health)
Known Issues:
* Containers with `hostPort` don't listen on all host addresses, these workloads must use `hostNetwork` for now https://github.com/cilium/cilium/issues/12116
* Erroneous warning on …
=> Add experimental Cilium CNI provider

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.19.1
=> Update Prometheus from v2.19.0 to v2.19.1

CHANGES.md, addons/prometheus/deployment.yaml
* Prometheus has not published the v1.19.2 image
* This reverts commit 81b6f54169119702c3cc6a3ecabca77f8646b444.
=> Revert "Update Prometheus from v2.19.1 to v2.19.2"

CHANGES.md, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/container-linux/kubernetes/network.tf, digital-ocean/container-linux/kubernetes/outputs.tf, digital-ocean/container-linux/kubernetes/versions.tf, digital-ocean/container-linux/kubernetes/workers.tf, digital-ocean/fedora-coreos/kubernetes/controllers.tf, digital-ocean/fedora-coreos/kubernetes/network.tf, digital-ocean/fedora-coreos/kubernetes/outputs.tf, digital-ocean/fedora-coreos/kubernetes/versions.tf, digital-ocean/fedora-coreos/kubernetes/workers.tf, docs/architecture/digitalocean.md
* DigitalOcean introduced Virtual Private Cloud (VPC) support to match other clouds and enhance the prior "private networking"
feature. Before, droplet's belonging to different clusters (but residing in the same region) could reach one another (although
Typhoon firewall rules prohibit this). Now, droplets in a VPC reside in their own network
* https://www.digitalocean.com/docs/networking/vpc/
* Create droplet instances in a VPC per cluster. This matches the design of Typhoon AWS, Azure, and GCP
* Require `terraform-provider-digitalocean` v1.16.0+ (action required)
* Output `vpc_id` for use with an attached DigitalOcean loadbalancer
=> Isolate each DigitalOcean cluster in its own VPC

CHANGES.md, google-cloud/fedora-coreos/kubernetes/controllers.tf, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/workers.tf, google-cloud/fedora-coreos/kubernetes/workers/variables.tf, google-cloud/fedora-coreos/kubernetes/workers/workers.tf
* In v1.18.3, the `os_stream` variable was added to select a Fedora CoreOS image stream (stable, testing, next) on AWS and Google Cloud (which publish official streams)
* Remove `os_image` variable deprecated in v1.18.3. Manually uploaded images are no longer needed
=> Remove os_image variable on Google Cloud Fedora CoreOS

CHANGES.md, azure/container-linux/kubernetes/cl/controller.yaml, azure/container-linux/kubernetes/controllers.tf, azure/container-linux/kubernetes/workers/cl/worker.yaml, azure/container-linux/kubernetes/workers/workers.tf
* Set Kubelet cgroup driver to systemd when Flatcar Linux edge is chosen
Note: Typhoon module status assumes use of the stable variant of an OS channel/stream. Its possible to use earlier variants and
those are sometimes tested or developed against, but stable is the recommendation
=> Allow using Flatcar Linux edge on Azure

docs/advanced/worker-pools.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/bare-metal.md, docs/flatcar-linux/digitalocean.md, docs/flatcar-linux/google-cloud.md
* Remove coreos-stable, coreos-beta, and coreos-alpha channel references from docs
* CoreOS Container Linux is end of life (see changelog)
=> Remove CoreOS Container Linux image names from docs

aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* Set etcd data directory /var/lib/etcd permissions to 700, required in etcd v3.4.10
* On Flatcar Linux, /var/lib/etcd is pre-existing and Ignition v2 doesn't overwrite the directory. Update the Container Linux
config, but add the manual chmod workaround to bootstrap for Flatcar Linux users
* https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md#v3410-2020-07-16
* https://github.com/etcd-io/etcd/pull/11798
=> Declare etcd data directory permissions

CHANGES.md, addons/grafana/dashboards-coredns.yaml, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://coredns.io/2020/06/15/coredns-1.7.0-release/
* Update Grafana dashboard with revised metrics names
=> Update CoreDNS from v1.6.7 to v1.7.0

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Fedora CoreOS now ships systemd-udev's `default.link` while Flannel relies on being able to pick its own MAC address for
the `flannel.1` link for tunneled traffic to reach cni0 on the destination side, without being dropped
* This change first appeared in FCOS testing-devel 32.20200624.20.1 and is the behavior going forward in FCOS since it was added to align FCOS network naming / configs with the rest of Fedora and address issues related to the default being missing
* Flatcar Linux (and Container Linux) has a specific flannel.link configuration builtin, so it was not affected
* https://github.com/coreos/fedora-coreos-tracker/issues/574#issuecomment-665487296
Note: Typhoon's default CNI provider is Calico (recommended), unless `networking` is set to flannel directly.
=> Fix flannel support on Fedora CoreOS

bare-metal/container-linux/kubernetes/versions.tf, bare-metal/fedora-coreos/kubernetes/versions.tf
* Allow use of terraform-provider-matchbox v0.3+ (which allows v0.3.0 <= version < v1.0) for any pre 1.0 release
* Before, the requirement was v0.3.0 <= version < v0.4.0
Related: https://github.com/poseidon/terraform-provider-matchbox/releases/tag/v0.4.0
=> Relex terraform-provider-matchbox version constraint

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, docs/topics/security.md, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* Update CNI plugins from v0.6.0 to v0.8.6 to fix several CVEs
* Update the base image to alpine:3.12 (likely scratch later)
* Use `flannel-cni` as an init container and remove sleep
* https://github.com/poseidon/terraform-render-bootstrap/pull/205
* https://github.com/poseidon/flannel-cni
* https://quay.io/repository/poseidon/flannel-cni
Background
* Switch from github.com/coreos/flannel-cni v0.3.0 which was last published by me in 2017 and is no longer accessible to me to maintain or patch
* Port to the poseidon/flannel-cni rewrite, which releases v0.4.0 to continue the prior release numbering
=> Update from coreos/flannel-cni to poseidon/flannel-cni

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.1.3
* https://github.com/grafana/grafana/releases/tag/v7.1.2
=> Update Grafana from v7.1.1 to v7.1.3

CHANGES.md, aws/container-linux/kubernetes/versions.tf, aws/container-linux/kubernetes/workers/versions.tf, aws/fedora-coreos/kubernetes/versions.tf, aws/fedora-coreos/kubernetes/workers/versions.tf, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/bare-metal.md, docs/flatcar-linux/google-cloud.md
* Typhoon AWS is compatible with terraform-provider-aws v3.x releases
* Continue to allow v2.23+, no v3.x specific features are used
* Set required provider versions in the worker module, since it can be used independently
Related:
* https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v3.0.0
=> Allow terraform-provider-aws v3.0+ plugin

CHANGES.md, docs/topics/maintenance.md
* Mention the first master branch SHA that introduced Terraform v0.13 forward compatibility
* Link the migration guide on Github until a release is available and website docs are published
=> Update Terraform migration guide SHA

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
There's already a [merged PR](https://github.com/poseidon/typhoon/pull/708) addressing the same problem on the controller that runs `bootstrap` service. However, on other controllers, Docker pods `kube-apiserver`, `kube-scheduler`, and `kube-controller-manager` still cannot read files from `/etc/kubernetes/bootstrap-secrets` (on host) due to the wrong SELinux file label (specifically `user` field).
On the controller that has run `bootstrap` service:
```
[root@ip-10-20-139-198 ~]$ ls -alZ /etc/kubernetes
total 16
drwxr-xr-x.  5 root root system_u:object_r:container_file_t:s0   91 Aug 18 03:16 .
drwxr-xr-x. 80 root root system_u:object_r:etc_t:s0            4096 Aug 18 03:13 ..
drwxr-xr-x.  2 root root system_u:object_r:container_file_t:s0  220 Aug 18 03:16 bootstrap-secrets
-rw-r--r--.  1 …
```
=> Fix SELinux label of bootstrap-secrets on non-bootstrapping controllers

docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/google-cloud.md, requirements.txt
* Sync Terraform provider plugins with those used internally
* Update mkdocs-material from v5.5.11 to v5.5.12
=> Update recommended Terraform provider versions

CHANGES.md, addons/grafana/deployment.yaml, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml, addons/prometheus/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml, addons/prometheus/exporters/node-exporter/daemonset.yaml, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* seccomp graduated to GA in Kubernetes v1.19. Support for seccomp alpha annotations will be removed in v1.22
* Replace seccomp annotations with the GA seccompProfile field in the PodTemplate securityContext
* Switch profile from `docker/default` to `runtime/default` (no effective change, since docker is the runtime)
* Verify with docker inspect SecurityOpt. Without the profile, you'd see `seccomp=unconfined`
Related: https://github.com/poseidon/terraform-render-bootstrap/pull/215
=> Change seccomp annotations to seccompProfile

CHANGES.md, addons/nginx-ingress/aws/class.yaml, addons/nginx-ingress/azure/class.yaml, addons/nginx-ingress/bare-metal/class.yaml, addons/nginx-ingress/digital-ocean/class.yaml, addons/nginx-ingress/google-cloud/class.yaml
* Kubernetes v1.19 graduated Ingress and IngressClass from `networking.k8s.io/v1beta1` to `networking.k8s.io/v1`
=> Update IngressClass resources to networking.k8s.io/v1

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, docs/addons/fleetlock.md, docs/advanced/customization.md, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* No notable changes in the config spec, just house keeping
* Require any snippets customization to update to v1.1.0. Version skew
between the main config and snippets will show an err message
Related: https://github.com/coreos/fcct/blob/master/docs/configuration-v1_1.md
=> Update Fedora CoreOS Config version from v1.0.0 to v1.1.0

CHANGES.md
* Cilium was added as an experimental CNI provider in June
* Since then, I've been choosing it for an increasing number of clusters and scenarios
=> Promote Cilium from experimental to GA

CHANGES.md, addons/prometheus/config.yaml
* Originally, Kubelet and CAdvisor metrics used a labelmap relabel to add Kubernetes SD node labels onto timeseries
* With https://github.com/poseidon/typhoon/pull/596 that relabel was dropped since node labels aren't usually that
valuable. `__meta_kubernetes_node_name` was retained but the field name is empty
* Favor just using Prometheus server-side `instance` in queries that require some node identifier for aggregation or debugging
Fix https://github.com/poseidon/typhoon/issues/823
=> Remove labelmap relabel_config for Kubernetes node_name

CHANGES.md, addons/prometheus/config.yaml
* Reduce `apiserver_request_duration_seconds_count` cardinality
by dropping series for non-core Kubernetes APIs. This is done
to match `apiserver_request_duration_seconds_count` relabeling
* These two relabels must be performed the same way to avoid
affecting new SLO calculations (upcoming)
* See https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/498
Related: https://github.com/poseidon/typhoon/pull/596
=> Reduce apiserver metrics cardinality of non-core APIs

CHANGES.md, aws/container-linux/kubernetes/ami.tf, aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/variables.tf, aws/container-linux/kubernetes/workers/ami.tf, aws/container-linux/kubernetes/workers/variables.tf, aws/container-linux/kubernetes/workers/workers.tf, azure/container-linux/kubernetes/controllers.tf, azure/container-linux/kubernetes/variables.tf, azure/container-linux/kubernetes/workers/variables.tf, azure/container-linux/kubernetes/workers/workers.tf, bare-metal/container-linux/kubernetes/variables.tf, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/variables.tf, google-cloud/container-linux/kubernetes/workers/variables.tf
* CoreOS Container Linux was deprecated in v1.18.3 (May 2020) in favor of Fedora CoreOS and Flatcar Linux. CoreOS Container Linux references were kept to give folks more time to migrate, but AMIs have now been deleted. Time is up.
* CoreOS Container Linux [EOL](https://coreos.com/os/eol/)
Related:
* Deprecation https://github.com/poseidon/typhoon/pull/702
* Flatcar/AWS fix https://github.com/poseidon/typhoon/issues/838
=> Remove references to CoreOS Container Linux

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/cluster-role.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-alpha
* https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-alpha.1
=> Update kube-state-metrics from v1.9.7 to v2.0.0-alpha.1

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://github.com/projectcalico/calico/releases/tag/v3.16.3
* https://github.com/poseidon/terraform-render-bootstrap/pull/212
=> Update Calico from v3.15.3 to v3.16.3

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/container-linux/kubernetes/workers/cl/worker.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/container-linux/kubernetes/workers/cl/worker.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/worker.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/container-linux/kubernetes/cl/worker.yaml, docs/architecture/operating-systems.md, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml
* Use docker to run the `kubelet.service` container
* Update Kubelet mounts to match Fedora CoreOS
* Remove unused `/etc/ssl/certs` mount (see https://github.com/poseidon/typhoon/pull/810)
* Remove unused `/usr/share/ca-certificates` mount
* Remove `/etc/resolv.conf` mount, Docker default is ok
* Change `delete-node.service` to use docker instead of rkt and inline ExecStart, as was done on Fedora CoreOS
* Fix permission denied on shutdown `delete-node`, caused by the kubeconfig mount changing with the introduction of node TLS bootstrap
Background
* podmand, rkt, and runc daemonless container process runners provide advantages over the docker daemon for system containers. Docker requires workarounds for use in systemd units where the ExecStart must tail logs so systemd can monitor the …
=> Change Flatcar kubelet.service container from rkt to docker

CHANGES.md, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* On cloud platforms, `delete-node.service` tries to delete the local node (not always possible depending on preemption time)
* Since v1.18.3, kubelet TLS bootstrap generates a kubeconfig in `/var/lib/kubelet` which should be used with kubectl in the delete-node oneshot
Fixed on Flatcar Linux in https://github.com/poseidon/typhoon/pull/855
=> Fix delete node permission on Fedora CoreOS node shutdown

CHANGES.md, bare-metal/flatcar-linux/kubernetes/cl/install.yaml, bare-metal/flatcar-linux/kubernetes/groups.tf, bare-metal/flatcar-linux/kubernetes/profiles.tf, bare-metal/flatcar-linux/kubernetes/variables.tf
* Remove Matchbox profiles for CoreOS Container Linux
* Simplify the remaining Flatcat Linux profiles
=> Remove bare-metal CoreOS Container Linux profiles

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/projectcalico/calico/releases/tag/v3.16.4
=> Update Calico from v3.16.3 to v3.16.4

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/cluster-role.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-alpha.2
=> Update kube-state-metrics from v2.0.0-alpha.1 to v2.0.0-alpha.2

CHANGES.md, aws/flatcar-linux/kubernetes/cl/controller.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, docs/architecture/operating-systems.md, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml
* Use docker to run the `etcd-member.service` container
* Use environment variables from `/etc/etcd/etcd.env` (like podman on FCOS)
* Background: https://github.com/poseidon/typhoon/pull/855
=> Change Flatcar etcd-member.service container from rkt to docker

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, docs/advanced/customization.md, docs/topics/security.md, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* Allow a snippet with a systemd dropin to set an alternate image via `ETCD_IMAGE`, for consistency across Fedora CoreOS
and Flatcar Linux
* Drop comments about integrating system containers with systemd-notify
=> Improve and tidy Fedora CoreOS etcd-member.service

CHANGES.md, README.md, aws/fedora-coreos/kubernetes/README.md, aws/flatcar-linux/kubernetes/README.md, azure/flatcar-linux/kubernetes/README.md, bare-metal/flatcar-linux/kubernetes/README.md, digital-ocean/flatcar-linux/kubernetes/README.md, google-cloud/flatcar-linux/kubernetes/README.md
Some documentation links were pointing to `https://typhoon.psdn.io/cl/` which appears to have moved to `https://typhoon.psdn.io/flatcar-linux/` at some point without redirect.  Updated links as appropriate to remediate.
=> Fix broken flatcar linux documentation links

CHANGES.md, aws/fedora-coreos/kubernetes/ami.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/controllers.tf, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers.tf, aws/fedora-coreos/kubernetes/workers/ami.tf, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, aws/fedora-coreos/kubernetes/workers/variables.tf, aws/fedora-coreos/kubernetes/workers/workers.tf, docs/advanced/arm64.md, docs/advanced/overview.md, mkdocs.yml, requirements.txt
* Add experimental `arch` variable to Fedora CoreOS AWS, accepting amd64 (default) or arm64 to support native arm64/aarch64 clusters or mixed/hybrid clusters with a worker pool of arm64 workers
* Add `daemonset_tolerations` variable to cluster module (experimental)
* Add `node_taints` variable to workers module
* Requires flannel CNI and experimental Poseidon-built arm64 Fedora CoreOS AMIs (published to us-east-1, us-east-2, and us-west-1)
Warn: These ARM64 AMIs are unofficial and experimental. They may be removed at any time and will be removed when Fedora CoreOS publishes official arm64 AMIs. Do NOT use in production
Related: https://github.com/poseidon/typhoon/pull/682
=> Add experimental Fedora CoreOS arm64 support on AWS

addons/prometheus/rules.yaml
* Kubernetes watch expiry is not a gRPC code we care about
* Background: This rule is typically removed, but was added back in
=> Discard Prometheus etcd gRPC failure alert

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.3.2
=> Update Grafana from v7.3.1 to v7.3.2

CHANGES.md, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/versions.tf, aws/fedora-coreos/kubernetes/workers/variables.tf, aws/fedora-coreos/kubernetes/workers/versions.tf, aws/flatcar-linux/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/versions.tf, aws/flatcar-linux/kubernetes/workers/variables.tf, aws/flatcar-linux/kubernetes/workers/versions.tf, azure/fedora-coreos/kubernetes/versions.tf, azure/fedora-coreos/kubernetes/workers/versions.tf, azure/flatcar-linux/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/versions.tf, azure/flatcar-linux/kubernetes/workers/variables.tf, azure/flatcar-linux/kubernetes/workers/versions.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/versions.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, bare-metal/flatcar-linux/kubernetes/versions.tf, digital-ocean/fedora-coreos/kubernetes/versions.tf, digital-ocean/flatcar-linux/kubernetes/versions.tf, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/versions.tf, google-cloud/fedora-coreos/kubernetes/workers/variables.tf, google-cloud/fedora-coreos/kubernetes/workers/versions.tf, google-cloud/flatcar-linux/kubernetes/versions.tf, google-cloud/flatcar-linux/kubernetes/workers/versions.tf
* Support for migrating from Terraform v0.12.x to v0.13.x was added in v1.18.8
* Require Terraform v0.13+. Drop support for Terraform v0.12
=> Add Terraform v0.13 input variable validations

CHANGES.md, aws/fedora-coreos/kubernetes/nlb.tf, aws/flatcar-linux/kubernetes/nlb.tf, docs/architecture/aws.md
* NLB subnets assigned both IPv4 and IPv6 addresses
* NLB DNS name has both A and AAAA records
* NLB to target node traffic is IPv4 (no change), no change to security groups needed
* Ingresses exposed through the recommended Nginx Ingress Controller addon will be accessible via
IPv4 or IPv6. No change is needed to the app's CNAME to NLB record
Related:
* https://aws.amazon.com/about-aws/whats-new/2020/11/network-load-balancer-supports-ipv6/
* Now both GCP and AWS (new) support exposing Ingress via IPv6
=> Enable Network Load Balancer (NLB) dualstack

CHANGES.md, aws/fedora-coreos/kubernetes/outputs.tf, aws/flatcar-linux/kubernetes/outputs.tf, azure/fedora-coreos/kubernetes/outputs.tf, azure/flatcar-linux/kubernetes/outputs.tf, bare-metal/fedora-coreos/kubernetes/outputs.tf, bare-metal/flatcar-linux/kubernetes/outputs.tf, digital-ocean/fedora-coreos/kubernetes/outputs.tf, digital-ocean/flatcar-linux/kubernetes/outputs.tf, google-cloud/fedora-coreos/kubernetes/outputs.tf, google-cloud/flatcar-linux/kubernetes/outputs.tf
* Mark `kubeconfig` and `asset_dist` as `sensitive` to prevent the Terraform CLI displaying these values, esp. for CI systems
* In particular, external tools or tfvars style uses (not recommended) reportedly display all outputs and are improved by setting sensitive
* For Terraform v0.14, outputs referencing sensitive fields must also be annotated as sensitive
Closes https://github.com/poseidon/typhoon/issues/884
=> Set kubeconfig and asset_dist as sensitive

CHANGES.md, aws/fedora-coreos/kubernetes/ami.tf, aws/fedora-coreos/kubernetes/controllers.tf, aws/fedora-coreos/kubernetes/workers/ami.tf, aws/fedora-coreos/kubernetes/workers/workers.tf
* A `aws_ami` data source will fail a Terraform plan if no matching AMI is found, even if the AMI is not used. ARM64 images are only published to a few US regions, so the `aws_ami` data query could fail when creating Fedora CoreOS AWS clusters in non-US regions
* Condition `aws_ami` on whether experimental arch `arm64` is chosen
* Recent regression introduced in v1.19.4 https://github.com/poseidon/typhoon/pull/875
Closes https://github.com/poseidon/typhoon/issues/886
=> Fix Fedora CoreOS AWS AMI query in non-US regions

CHANGES.md, bare-metal/fedora-coreos/kubernetes/profiles.tf, docs/fedora-coreos/bare-metal.md
* Fedora CoreOS stable (after Oct 6) ships separate initramfs and rootfs images, used as initrd's
* Update profiles to match the Matchbox examples, which have already switched to the new profile and to remove the unused kernel args
* Requires Fedora CoreOS version which ships rootfs images (e.g. stable 32.20200923.3.0 or later)
Rel:
* https://github.com/coreos/fedora-coreos-tracker/issues/390#issuecomment-661986987
* https://github.com/poseidon/matchbox/commit/da0df01763693b6391b3f6f9b7a267818075cef8#diff-4541f7b7c174f6ae6270135942c1c65ed9e09ebe81239709f5a9fb34e858ddcf
Supercedes https://github.com/poseidon/typhoon/pull/888
=> Update Matchbox profile to use initramfs and rootfs images

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Add kube-apiserver flags for TokenReview and TokenRequestProjection (beta, defaults on) to allow using Service Account Token Volume Projection to create and mount service account tokens tied to a Pod's lifecycle
Rel:
* https://github.com/poseidon/terraform-render-bootstrap/pull/231
* https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection
=> Add TokenReview and TokenRequestProjection flags

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/flatcar-linux/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/flatcar-linux/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml
* Generate TLS client certificates for `kube-scheduler` and `kube-controller-manager` with `system:kube-scheduler` and
`system:kube-controller-manager` CNs
* Template separate kubeconfigs for kube-scheduler and kube-controller manager (`scheduler.conf` and `controller-manager.conf`). Rename admin for clarity
* Before v1.16.0, Typhoon scheduled a self-hosted control plane, which allowed the steady-state kube-scheduler and kube-controller-manager to use a scoped ServiceAccount. With a static pod control plane, separate CN TLS client certificates are the nearest equiv.
* https://kubernetes.io/docs/setup/best-practices/certificates/
* Remove unused Kubelet certificate, TLS bootstrap is used instead
=> Add kubeconfig's for kube-scheduler and kube-controller-manager

aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/flatcar-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml
* Change control plane static pods to mount `/etc/kubernetes/pki`, instead of `/etc/kubernetes/bootstrap-secrets` to better reflect
their purpose and match some loose conventions upstream
* Place control plane and bootstrap TLS assets and kubeconfig's in `/etc/kubernetes/pki`
* Mount to `/etc/kubernetes/pki` (rather than `/etc/kubernetes/secrets`) to match the host location (less surprise)
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/233
=> Move control plane static pod TLS assets to /etc/kubernetes/pki

CHANGES.md, README.md, docs/index.md
* Fedora CoreOS is a good choice for use on bare-metal
=> Promote Fedora CoreOS bare-metal to stable

CHANGES.md, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/worker.yaml
* Remove Kubelet `/etc/iscsi` and `iscsiadm` host mounts that were added on bare-metal, since these no longer work on either Fedora CoreOS or Flatcar Linux with newer `iscsiadm`
* These special mounts on bare-metal date back to #350 which added them to provide a way to use iSCSI in Kubernetes v1.10
* Today, storage should be handled by external CSI providers which handle different storage systems, which doesn't rely on Kubelet storage utils
Close #907
=> Remove iSCSI mounts from Kubelet

CHANGES.md, docs/fedora-coreos/digitalocean.md, docs/topics/maintenance.md
* Highlight that short-term, use of Fedora CoreOS will require non-RSA SSH keys or a workaround snippet
* See https://github.com/poseidon/typhoon/issues/915
=> Add notice about upstream Fedora CoreOS changes

CHANGES.md, addons/prometheus/exporters/node-exporter/daemonset.yaml
* https://github.com/prometheus/node_exporter/releases/tag/v1.1.1
=> Update node-exporter from v1.0.1 to v1.1.1

CHANGES.md, aws/flatcar-linux/kubernetes/cl/controller.yaml, aws/flatcar-linux/kubernetes/controllers.tf, aws/flatcar-linux/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/workers/cl/worker.yaml, aws/flatcar-linux/kubernetes/workers/variables.tf, aws/flatcar-linux/kubernetes/workers/workers.tf, azure/flatcar-linux/kubernetes/cl/controller.yaml, azure/flatcar-linux/kubernetes/controllers.tf, azure/flatcar-linux/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/workers/cl/worker.yaml, azure/flatcar-linux/kubernetes/workers/variables.tf, azure/flatcar-linux/kubernetes/workers/workers.tf, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/worker.yaml, bare-metal/flatcar-linux/kubernetes/profiles.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, docs/advanced/worker-pools.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/bare-metal.md
* Flatcar Linux has not published an Edge channel image since April 2020 and recently removed mention of the channel from
their documentation https://github.com/kinvolk/Flatcar/pull/345
* Users of Flatcar Linux Edge should move to the stable, beta, or alpha channel, barring any alternate advice from upstream Flatcar Linux
=> Remove Flatcar Linux Edge channel option

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* kube-state-metrics is continuing publishing container images to `k8s.gcr.io` instead of `quay.io`
Rel: https://github.com/kubernetes/kube-state-metrics/issues/1409
=> Switch kube-state-metrics image from quay to k8s.gcr.io

bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml
Added kubelet image environment variable in Fedora bare-metal bootstrap for use with systemd dropins (Flatcar bare-metal already did this.)
=> update fedora bare-metal bootstrap

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Mark the bootstrap token as sensitive, which is useful when Terraform is run in automated CI/CD systems to avoid showing the token
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/251
=> Mark bootstrap token as sensitive in plan/apply

CHANGES.md, azure/fedora-coreos/kubernetes/lb.tf, azure/flatcar-linux/kubernetes/lb.tf
* Remove the deprecated `resource_group_name` field from Azure `azurerm_lb_backend_address_pool` resources
=> Remove deprecated field on azurerm_lb_backend_address_pool

docs/index.md
The link for "Fedora CoreOS on Google Cloud" was pointing to the wrong place, producing a 404. I clicked it because it said `stable` as opposed to Flatcar Linux's `beta`. I got a good chuckle out of the latter working while stable doesn't.
This PR fixes that. Have a nice weekend :rocket:
=> [docs] fix broken link on landing page

README.md, docs/fedora-coreos/digitalocean.md, docs/flatcar-linux/digitalocean.md, docs/index.md
* Use our DigitalOcean referral code for new DigitalOcean users. This gives new accounts free cloud credits and provides a smaller cloud credit back to the project
* Link to the new video meeting via one-time Github Sponsor feature that we're trying out
* List Fedora CoreOS ARM64 as a supported platform (alpha). Before this was only mentioned in docs and on the blog
=> Update docs with video meetings and referral links

CHANGES.md, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers/variables.tf, aws/flatcar-linux/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/workers/variables.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/variables.tf, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/google-cloud.md, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/workers/variables.tf, google-cloud/flatcar-linux/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/workers/variables.tf
* We're typically reducing the `disk_size` in real clusters since the space is under used. The default should be lower.
=> Reduce the default disk_size from 40GB to 30GB

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Fedora CoreOS is beginning to switch from cgroups v1 to cgroups v2 by default, which changes the sysfs hierarchy
* This will be needed when using a Fedora Coreos OS image that enables cgroups v2 (`next` stream as of this writing)
Rel: https://github.com/coreos/fedora-coreos-tracker/issues/292
=> Update Fedora CoreOS Kubelet for cgroups v2

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Add multi-arch container images and arm64 support
* https://github.com/cilium/cilium/releases/tag/v1.10.0-rc1
=> Update Cilium from v1.9.6 to v1.10.0-rc1

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, docs/advanced/arm64.md, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Mention Cilium can be used with ARM64 on FCOS AWS
* https://github.com/cilium/cilium/releases/tag/v1.10.0
=> Update Cilium from v0.10.0-rc1 to v0.10.0

README.md, docs/index.md
* Due to the takeover of freenode.net IRC, the channel there should no longer be used
=> Remove freenode IRC from help section

bare-metal/fedora-coreos/kubernetes/ssh.tf, digital-ocean/fedora-coreos/kubernetes/ssh.tf
* On FCOS 34 / systemd 248, `kubelet.path` won't activate (stuck waiting) when `/etc/kubernetes/kubeconfig` exists, even with manual prodding of the file. The root cause isn't known, but a workaround is to delay `/etc/kubernetes` directory creation
or to touch the directory later
* Fix DigitalOcean worker node kubelet.service being enabled immediately. On bare-metal and DigitalOcean, the kubeconfig
should activate the Kubelet, so it doesn't crashloop needlessly (nice to have, not required)
Rel: https://github.com/coreos/fedora-coreos-tracker/issues/861
=> Workaround systemd 248 path units not working reliably

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://coredns.io/2021/01/20/coredns-1.8.1-release/
* https://coredns.io/2021/02/23/coredns-1.8.2-release/
* https://coredns.io/2021/02/24/coredns-1.8.3-release/
* https://coredns.io/2021/05/28/coredns-1.8.4-release/
=> Update CoreDNS from v1.8.0 to v1.8.4

CHANGES.md, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers/variables.tf, aws/flatcar-linux/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/workers/variables.tf, docs/advanced/worker-pools.md, docs/fedora-coreos/aws.md, docs/flatcar-linux/aws.md
* https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/
=> Change AWS default disk type from gp2 to gp3

CHANGES.md, addons/prometheus/exporters/node-exporter/daemonset.yaml
* https://github.com/prometheus/node_exporter/releases/tag/v1.2.0
=> Update node-exporter from v1.1.2 to v1.2.0

docs/topics/maintenance.md
* Terraform v0.12.x and v0.13.x are now quite outdated, remove the migration docs
=> Remove outdated Terraform migration docs

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* On Fedora CoreOS, Cilium cross-node service IP load balancing stopped working for a time (first observable as CoreDNS pods located on worker nodes not being able to reach the kubernetes API service 10.3.0.1). This turned out to have two parts:
* Fedora CoreOS switched to cgroups v2 by default. In our early testing with cgroups v2, Calico (default) was used. With the
cgroups v2 change, SELinux policy denied some eBPF operations.
Since fixed in all Fedora CoreOS channels
* Cilium requires new mounts to support cgroups v2, which are added here
Related:
* https://github.com/coreos/fedora-coreos-tracker/issues/292
* https://github.com/coreos/fedora-coreos-tracker/issues/881
* https://github.com/cilium/cilium/pull/16259
* https://github.com/poseidon/terraform-render-bootstrap/pull/271
=> Update Cilium for cgroups v2 support

CHANGES.md, addons/prometheus/config.yaml, addons/prometheus/discovery/kube-controller-manager.yaml, addons/prometheus/discovery/kube-scheduler.yaml, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/security.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/security.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/security.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/security.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/network.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/network.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/network.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/network.tf
* Kubernetes v1.22.0 disabled kube-controller-manager insecure port, which was used internally for Prometheus metrics scraping
* Configure Prometheus to discover and scrape endpoints for kube-scheduler and kube-controller-manager via the authenticated https ports, via bearer token
* Change firewall ports to allow Prometheus (on worker nodes) to scrape kube-scheduler and kube-controller-manager targets
that run on controller(s) with hostNetwork
* Disable the insecure port on kube-scheduler
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/273
=> Update Prometheus discovery of kube components

README.md, docs/advanced/arm64.md, docs/advanced/worker-pools.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, docs/index.md
* For Fedora CoreOS, users should not be using sha-rsa public keys anymore, so make sure the docs examples reflect this
* https://github.com/poseidon/typhoon/issues/915
=> Show SSH keys with ssh-ed25519 instead of sha-rsa in docs

docs/topics/security.md
* Poseidon infra publishes official multi-arch container images for Kubelet to both Quay and Dockerhub (fallback) and continues to do so. There are no changes to the official images used in Typhoon
* Automated builds by Quay and Dockerhub added separately tagged images for those not able to trust our own images and preferring to trust Quay/Dockerhub. Going forward, we're ending the use of Dockerhub automated builds. Docker has moved automated builds to paid plans, even for open source projects (we're not petitioning for a special exemption given these are our unofficial images, just not worth the hassle). Those still needing Kubelet images built externally (i.e. not Poseidon Labs) would still be able to use the Quay images tagged `build-SHA`
Blog: …
=> Discontinue Docker automated build publishing

aws/fedora-coreos/kubernetes/ami.tf
* Use upstream ami for aarch64 Fedora CoreOS repo as the Fedora CoreOS team has starting publish images.
`aws ec2 describe-images --owners 125523088429 --filters "Name=architecture,Values=arm64" "Name=description,Values=*Fedora CoreOS*"`
rel: https://github.com/coreos/fedora-coreos-tracker/issues/541 https://getfedora.org/en/coreos?stream=stable
=> Use official Fedora CoreOS AMI for aarch64

CHANGES.md, bare-metal/fedora-coreos/kubernetes/versions.tf, bare-metal/flatcar-linux/kubernetes/versions.tf, docs/fedora-coreos/bare-metal.md, docs/flatcar-linux/bare-metal.md
* Relax version constraint to allow future minor version releases to be used without a corresponding Typhoon change
=> Update Terraform provider poseidon/matchbox to v0.5+

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Update Calico from v3.20.2 to v3.21.0
* Update Flannel from v0.14.0 to v0.15.0
=> Update Calico and Flannel CNI providers

CHANGES.md, aws/flatcar-linux/kubernetes/cl/controller.yaml, aws/flatcar-linux/kubernetes/workers/cl/worker.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, azure/flatcar-linux/kubernetes/workers/cl/worker.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/worker.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/worker.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/flatcar-linux/kubernetes/workers/cl/worker.yaml
* Remove `/sys/fs/cgroup/systemd` mount since Flatcar Linux uses cgroups v2
* Flatcar Linux's `docker` switched from the `cgroupfs` to `systemd` driver without notice
=> Fix Flatcar Linux docker driver and add cgroups v2

aws/fedora-coreos/kubernetes/ami.tf, aws/fedora-coreos/kubernetes/workers/ami.tf
* Fix worker nodes to use official Fedora CoreOS AMIs, instead of the older Poseidon built AMIs (now removed).
This should have been part of #1038, but was missed in code review
* Poseidon build AMIs have been deleted (so I don't have to keep paying to host them for people)
=> Switch FCOS workers to official Fedora CoreOS AMIs

CHANGES.md, aws/fedora-coreos/kubernetes/variables.tf
* Since v1.21.3 switched controllers default disk type from `gp2` to `gp3`, an iops diff has been shown (harmless, but
annoying)
* Controller nodes default to a 30GB `gp3` disk. `gp3` disks do respect `iops` and the corresponding default is 3000
=> Change default `disk_iops` from unset to 3000

CHANGES.md, aws/flatcar-linux/kubernetes/variables.tf
* Same as #1073, but for Flatcar Linux on AWS as well
=> Change default disk_iops on Flatcar Linux

google-cloud/fedora-coreos/kubernetes/versions.tf
* Part of https://github.com/poseidon/typhoon/pull/1074
=> Fix null provider version constraint on Google Cloud

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Mount both /etc/ssl/certs and /etc/pki into control plane static pods and kube-proxy, rather than choosing one based a variable
(set based on Flatcar Linux or Fedora CoreOS)
* Remove deprecated `--port` from `kube-scheduler` static Pod
=> Normalize CA certs mounts in static Pods and kube-proxy

CHANGES.md, aws/fedora-coreos/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, digital-ocean/fedora-coreos/kubernetes/variables.tf, digital-ocean/flatcar-linux/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/variables.tf
* Change `enable_aggregation` default from false to true
* These days, Kubernetes control plane components emit annoying messages related to assumptions baked into the Kubernetes API Aggregation Layer if you don't enable it. Further the conformance tests force you to remember to enable it if you care about passing those
* This change is motivated by eliminating annoyances, rather than any enthusiasm for Kubernetes' aggregation features
Note: This was meant to be included in v1.23.3. Updated CHANGELOG
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/279
=> Enable Kubernetes aggregation by default

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, aws/flatcar-linux/kubernetes/cl/controller.yaml, aws/flatcar-linux/kubernetes/workers/cl/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, azure/flatcar-linux/kubernetes/workers/cl/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/flatcar-linux/kubernetes/workers/cl/worker.yaml
* Both Flatcar Linux and Fedora CoreOS use systemd-resolved, but they setup /etc/resolv.conf symlinks differently
* Prefer using /run/systemd/resolve/resolv.conf directly, which also updates to reflect runtime changes (e.g. resolvectl)
=> Set Kubelet resolver config to /run/systemd/resolve/resolv.conf

CHANGES.md, aws/flatcar-linux/kubernetes/cl/controller.yaml, aws/flatcar-linux/kubernetes/workers/cl/worker.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, azure/flatcar-linux/kubernetes/workers/cl/worker.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/worker.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/worker.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/flatcar-linux/kubernetes/workers/cl/worker.yaml
* Use containerd as the Kubernetes Container Runtime
=> Switch Flatcar Linux to using containerd CRI

CHANGES.md, aws/fedora-coreos/kubernetes/ssh.tf, aws/flatcar-linux/kubernetes/ssh.tf, azure/fedora-coreos/kubernetes/ssh.tf, azure/flatcar-linux/kubernetes/ssh.tf, bare-metal/fedora-coreos/kubernetes/ssh.tf, bare-metal/flatcar-linux/kubernetes/ssh.tf, digital-ocean/fedora-coreos/kubernetes/ssh.tf, digital-ocean/flatcar-linux/kubernetes/ssh.tf, google-cloud/fedora-coreos/kubernetes/ssh.tf, google-cloud/flatcar-linux/kubernetes/ssh.tf
* Terraform v1.1 changed the behavior of provisioners and `remote-exec` in a way that breaks support for expansions in commands (including file provisioner, where `destination` is part of an `scp` command)
* Terraform will likely revert the change eventually, but I suspect it will take a while
* Instead, we can stop relying on Terraform's expansion behavior. `/home/core` is a suitable choice for `$HOME` on both Flatcar Linux and Fedora CoreOS (harldink `/var/home/core`)
Rel: https://github.com/hashicorp/terraform/issues/30243
Closes #1091
=> Workaround Terraform v1.1 file provisioner regression

CHANGES.md, addons/prometheus/config.yaml
* Set `prometheus.io/param` on a Kubernetes Service to scrape the service endpoints and pass a custom query parameter
* For example, scrape Consul with `?format=prometheus`
```yaml
kind: Service
metadata:
annotations:
prometheus.io/scrape: 'true'
prometheus.io/port: '8500'
prometheus.io/path: /v1/agent/metrics
prometheus.io/param: format=prometheus
```
Closes #1061
=> Configure Prometheus to allow a custom scrape query param

CHANGES.md, addons/prometheus/config.yaml, addons/prometheus/rbac/cluster-role.yaml
* Allow Kubernetes Ingress resources to be probed via Blackbox Exporter (if present) if annotated `prometheus.io/probe: "true"`
* Fix probes of Services via Blackbox Exporter. Require Blackbox Exporter to be deployed in the same `monitoring` namespace, be named `blackbox-exporter`, and use port 8080
Closes #1037
=> Add Prometheus config for monitoring Kubernetes Ingress

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Migrate from `docker-shim` to `containerd` in preparation for Kubernetes v1.24.0 dropping `docker-shim` support
* Much consideration was given to the container runtime choice. https://github.com/poseidon/typhoon/issues/899 provides relevant rationales
Rel: #899
=> Switch Fedora CoreOS from docker-shim to containerd

aws/fedora-coreos/kubernetes/fcc/controller.yaml
* etcd used to require a special variable to use the arm64 container image, but this is no longer required
=> Remove unused ETCD_UNSUPPORTED_ARCH variable

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Gradually start removing the `template` provider in favor of `templatefile` (though its less readable)
=> Remove `template` provider usage from terraform-render-bootstrap

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Kubelet now uses `containerd` as the container runtime, but `docker.service` still starts when `docker.sock` is probed bc
the service is socket activated. Prevent this by masking the `docker.service` unit
=> Mask docker.service to prevent socket activation

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, aws/flatcar-linux/kubernetes/cl/controller.yaml, aws/flatcar-linux/kubernetes/workers/cl/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, azure/flatcar-linux/kubernetes/workers/cl/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/worker.yaml, docs/advanced/overview.md, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/flatcar-linux/kubernetes/workers/cl/worker.yaml
* Now that `docker-shim` is no longer used, the Kubelet flag is no longer needed and will be removed in v1.24
=> Remove Kubelet `--network-plugin=cni` flag

CHANGES.md, README.md, docs/advanced/worker-pools.md, docs/flatcar-linux/google-cloud.md, docs/index.md, google-cloud/flatcar-linux/kubernetes/controllers.tf, google-cloud/flatcar-linux/kubernetes/image.tf, google-cloud/flatcar-linux/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/workers/image.tf, google-cloud/flatcar-linux/kubernetes/workers/variables.tf, google-cloud/flatcar-linux/kubernetes/workers/workers.tf
* Use the official Kinvolk Flatcar Linux image on Google Cloud
* Change `os_image` from a custom image name to `flatcar-stable` (default), `flatcar-beta`, or `flatcar-alpha` (**action required**)
* Change `os_image` from a required to an optional variable
* Promote Typhoon on Flatcar Linux / Google Cloud to stable
* Remove docs about needing to upload a Flatcar Linux image manually on Google Cloud and drop support for custom images
=> Switch to using Flatcar Linux images on Google Cloud

CHANGES.md, aws/fedora-coreos/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, digital-ocean/fedora-coreos/kubernetes/variables.tf, digital-ocean/flatcar-linux/kubernetes/variables.tf, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/bare-metal.md, docs/flatcar-linux/digitalocean.md, docs/flatcar-linux/google-cloud.md, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/variables.tf
* Cilium (v1.8) was added to Typhoon in v1.18.5 in June 2020 and its become more impressive since then. Its currently the leading CNI provider choice.
* Calico has grown complex, has lots of CRDs, masks management complexity with an operator (which we won't use), doesn't provide multi-arch images, and hasn't been compatible with Kubernetes v1.23 (with ipvs) for several releases.
* Both have CNCF conformance quirks (flannel used for conformance), but that's not the main factor in choosing the default
=> Change default CNI provider from Calico to Cilium

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* kube-state-metrics:v2.4.0 isn't published, skip it
=> Revert kube-state-metrics upgrade

aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Kubelet node's System UUID can be detected from the sysfs filesystem without a host mount, but if you need to distinguish
between the host's machine-id and SystemUUID
* On cloud platforms, MachineID and SystemUUID are identical, but on bare-metal the two differ
=> Mount /etc/machine-id from host into Kubelet

CHANGES.md, azure/fedora-coreos/kubernetes/lb.tf, azure/fedora-coreos/kubernetes/network.tf, azure/fedora-coreos/kubernetes/outputs.tf, azure/fedora-coreos/kubernetes/security.tf, azure/fedora-coreos/kubernetes/versions.tf, azure/fedora-coreos/kubernetes/workers/versions.tf, azure/flatcar-linux/kubernetes/lb.tf, azure/flatcar-linux/kubernetes/network.tf, azure/flatcar-linux/kubernetes/outputs.tf, azure/flatcar-linux/kubernetes/security.tf, azure/flatcar-linux/kubernetes/versions.tf, azure/flatcar-linux/kubernetes/workers/versions.tf, docs/architecture/azure.md
* Change subnet references to source and destinations prefixes (plural)
* Remove references to a resource group in some load balancing components, which no longer require it (inferred)
* Rename `worker_address_prefix` output to `worker_address_prefixes`
=> Allow upgrading Azure Terraform Provider to v3.x

CHANGES.md, google-cloud/flatcar-linux/kubernetes/controllers.tf
* Add `boot_disk[0].initialize_params` to the ignored fields for the controller nodes
* Nodes will auto-update, Terraform should not attempt to delete and recreate nodes (especially controllers!). Lack of this ignore causes
Terraform to propose deleting controller nodes when Flatcar Linux releases new images
* Matches the configuration on Typhoon Fedora CoreOS (which does not have the issue)
=> Fix Flatcar Linux nodes on Google Cloud not ignoring image changes

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Fixes warning about use of deprecated field `key_algorithm` in the `hashicorp/tls` provider. The key algorithm can now be inferred directly from the private key so resources don't have to output and pass around the algorithm
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/305
=> Remove use of deprecated `key_algorithm` field in TLS assets

aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
Enable Kubelet to determine SELinux state, enabling it to specify relabelling of mounts without explicitly setting the context on the StorageClass or PersistentVolume mountOptions.
* Added Kubelet mounts for /etc/selinux and /sys/fs/selinux to all FCOS butane templates.
Using a CSI volume through a StorageClass without an explicit mount option will result in the following SELinux content on the host (and not be accessible from within the container):
```
drwx------. 2 root root system_u:object_r:unlabeled_t:s0      16384 Apr 26 16:11 lost+found
```
Kublet is expected to automatically relabel volumes on SELinux enforcing systems. With the [mount flags](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1710-selinux-relabeling/README.md#volume-mounting):
```
--volume …
```
=> Add Kubelet SELinux mounts to enable relabeling workflow volumes

CHANGES.md, addons/grafana/deployment.yaml, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/aws/rbac/role.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/azure/rbac/role.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/bare-metal/rbac/role.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/digital-ocean/rbac/role.yaml, addons/nginx-ingress/google-cloud/deployment.yaml, addons/nginx-ingress/google-cloud/rbac/role.yaml, addons/prometheus/deployment.yaml
* Update ingress-nginx RBAC Role to include coordination.k8s.io leases permissions that are required with ingress-nginx v1.3.0
=> Update Prometheus, Grafana, and ingress-nginx addons

bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/profiles.tf, bare-metal/flatcar-linux/kubernetes/profiles.tf
* Add `initrd=main` kernel argument for UEFI
* Switch to using the `coreos.live.rootfs_url` kernel argument instead of passing the rootfs as an appended initrd
* Remove `coreos.inst.image_url` kernel argument since coreos-installer now defaults to installing from the embedded live system
* Remove `rd.neednet=1` and `dhcp=ip` kernel args that aren't needed
* Remove serial console kernel args by default (these can be added via `var.kernel_args` if needed)
* Remove iptables-legacy.stamp pinning, this doesn't seem required (at least with Cilium)
Rel:
* https://github.com/poseidon/matchbox/pull/972 (thank you @bgilbert)
* https://github.com/poseidon/matchbox/pull/978
=> Update FCOS iPXE initrd and kernel arg settings

CHANGES.md, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Google Cloud Terraform provider resource google_dns_record_set's name field provides the full domain name with a trailing ".". This isn't a new behavior, Google has behaved this way as long as I can remember
* etcd domain names are passed to the bootstrap module to generate TLS certificates. What seems to be new(ish?) is that etcd peers see `example.foo` and `example.foo.` as different domains during TLS SANs validation. As a result, clusters with multiple controller nodes fail to run etcd-member, which manifests as cluster provisioning hanging. Single controller/master clusters (default) are unaffected
* Fix etcd-member.service error in multi-controller clusters:
```
"error":"x509: certificate is valid for conformance-etcd0.redacted.,
conform-etcd1.redacted., conform-etcd2.redacted., …
```
=> Fix bug provisioning multi-controller clusters on Google Cloud

CHANGES.md, aws/flatcar-linux/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/controllers.tf, aws/flatcar-linux/kubernetes/versions.tf, aws/flatcar-linux/kubernetes/workers/butane/worker.yaml, aws/flatcar-linux/kubernetes/workers/versions.tf, aws/flatcar-linux/kubernetes/workers/workers.tf, azure/flatcar-linux/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/controllers.tf, azure/flatcar-linux/kubernetes/versions.tf, azure/flatcar-linux/kubernetes/workers/butane/worker.yaml, azure/flatcar-linux/kubernetes/workers/versions.tf, azure/flatcar-linux/kubernetes/workers/workers.tf, bare-metal/fedora-coreos/kubernetes/profiles.tf, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/install.yaml, bare-metal/flatcar-linux/kubernetes/butane/worker.yaml, bare-metal/flatcar-linux/kubernetes/profiles.tf, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/worker.yaml, digital-ocean/flatcar-linux/kubernetes/controllers.tf, digital-ocean/flatcar-linux/kubernetes/versions.tf, digital-ocean/flatcar-linux/kubernetes/workers.tf, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/controllers.tf, google-cloud/flatcar-linux/kubernetes/versions.tf, google-cloud/flatcar-linux/kubernetes/workers/butane/worker.yaml, google-cloud/flatcar-linux/kubernetes/workers/versions.tf, google-cloud/flatcar-linux/kubernetes/workers/workers.tf
* Requires poseidon v0.11+ and Flatcar Linux 3185.0.0+ (action required)
* Previously, Flatcar Linux configs have been parsed as Container Linux Configs to Ignition v2.2.0 specs by poseidon/ct
* Flatcar Linux starting in 3185.0.0 now supports Ignition v3.x specs (which are rendered from Butane Configs, like Fedora CoreOS)
* poseidon/ct v0.11.0 adds support for the flatcar Butane Config variant so that Flatcar Linux can use Ignition v3.x
Rel:
* [Flatcar Support](https://flatcar-linux.org/docs/latest/provisioning/ignition/specification/#ignition-v3)
* [poseidon/ct support](https://github.com/poseidon/terraform-provider-ct/pull/131)
=> Migrate Flatcar Linux from Ignition spec v2.3.0 to v3.3.0

docs/advanced/customization.md, docs/architecture/operating-systems.md, docs/fedora-coreos/azure.md, docs/flatcar-linux/digitalocean.md
* Typhoon now consistently uses Butane Configs for snippets (variant `fcos` or `flatcar`). Previously snippets were either Butane Configs (on FCOS) or Container Linux Configs (on Flatcar)
* Update docs on uploading Flatcar Linux DigitalOcean images
* Update docs on uploading Fedora CoreOS Azure images
=> Update docs on using Butane snippets for customization

addons/prometheus/exporters/node-exporter/daemonset.yaml
* Add toleration to run node-exporter on controller nodes
* Add HostToContainer mount propagation and security context group settings from upstream
* Fix SELinux denied accessing /host/proc/1/mounts. The mounts file is has an SELinux type attribute init_t, but that won't allow running the node-exporter binary so we have to use spc_t. This should be more targeted at just the SELinux issue than making the Pod privileged
* Remove excluded mount points and filesystem types, the defaults are https://github.com/prometheus/node_exporter/blob/v1.3.1/collector/filesystem_linux.go#L35
```
caller=collector.go:169 level=error msg="collector failed" name=filesystem duration_seconds=0.000666766 err="open /host/proc/1/mounts: permission denied"
```
```
[ 3664.880899] audit: type=1400 …
```
=> Update node-exporter DaemonSet to fix permission denied

CHANGES.md, addons/grafana/deployment.yaml
* Use the liveness and readiness probes that Grafana recommends
* Update Grafana from v9.0.3 to v9.0.5
=> Update Grafana liveness and readiness probes

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* Typhoon Fedora CoreOS is already using iptables nf_tables since F36. The file to pin to legacy iptables was renamed to `/etc/coreos/iptables-legacy.stamp`
=> Remove ineffective iptables-legacy.stamp

CHANGES.md, aws/fedora-coreos/kubernetes/workers/ami.tf, aws/fedora-coreos/kubernetes/workers/workers.tf, aws/flatcar-linux/kubernetes/workers/workers.tf
* Rename launch configuration to use a name_prefix named after the cluster and worker to improve identifiability
* Shorten AWS autoscaling group name to not include the launch config id. Years ago this used to be needed to update the ASG but the AWS provider detects changes to the launch configuration just fine
=> Improve AWS autoscaling group and launch config names

CHANGES.md, google-cloud/fedora-coreos/kubernetes/apiserver.tf, google-cloud/fedora-coreos/kubernetes/network.tf, google-cloud/fedora-coreos/kubernetes/workers/workers.tf, google-cloud/flatcar-linux/kubernetes/apiserver.tf, google-cloud/flatcar-linux/kubernetes/network.tf, google-cloud/flatcar-linux/kubernetes/workers/workers.tf
* When a worker managed instance group's (MIG) instance template changes (including `worker_type`, `disk_size`, `preemptible`, or Butane `worker_snippets` but excluding new AMIs), use Google Cloud's rolling update features to ensure instances match declared state
* Ignore new AMIs since Fedora CoreOS and Flatcar Linux nodes already auto-update and reboot themselves
* Rolling updates will create surge instances, wait for health checks, then delete old instances (0 unavilable instances)
* Instances are replaced to ensure new Ignition/Butane snippets are respected
* Add managed instance group autohealing (i.e. health checks) to ensure new instances' Kubelet is running
Renames
* Name apiserver and kubelet health checks consistently
* Rename MIG from `${var.name}-worker-group` to …
=> Roll instance template changes to worker managed instance groups

CHANGES.md, google-cloud/fedora-coreos/kubernetes/network.tf, google-cloud/fedora-coreos/kubernetes/workers/workers.tf, google-cloud/flatcar-linux/kubernetes/network.tf, google-cloud/flatcar-linux/kubernetes/workers/workers.tf
* Change the workers managed instance group to health check nodes via HTTP probe of the kube-proxy port 10256 /healthz endpoints
* Advantages: kube-proxy is a lower value target (in case there were bugs in firewalls) that Kubelet, its more representative than health checking Kubelet (Kubelet must run AND kube-proxy Daemonset must be healthy), and its already used by kube-proxy liveness probes (better discoverability via kubectl or alerts on pods crashlooping)
* Another motivator is that GKE clusters also use kube-proxy port 10256 checks to assess node health
=> Adjust Google Cloud worker health checks to use kube-proxy healthz

CHANGES.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/bare-metal.md, docs/flatcar-linux/digitalocean.md, docs/flatcar-linux/google-cloud.md, docs/topics/maintenance.md
* Document that worker instances are rolling replaced when changes to their configuration are applied
=> Add docs for GCP MIG update and AWS ASG instance refresh

aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/fedora-coreos/kubernetes/workers/butane/worker.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/workers/butane/worker.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/workers/butane/worker.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/workers/butane/worker.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/worker.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/worker.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/worker.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/worker.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/butane/worker.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/workers/butane/worker.yaml
* Add a KubeletConfiguration file to replace most Kubelet flags, to prepare for upcoming changes
* Pass Kubelet the `--config` flag to specify the location of the KubeletConfiguration
* Remove flsgs / configuration where it matches the defaults
* Remove `--cgroups-per-qos`, defaults to true
* Remove `--container-runtime`, defaults to remote
* Remove `--enforce-node-allocatable=pods`, defaults to pods
Rel:
* https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
* https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
=> Migrate most Kubelet flags to KubeletConfiguration file

aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/fedora-coreos/kubernetes/workers/butane/worker.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/workers/butane/worker.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/workers/butane/worker.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/workers/butane/worker.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/worker.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/worker.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/worker.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/worker.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/butane/worker.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/workers/butane/worker.yaml
* Kubernetes v1.25.0 moved the LocalStorageCapacityIsolationFSQuotaMonitoring feature from alpha to beta, but it breaks Kubelet updating ConfigMaps in Pods, as shown by conformance tests
* Kubernetes is rolling LocalStorageCapacityIsolationFSQuotaMonitoring back to alpha so its not enabled by default, but that will require a release
* Disable the feature gate directly as a workaround for now to make Kubernetes v1.25.0 usable
```
FailedMount: MountVolume.SetUp failed for volume "configmap-volume" : requesting quota on existing directory /var/lib/kubelet/pods/f09fae17-ff16-4a05-aab3-7b897cb5b732/volumes/kubernetes.io~configmap/configmap-volume but different pod 673ad247-abf0-434e-99eb-1c3f57d7fdaa a4568e94-2b2d-438f-a4bd-c9edc814e478
```
Rel:
* …
=> Disable LocalStorageCapacityIsolationFSQuotaMonitoring feature

CHANGES.md, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/fedora-coreos/kubernetes/workers/butane/worker.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/workers/butane/worker.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/worker.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/worker.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/butane/worker.yaml
* When podman runs the Kubelet container, logging to journald means log lines are duplicated in the journal. journalctl -u kubelet shows Kubelet's logs and the same log messages from podman. Using the `k8s-file` driver alleviates this problem
* Fix Kubelet and etcd-member logs to be more readable and reduce unneccessary Kubelet log volume
=> Change Podman log-driver from journald to k8s-file

CHANGES.md, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/fedora-coreos/kubernetes/workers/butane/worker.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/workers/butane/worker.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/workers/butane/worker.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/workers/butane/worker.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/worker.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/worker.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/worker.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/worker.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/butane/worker.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/workers/butane/worker.yaml
* Configure Kubelet Graceful Node Shutdown to detect system shutdown events and stop running containers gracefully when possible
* Allow up to 30s for critical pods to gracefully shutdown
* Allow up to 15s for regular pods to gracefully shutdown
* Node will be marked as NotReady promptly, instead of having to wait for health checks
* Kubelet uses systemd inhibitor locks to delay shutdown for a limited number of seconds
* Raise the default max inhibitor time from 5s to 45s
Verify systemd inhibitor locks are present:
```
sudo systemd-inhibit --list
WHO     UID USER PID  COMM    WHAT     WHY                                        MODE
kubelet 0   root 4581 kubelet shutdown Kubelet needs time to handle node shutdown delay
```
Tail journal logs and then shutdown a node via systemctl reboot
or …
=> Configure Graceful Node Shutdown and lengthen max inhibitor delay

CHANGES.md, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/worker.yaml
* systemd adds "search ." to hosts `/run/systemd/resolve/resolv.conf` on hosts with a fqdn hostname
* Kubelet v1.25 began propagating `search .` from the host node into containers' `/etc/resolv.conf`
* musl-based DNS resolvers don't behave correctly when `search .` is used in their `/etc/resolv.conf`. This breaks Alpine images
* Adapt the same workaround used by Openshift to strip the `search .`
* This only applies to bare-metal Typhoon nodes (where hostnames are set to fqdn's), nodes on cloud platforms aren't affected in the Typhoon configuration
Kubernetes tracking issue: https://github.com/kubernetes/kubernetes/issues/112135
Rel:
* https://github.com/systemd/systemd/pull/17201
* https://github.com/kubernetes/kubernetes/pull/109441
* …
=> Add workaround to strip "search ." from resolv.conf

CHANGES.md, aws/fedora-coreos/kubernetes/workers/butane/worker.yaml, aws/flatcar-linux/kubernetes/workers/butane/worker.yaml, azure/fedora-coreos/kubernetes/workers/butane/worker.yaml, azure/flatcar-linux/kubernetes/workers/butane/worker.yaml, bare-metal/fedora-coreos/kubernetes/butane/worker.yaml, bare-metal/flatcar-linux/kubernetes/butane/worker.yaml, digital-ocean/fedora-coreos/kubernetes/butane/worker.yaml, digital-ocean/flatcar-linux/kubernetes/butane/worker.yaml, google-cloud/fedora-coreos/kubernetes/workers/butane/worker.yaml, google-cloud/flatcar-linux/kubernetes/workers/butane/worker.yaml
* Disable Kubelet Graceful Node Shutdown on worker nodes (enabled in Kubernetes v1.25.0 https://github.com/poseidon/typhoon/pull/1222)
* Fix Error/Completed pods accumulating whenever its node restarts (or auto-updates), visible in kubectl get pods
* Unfortunately, regular pods and the node are shutdown at the same time at the end of the 45s period without further configuration options
* In practice, enabling this feature causes Error or Completed pods to accumulate in kube-apiserver state until manually cleaned up
* This issue wasn't apparent in initial testing and seems to only affect non-critical pods (due to critical pods being killed earlier) But its very apparent on our clusters
* Using longer inhibitor times and longer max allowed systemd inhibitor times (e.g. 3min) doesn't change …
=> Revert Graceful Node Shutdown feature

CHANGES.md, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/fedora-coreos/kubernetes/workers/butane/worker.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/workers/butane/worker.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/workers/butane/worker.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/workers/butane/worker.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/worker.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/worker.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/worker.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/worker.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/butane/worker.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/workers/butane/worker.yaml
* LocalStorageCapacityIsolationFSQuotaMonitoring was reverted back to alpha in v1.25.1, so we don't need to explicitly disable it anymore
Rel: https://github.com/kubernetes/kubernetes/issues/112081
=> Remove workaround for v1.25.0 ConfigMap rendering issue

CHANGES.md, addons/grafana/deployment.yaml, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* Switch addon manifests to use the new Kubernetes image registry
Rel:
* https://github.com/poseidon/typhoon/pull/1206
* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#moved-container-registry-service-from-k8sgcrio-to-registryk8sio
=> Switch addons images from k8s.gcr.io to registry.k8s.io

docs/advanced/arm64.md
* Calico v3.22.0 introduced multi-arch container images so Typhoon's ARM64 support has allowed choosing Calico CNI since Typhoon v1.23.5
=> Remove note about not supporting ARM64 with Calico CNI

CHANGES.md, azure/flatcar-linux/kubernetes/controllers.tf, azure/flatcar-linux/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/workers/variables.tf, azure/flatcar-linux/kubernetes/workers/workers.tf, docs/advanced/worker-pools.md, docs/flatcar-linux/azure.md
* Switch from Azure Hypervisor generation 1 to generation 2
* Change default Azure `worker_type` from `Standard_DS1_v2` to `Standard_D2as_v5`
* Get 2 VCPU, 7 GiB, 12500 Mbps (vs 1 VCPU, 3.5GiB, 750 Mbps)
* Small increase in pay-as-you-go price ($53.29 -> $62.78)
* Small increase in spot price ($5.64/mo -> $7.37/mo)
* Change from Intel to AMD EPYC (`D2as_v5` cheaper than `D2s_v5`)
Notes: Azure makes you accept terms for each plan:
```
az vm image terms accept --publish kinvolk --offer flatcar-container-linux-free --plan stable-gen2
```
Rel:
* https://learn.microsoft.com/en-us/azure/virtual-machines/dasv5-dadsv5-series#dasv5-series
* https://learn.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series
=> Switch to Flatcar Azure gen2 images and change worker type

CHANGES.md, azure/fedora-coreos/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/workers/variables.tf, docs/fedora-coreos/azure.md
* Change default Azure worker_type from Standard_DS1_v2 to Standard_D2as_v5
* Get 2 VCPU, 7 GiB, 12500Mbps (vs 1 VCPU, 3.5GiB, 750 Mbps)
* Small increase in pay-as-you-go price ($53.29 -> $62.78)
* Small increase in spot price ($5.64/mo -> $7.37/mo)
* Change from Intel to AMD EPYC (`D2as_v5` cheaper than `D2s_v5`)
Rel:
* https://github.com/poseidon/typhoon/pull/1248
* https://learn.microsoft.com/en-us/azure/virtual-machines/dasv5-dadsv5-series#dasv5-series
* https://learn.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series
=> Switch Azure Fedora CoreOS default worker type

CHANGES.md, README.md, azure/flatcar-linux/kubernetes/controllers.tf, azure/flatcar-linux/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/workers.tf, azure/flatcar-linux/kubernetes/workers/variables.tf, azure/flatcar-linux/kubernetes/workers/workers.tf, docs/advanced/arm64.md, docs/index.md
* Kinvolk now publishes Flatcar Linux images for ARM64
* For now, amd64 image must specify a plan while arm64 images must NOT specify a plan due to how Kinvolk publishes.
Rel: https://github.com/flatcar/Flatcar/issues/872
=> Add Flatcar Linux ARM64 support on Azure

CHANGES.md, aws/fedora-coreos/kubernetes/workers/butane/worker.yaml, aws/flatcar-linux/kubernetes/workers/butane/worker.yaml, azure/fedora-coreos/kubernetes/workers/butane/worker.yaml, azure/flatcar-linux/kubernetes/workers/butane/worker.yaml, digital-ocean/fedora-coreos/kubernetes/butane/worker.yaml, digital-ocean/flatcar-linux/kubernetes/butane/worker.yaml, google-cloud/fedora-coreos/kubernetes/workers/butane/worker.yaml, google-cloud/flatcar-linux/kubernetes/workers/butane/worker.yaml
* `delete-node.service` used to be used to remove nodes from the cluster on shutdown, but its long since it last worked properly
* If there is still a desire for this concept, it can be added with a custom snippet and with a better systemd unit
=> Remove defunct delete-node.service from worker nodes

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/projectcalico/calico/releases/tag/v3.24.3
* Add patch to allow Kubelet kubeconfig to drain nodes if desired in addition to just deleting them in shutdown integrations. See https://github.com/poseidon/terraform-render-bootstrap/pull/330
=> Update Calico v3.24.2 to v3.24.3

CHANGES.md, aws/fedora-coreos/kubernetes/workers/butane/worker.yaml, aws/flatcar-linux/kubernetes/workers/butane/worker.yaml, azure/fedora-coreos/kubernetes/workers/butane/worker.yaml, azure/flatcar-linux/kubernetes/workers/butane/worker.yaml, bare-metal/fedora-coreos/kubernetes/butane/worker.yaml, bare-metal/flatcar-linux/kubernetes/butane/worker.yaml, digital-ocean/fedora-coreos/kubernetes/butane/worker.yaml, digital-ocean/flatcar-linux/kubernetes/butane/worker.yaml, google-cloud/fedora-coreos/kubernetes/workers/butane/worker.yaml, google-cloud/flatcar-linux/kubernetes/workers/butane/worker.yaml
* Kubelet GracefulNodeShutdown works, but only partially handles gracefully stopping the Kubelet. The most noticeable drawback is that Completed Pods are left around
* Use a project like poseidon/scuttle or a similar systemd unit as a snippet to add drain and/or delete behaviors if desired
* This reverts commit 1786e34f33779d93f96b0a4345a7b460e023c892.
Rel:    
* https://www.psdn.io/posts/kubelet-graceful-shutdown/
* https://github.com/poseidon/scuttle
Previous PRs:
* https://github.com/poseidon/typhoon/pull/1227
* https://github.com/poseidon/typhoon/pull/1222
=> Re-enable Graceful Node Shutdown feature

CHANGES.md, aws/fedora-coreos/kubernetes/controllers.tf, aws/fedora-coreos/kubernetes/workers/workers.tf, aws/flatcar-linux/kubernetes/controllers.tf, aws/flatcar-linux/kubernetes/workers/workers.tf
* Same features, but AWS will soon require launch templates
* Starting Dec 31, 2022 AWS will not add new instance types (e.g. graviton 4) to launch configuration support
Rel: https://aws.amazon.com/blogs/compute/amazon-ec2-auto-scaling-will-no-longer-add-support-for-new-ec2-features-to-launch-configurations/
=> Migrate AWS launch configurations to launch templates

CHANGES.md
* Terraform supports sourcing modules from either Git repos or from their own hosted Terraform Module Registry, introduced a few years ago
* Typhoon docs have always shown using Git-based module sources, not the Terraform Module Registry. For example, module usage should be `source = "git::https://github.com/poseidon/typhoon/...` not `source = poseidon/kubernetes/...`
* Typhoon published Flatcar Linux modules (CoreOS Container Linux at the time) to Terraform Module Registry, but the approach has a number of drawbacks for publishers and for users.
* Terraform's Module Registry requires subtree mirroring Typhoon to special terraform-platform-kubernetes repos. This distorts Git history, requires special automation, and the registry's naming requirements don't allow us to publish our full …
=> Update CHANGES to reiterate Terraform Module Registry deprecation

bare-metal/fedora-coreos/kubernetes/variables.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, docs/fedora-coreos/bare-metal.md, docs/flatcar-linux/bare-metal.md
* To accompany the restructure of the bare-metal modules to allow discrete workers to be defined and attached to a cluster (#1295), the `workers` variable (older way, used for defining homogeneous workers inline) should be optional and default to an empty list
Fix #1301
=> Change bare-metal workers variable to optional

.github/dependabot.yaml, CHANGES.md
* Small warning about Fedora CoreOS [issue](https://github.com/coreos/fedora-coreos-tracker/issues/1423) fix that hasn't made it to stable yet
=> Update CHANGES.md with release notes

aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Starting in Cilium v1.13.1, the cilium-cni plugin is installed via an init container rather than by the Cilium agent container
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/348
=> Update Cilium to use an init container to install CNI plugins

CHANGES.md, bare-metal/flatcar-linux/kubernetes/butane/install.yaml, bare-metal/flatcar-linux/kubernetes/profiles.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, bare-metal/flatcar-linux/kubernetes/worker/butane/install.yaml, bare-metal/flatcar-linux/kubernetes/worker/matchbox.tf, bare-metal/flatcar-linux/kubernetes/worker/variables.tf, bare-metal/flatcar-linux/kubernetes/workers.tf, docs/flatcar-linux/bare-metal.md
By exposing this parameter it is possible to install OEM specific software during the `flatcar-install` invocation.
I installed a Kubernetes cluster on vSphere VMs and used the newly exposed flag to install the vmware OEM files. Now vSphere no longer complains that the vSphere tools are not installed and it is possible to see the assigned hostname and IPs in the vSphere UI. This also enables the vSphere Terraform provider to wait for IP assignment.
When using `cached_install = true` Matchbox also needs to serve these files otherwise the `installer.service` fails:
```
https://${channel}.release.flatcar-linux.net/amd64-usr/${version}/flatcar_production_${oem_type}_image.bin.bz2
https://${channel}.release.flatcar-linux.net/amd64-usr/${version}/flatcar_production_${oem_type}_image.bin.bz2.sig …
```
=> Expose flatcar-install OEM parameter

bare-metal/flatcar-linux/kubernetes/butane/install.yaml, bare-metal/flatcar-linux/kubernetes/profiles.tf, bare-metal/flatcar-linux/kubernetes/worker/butane/install.yaml, bare-metal/flatcar-linux/kubernetes/worker/matchbox.tf
* The OEM parameter added in #1302 defaults to empty but results in a `-o` flag instead of a `-o ""` flag. This change omits the `-o` flag altogether unless `oem_type` is defined
Prior to this change, running in `terraform console`:
```
templatefile("${path.module}/butane/install.yaml", {os_channel = "", os_version = "", ignition_endpoint = "", mac = "", install_disk = "", ssh_authorized_key = "", oem_type = "", baseurl_flag = ""})
```
will demonstrate the `-o` flag being added with no argument
After this change, running in `terraform console`:
```
templatefile("${path.module}/butane/install.yaml", {os_channel = "", os_version = "", ignition_endpoint = "", mac = "", install_disk = "", ssh_authorized_key = "", oem_flag = "", baseurl_flag = ""})
``` …
=> Omit -o flag to flatcar-install unless oem_type is defined

.github/workflows/publish.yaml
* Use a shared GitHub Workflow to build the mkdocs site and publish to GitHub Pages (when the release-docs branch is updated)
=> Consolidate the mkdocs to GitHub Pages publish workflow

CHANGES.md, azure/flatcar-linux/kubernetes/controllers.tf, azure/flatcar-linux/kubernetes/workers/workers.tf
* When invalid Ignition snippets are provided to Typhoon, it can be useful to view Azure's boot logs for the instance, which requires boot diagnostics be enabled
* Also enable termination notices for use with poseidon/scuttle
=> Enable boot diagnostics for Azure controller and worker VMs

CHANGES.md, aws/fedora-coreos/kubernetes/versions.tf, aws/fedora-coreos/kubernetes/workers/versions.tf, aws/flatcar-linux/kubernetes/versions.tf, aws/flatcar-linux/kubernetes/workers/versions.tf
* aws provider v5.0+ works alright and should be permitted, relax the version constraint for the Typhoon AWS kubernetes module and worker module for Fedora CoreOS and Flatcar Linux
=> Relax aws Terraform Provider version constraint

CHANGES.md, azure/fedora-coreos/kubernetes/controllers.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/workers.tf, azure/fedora-coreos/kubernetes/workers/variables.tf, azure/fedora-coreos/kubernetes/workers/workers.tf, azure/flatcar-linux/kubernetes/controllers.tf, azure/flatcar-linux/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/workers.tf, azure/flatcar-linux/kubernetes/workers/variables.tf, azure/flatcar-linux/kubernetes/workers/workers.tf
* Allow passing a dummy RSA key to Azure to satisfy its obtuse requirements (recommend deleting the corresponding private key)
* Then `ssh_authorized_key` can be used to provide Fedora CoreOS or Flatcar Linux with a modern ed25519 public key to set in the authorized_keys via Ignition
Rel: https://github.com/Azure/AzureVM/issues/26
=> Workaround to allow use of ed25519 keys on Azure

bare-metal/flatcar-linux/kubernetes/outputs.tf
This PR adds the `kubeconfig` output to the bare-metal/flatcar-linux outputs.tf in order to fix support for separately defined worker modules.
Before this change, that functionality was broken as described in https://github.com/poseidon/typhoon/issues/1386
`terraform plan` using my patched outputs.tf completes.
rel: 1386
=> Update outputs.tf for bare-metal/flatcar-linux to include kubeconfig output

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* With Cilium v1.14, Cilium's kube-proxy partial mode changed to either be enabled or disabled (not partial). This somtimes leaves Cilium (and the host) unable to reach the kube-apiserver via the in-cluster Kubernetes Service IP, until the host is rebooted
* As a workaround, configure Cilium to rely on external DNS resolvers to find the IP address of the apiserver. This is less portable and less "clean" than using in-cluster discovery, but also what Cilium wants users to do. Revert this when the upstream issue https://github.com/cilium/cilium/issues/27982 is resolved
=> Workaround problems in Cilium v1.14 partial kube-proxy replacement

CHANGES.md, google-cloud/fedora-coreos/kubernetes/versions.tf, google-cloud/fedora-coreos/kubernetes/workers/versions.tf, google-cloud/flatcar-linux/kubernetes/versions.tf, google-cloud/flatcar-linux/kubernetes/workers/versions.tf
* Allow upgrading to the v5.x Google Cloud Terrform Provider
* Relax the version constraint to ease future compatibility, though it does allow users to upgrade prematurely
=> Relax the provider version constraint for Google Cloud

addons/nginx-ingress/google-cloud/rbac/cluster-role.yaml
When deployed to GCP I hit this issue;
k8s.io/client-go@v0.25.3/tools/cache/reflector.go:169: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:ingress:default" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope 
I added the extra cluster rbacs to the ingress class and all seems to now work.
I deployed on GCP and was able to route ingress traffic to a contianer in the cluster.
=> Fix/Ingress on gcp doesnt work by default.

aws/fedora-coreos/kubernetes/workers/workers.tf, aws/flatcar-linux/kubernetes/workers/workers.tf
* AWS has recently started defaulting launch templates to IMDSv2 being "required". aws_launch_template is supposed to default to "optional" but it doesn't.
* Requiring IMDSv2 sessions breaks a number of applications which don't use AWS SDKs and were never meant to be complex applications (e.g. shell scripts and the like)
=> Fix AWS launch template to retain support for IMDVv1

CHANGES.md, README.md, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml
* Set CNI networking to "none" to skip installing any CNI provider (i.e. no flannel, Calico, or Cilium). In this mode, cluster nodes will be NotReady until you add your own CNI stack
* Motivation: I now tend to manage CNI components as addon modules just like other applications overlaid onto a cluster. It allows for faster iteration and may eventually become the recommendation
=> Allow CNI networking to be set to none

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/variables.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/variables.tf
* When `true`, the chosen container `networking` provider is installed during cluster bootstrap
* Set `false` to self-manage the container networking provider. This allows flannel, Calico, or Cilium to be managed via Terraform (like any other Kubernetes resources). Nodes will be NotReady until you apply the self-managed container networking provider. This may become the default in future.
=> Add an `install_container_networking` variable (default `true`)

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Update fixes Calico incompatibility with Fedora CoreOS
Rel: https://github.com/projectcalico/calico/issues/8372
=> Update Calico from v3.26.3 to v3.27.2

CHANGES.md, aws/fedora-coreos/kubernetes/security.tf, aws/flatcar-linux/kubernetes/security.tf, azure/fedora-coreos/kubernetes/security.tf, azure/flatcar-linux/kubernetes/security.tf, digital-ocean/fedora-coreos/kubernetes/network.tf, digital-ocean/flatcar-linux/kubernetes/network.tf, google-cloud/fedora-coreos/kubernetes/network.tf, google-cloud/flatcar-linux/kubernetes/network.tf
* Add firewall or security riles to allow node-to-node traffic on ports 9962-9965 for Cilium and Hubble metrics. Cilium runs with host network, so these require cloud firewall changes
=> Add firewall and security rules for Cilium/Hubble metrics

CHANGES.md, azure/fedora-coreos/kubernetes/outputs.tf, azure/flatcar-linux/kubernetes/outputs.tf, docs/architecture/azure.md
* Output the network security group name and address prefixes for controller nodes, to allow adding custom network security rules that apply specifically to controller nodes
=> azure: Add controller security group and subnet outputs

CHANGES.md, README.md, addons/cilium/cluster-role-binding.tf, addons/cilium/cluster-role.tf, addons/cilium/config.tf, addons/cilium/daemonset.tf, addons/cilium/deployment.tf, addons/cilium/service-account.tf, addons/cilium/variables.tf, addons/cilium/versions.tf, addons/coredns/cluster-role.tf, addons/coredns/config.tf, addons/coredns/deployment.tf, addons/coredns/service-account.tf, addons/coredns/service.tf, addons/coredns/variables.tf, addons/coredns/versions.tf, addons/flannel/cluster-role-binding.tf, addons/flannel/cluster-role.tf, addons/flannel/config.tf, addons/flannel/daemonset.tf, addons/flannel/service-account.tf, addons/flannel/variables.tf, addons/flannel/versions.tf
* With the new component system, these components can be managed independent from the cluster and rolled or edited in advanced ways
=> Add Terraform modules for CoreDNS, Cilium, and flannel

CHANGES.md, azure/fedora-coreos/kubernetes/controllers.tf, azure/fedora-coreos/kubernetes/lb.tf, azure/fedora-coreos/kubernetes/locals.tf, azure/fedora-coreos/kubernetes/network.tf, azure/fedora-coreos/kubernetes/outputs.tf, azure/fedora-coreos/kubernetes/security.tf, azure/fedora-coreos/kubernetes/ssh.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/workers.tf, azure/fedora-coreos/kubernetes/workers/variables.tf, azure/fedora-coreos/kubernetes/workers/workers.tf, azure/flatcar-linux/kubernetes/controllers.tf, azure/flatcar-linux/kubernetes/lb.tf, azure/flatcar-linux/kubernetes/locals.tf, azure/flatcar-linux/kubernetes/network.tf, azure/flatcar-linux/kubernetes/outputs.tf, azure/flatcar-linux/kubernetes/security.tf, azure/flatcar-linux/kubernetes/ssh.tf, azure/flatcar-linux/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/workers.tf, azure/flatcar-linux/kubernetes/workers/variables.tf, azure/flatcar-linux/kubernetes/workers/workers.tf, docs/addons/ingress.md, docs/advanced/worker-pools.md, docs/architecture/azure.md, docs/fedora-coreos/azure.md, docs/flatcar-linux/azure.md
* Define a dual-stack virtual network with both IPv4 and IPv6 private address space. Change `host_cidr` variable (string) to a `network_cidr` variable (object) with "ipv4" and "ipv6" fields that list CIDR strings.
* Define dual-stack controller and worker subnets. Disable Azure default outbound access (a deprecated fallback mechanism)
* Enable dual-stack load balancing to Kubernetes Ingress by adding a public IPv6 frontend IP and LB rule to the load balancer.
* Enable worker outbound IPv6 connectivity through load balancer SNAT by adding an IPv6 frontend IP and outbound rule
* Configure controller nodes with a public IPv6 address to provide direct outbound IPv6 connectivity
* Add an IPv6 worker backend pool. Azure requires separate IPv4 and IPv6 backend pools, though the health probe can …
=> Add IPv6 support for Typhoon Azure clusters

CHANGES.md, azure/fedora-coreos/kubernetes/controllers.tf, azure/fedora-coreos/kubernetes/lb.tf, azure/fedora-coreos/kubernetes/network.tf, azure/fedora-coreos/kubernetes/outputs.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/workers.tf, azure/fedora-coreos/kubernetes/workers/variables.tf, azure/fedora-coreos/kubernetes/workers/workers.tf, azure/flatcar-linux/kubernetes/controllers.tf, azure/flatcar-linux/kubernetes/lb.tf, azure/flatcar-linux/kubernetes/network.tf, azure/flatcar-linux/kubernetes/outputs.tf, azure/flatcar-linux/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/workers.tf, azure/flatcar-linux/kubernetes/workers/variables.tf, azure/flatcar-linux/kubernetes/workers/workers.tf, docs/advanced/arm64.md, docs/advanced/worker-pools.md, docs/fedora-coreos/azure.md, docs/flatcar-linux/azure.md
* Rename the region variable to location to align with Azure platform conventions, where resources are created within an Azure location, which are themselves part of broader geographical regions
=> Rename Azure cluster region variable to location

CHANGES.md, azure/fedora-coreos/kubernetes/controllers.tf, azure/fedora-coreos/kubernetes/lb.tf, azure/fedora-coreos/kubernetes/outputs.tf, azure/flatcar-linux/kubernetes/controllers.tf, azure/flatcar-linux/kubernetes/lb.tf, azure/flatcar-linux/kubernetes/outputs.tf
* Consolidate load balancer frontend IPs to just the minimal IPv4 and IPv6 addresses that are needed per load balancer. apiserver and ingress use separate ports, so there is not a true need for a separate public IPv4 address just for apiserver
* Some might prefer a separate IP just because it slightly hides the apiserver, but these are public hosted endpoints that can be discovered
* Reduce the cost of an Azure cluster since IPv4 public IPs are billed ($3.60/mo/cluster)
=> Remove an IPv4 address from Azure clusters

azure/fedora-coreos/kubernetes/network.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/network.tf, azure/flatcar-linux/kubernetes/variables.tf
* Private IPv6 address space should be assigned randomly within an organization per https://datatracker.ietf.org/doc/html/rfc4193
=> Generate Azure Virtual Network IPv6 ULA space at random

CHANGES.md, aws/fedora-coreos/kubernetes/controllers.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers.tf, aws/fedora-coreos/kubernetes/workers/variables.tf, aws/fedora-coreos/kubernetes/workers/workers.tf, aws/flatcar-linux/kubernetes/controllers.tf, aws/flatcar-linux/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/workers.tf, aws/flatcar-linux/kubernetes/workers/variables.tf, aws/flatcar-linux/kubernetes/workers/workers.tf
* Add `controller_disk_type`, `controller_disk_size`, and `controller_disk_iops` variables
* Add `worker_disk_type`, `worker_disk_size`, and `worker_disk_iops` variables and fix propagation to worker nodes
* Remove `disk_type`, `disk_size`, and `disk_iops` variables
* Add `controller_cpu_credits` and `worker_cpu_credits` variables to set CPU pricing mode for burstable instance types
=> Add CPU credits variable to control burst mode

CHANGES.md, aws/fedora-coreos/kubernetes/ami.tf, aws/fedora-coreos/kubernetes/controllers.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers.tf, aws/flatcar-linux/kubernetes/ami.tf, aws/flatcar-linux/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/workers.tf, azure/flatcar-linux/kubernetes/controllers.tf, azure/flatcar-linux/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/workers.tf
* On platforms that support ARM64 instances, configure controller and worker node host architectures separately
* For example, you can run arm64 controllers and amd64 workers
* Add `controller_arch` and `worker_arch` variables
* Remove `arch` variable
=> Configure controller and worker node architecture separately

CHANGES.md, docs/advanced/arm64.md
* Typhoon now supports arbitrary combinations of controller, worker, and worker pool architectures so we can drop the specific details of full-cluster vs hybrid cluster. Just pick the architecture for each group of nodes accordingly.
* However, if a custom node taint is set, continue to configure the cluster's daemonsets accordingly with `daemonset_tolerations`
=> Update ARM64 cluster and hybrid cluster docs

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/variables.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/variables.tf
* Set reasonable values and remove some variable clutter
* enable_reporting is only used with Calico and we can just default to false, I doubt anyone uses Calico and cares much about reporting metrics to upstream Calico
=> Remove some seldom used variables and set reasonable values

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Update the CoreDNS and Cilium versons used by default when folks aren't managing the components themselves
=> Update default Cilium and CoreDNS components

CHANGES.md, aws/fedora-coreos/kubernetes/controllers.tf, aws/fedora-coreos/kubernetes/network.tf, aws/fedora-coreos/kubernetes/workers/workers.tf, aws/flatcar-linux/kubernetes/controllers.tf, aws/flatcar-linux/kubernetes/network.tf, aws/flatcar-linux/kubernetes/workers/workers.tf
* Use EC2 resource-based hostnames instead of IP-based hostnames. The Amazon DNS server can resolve A and AAAA queries to IPv4 and IPv6 node addresses
* For example, nodes used to be named like `ip-10-11-12-13.us-east-1.compute.internal` but going forward use the instance id `i-0123456789abcdef.us-east-1.compute.internal`
* Tag controller node EBS volumes with a name based on the controller node name
=> aws: Switch EC2 instances to use resource-based hostnames

CHANGES.md, addons/cilium/config.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/workers/workers.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* When using the Cilium component, disable bootstrapping the kube-proxy DaemonSet. Instead, configure Cilium to provide its kube-proxy replacement with BPF
* Update the self-managed Cilium component to use kube-proxy replacement as well
=> Use Cilium kube-proxy replacement when Cilium CNI is used

azure/fedora-coreos/kubernetes/versions.tf, azure/fedora-coreos/kubernetes/workers/versions.tf, azure/flatcar-linux/kubernetes/versions.tf, azure/flatcar-linux/kubernetes/workers/versions.tf
* Allow folks to start upgrading to azurerm provider v4.0.0, don't set an upper bound on versions going forward
=> Remove upper bound on azurerm provider version

CHANGES.md, google-cloud/fedora-coreos/kubernetes/workers/workers.tf, google-cloud/flatcar-linux/kubernetes/workers/workers.tf
* Use regional instance templates for the worker node regional managed instance groups. Regional instance templates are kept in the associated region, whereas the older "global" instance templates were kept in a particular region (regardless of where the MIG region) so outages in a region X could affect clusters in a region Y which is undesired
=> google: Use regional instance templates for workers

CHANGES.md, google-cloud/fedora-coreos/kubernetes/workers/workers.tf, google-cloud/flatcar-linux/kubernetes/workers/workers.tf
* Configure the regional worker instance templates with the region of the cluster. This defaults to the provider's region which isn't always what you want and if left off causes an error
* Close #1512
=> Add region to gcp instance template resource

addons/nginx-ingress/aws/rbac/cluster-role.yaml, addons/nginx-ingress/azure/rbac/cluster-role.yaml, addons/nginx-ingress/bare-metal/rbac/cluster-role.yaml, addons/nginx-ingress/bare-metal/service.yaml, addons/nginx-ingress/digital-ocean/rbac/cluster-role.yaml, addons/nginx-ingress/google-cloud/rbac/cluster-role.yaml
This extends #1409 to all other platforms + fixes the selector for bare-metal deployments. 
I've only validated the necessary rbac role on bare-metal, but I think it's fair to assume that it applies to nginx on all other platforms too. Happy to remove the unvalidated fixes though if you'd rather not merge them.
=> Fix nginx addon (service selector on bare-metal, rbac for all except gcp)

mkdocs.yml
* Add a mkdocs-material palette switcher to switch between light and dark modes, or automatically set the mode based on system preference
=> docs: Add support for dark mode and auto mode

addons/cilium/variables.tf, addons/flannel/variables.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, digital-ocean/fedora-coreos/kubernetes/variables.tf, digital-ocean/flatcar-linux/kubernetes/variables.tf, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/bare-metal.md, docs/flatcar-linux/digitalocean.md, docs/flatcar-linux/google-cloud.md, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/variables.tf
* Change the default Pod CIDR from `10.2.0.0/16` to `10.20.0.0/14` (10.20.0.0 - 10.23.255.255) to support 1024 nodes by default
* Most CNI providers divide the Pod CIDR so that each node has a `/24` to allocate to local pods (256). The previous `10.2.0.0/16` default only fits 256 /24's so 256 nodes were supported without customizing the pod_cidr
=> Change the default Pod CIDR to 10.20.0.0/14

CHANGES.md, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/fedora-coreos/kubernetes/workers/butane/worker.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/workers/butane/worker.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/workers/butane/worker.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/workers/butane/worker.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/worker/butane/worker.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/worker/butane/worker.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/worker.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/worker.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/butane/worker.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/workers/butane/worker.yaml
* By default, Kubelet will pull container images one by one (in series), which is mostly related to Docker-era bugs in parallel image pulls. These days we use containerd so parallel pulls should be fine
* Serial image pulls are undesirable because one slow registry or image can cause other image pulls to wait. Parallel image pulls ensure only large images / slow registries see that impact
Docs: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
=> Configure Kubelets for parallel image pulls

CHANGES.md, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/fedora-coreos/kubernetes/workers/butane/worker.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/workers/butane/worker.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/worker/butane/worker.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/worker.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/butane/worker.yaml
* Explicitly load the `nf_conntrack` and `br_netfilter` kernel modules to support flannel setups
* Flannel requires hosts have the `br_netfilter` kernel module loaded
* `kube-proxy` is still used when flannel is chosen, and it requires `nf_conntrack` module be loaded
=> Load nf_conntrack and br_netfilter for flannel

aws/fedora-coreos/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, digital-ocean/fedora-coreos/kubernetes/variables.tf, digital-ocean/flatcar-linux/kubernetes/variables.tf, docs/addons/overview.md, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/variables.tf
* Calico is no longer supported, so enabling or disabling the component does nothing. Remove the field from components
=> Remove calico from component configuration

CHANGES.md, addons/flannel/config.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/security.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/security.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/security.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/security.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/network.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/network.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/network.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/network.tf
* flannel and Cilium default to UDP 8472 for VXLAN traffic to avoid conflicts with other VXLAN usage (e.g. Open vSwith)
* Aligning flannel and Cilium to use the same vxlan port makes firewall rules or security policies simpler across clouds
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/403
=> Change flannel port from 4789 to 8472

CHANGES.md, azure/fedora-coreos/kubernetes/lb.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/lb.tf, azure/flatcar-linux/kubernetes/variables.tf
* Azure Load Balancers include 5 rules (e.g. 3 LB rules, 2 outbound), whether used or not (~$18/mo)
* [#1468](https://github.com/poseidon/typhoon/pull/1468) added 3 LB rules to support IPv6 load balancing, raising the rules count from 5 to 8 and added ~$21/mo to the cost of the load balancer
* I noticed this because my load balancing costs were up for the last few months. The gotcha is that outbound rules count toward the 5 rules included with the base cost of the LB (~$18/mo)
Docs: https://azure.microsoft.com/en-us/pricing/details/load-balancer/
=> azure: Add `enable_ipv6_load_balancing` variable and default false

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/variables.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/variables.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/variables.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/variables.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/variables.tf
* Allow the service account token issuer to be adjusted or served from a public bucket or static cache
Docs: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/405
=> Add service_account_issuer variable for kube-apiserver

CHANGES.md, bare-metal/fedora-coreos/kubernetes/profiles.tf
* Fedora CoreOS 42 seems to have slightly changed the kernel image's name (a dash was changed to a dot), which can cause iPXE booting to fail
=> Fix Fedora CoreOS kernel URL for metal iPXE booting

CHANGES.md, google-cloud/fedora-coreos/kubernetes/apiserver.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/ingress.tf, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/apiserver.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/ingress.tf, google-cloud/flatcar-linux/kubernetes/variables.tf
* Update Google Cloud TCP proxies from classic to current
* Google Cloud TCP proxies no longer restrict which frontend ports may be used
* Switch apiserver to listen on 6443 to match other cloud platforms
* Switch the HTTP (port 80) proxy to a TCP proxy to match what's done for HTTPS traffic to ingress/gateway controllers
* Add a variable `enable_http_lb` to make TCP/80 IPv4/IPv6 forwarding rules optional. Default to false. Google Cloud charges by forwarding rule, so dropping support for plaintext http traffic can save costs. And if you front traffic with global load balancer providers, you may handle http->https redirects there anyway, so there's no loss
=> Modernize Google Cloud load balancer setups

CHANGES.md, azure/fedora-coreos/kubernetes/lb.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/lb.tf, azure/flatcar-linux/kubernetes/variables.tf
* Azure Load Balancers charge by load balancer rues (5 included) so its useful to provide ways to stay under that number, either by dropping support for port 80 traffic or IPv6 traffic. When using global proxies, you can usually serve IPv6 or http->https redirects separately anyway
=> Add enable_http_load_balancing variable to Azure clusters

CHANGES.md, azure/fedora-coreos/kubernetes/lb.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/workers/workers.tf, azure/flatcar-linux/kubernetes/lb.tf, azure/flatcar-linux/kubernetes/variables.tf, azure/flatcar-linux/kubernetes/workers/workers.tf, docs/topics/maintenance.md
* Set a rolling upgrade policy so that changes to the worker node pool are rolled out gradually. Previously, the VMSS model could change, but instances would not receive it until manually replaced
* Align Azure node pool behaviors more closely with AWS and GCP:
* On AWS, worker instance template changes trigger an instance refresh
* On GCP, worker instance template changes roll out via proactive
* Define Azure automatic instance repair using Application Health Extension probes to 10256 (kube-proxy or Cilium equivalent) to match the strategy used on Google Cloud
=> Set Azure VMSS upgrade policy to Rolling

CHANGES.md, aws/fedora-coreos/kubernetes/nlb.tf, aws/fedora-coreos/kubernetes/security.tf, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers.tf, aws/fedora-coreos/kubernetes/workers/variables.tf, aws/fedora-coreos/kubernetes/workers/workers.tf, aws/flatcar-linux/kubernetes/nlb.tf, aws/flatcar-linux/kubernetes/security.tf, aws/flatcar-linux/kubernetes/variables.tf, aws/flatcar-linux/kubernetes/workers.tf, aws/flatcar-linux/kubernetes/workers/variables.tf, aws/flatcar-linux/kubernetes/workers/workers.tf
* AWS IPv4 address pricing is quite high compared to other clouds, and an NLB unavoidably uses at least 3.
* Unlike Azure's nice outbound through LB options, AWS has only NAT options which are even more costly than IPv4 in budget clusters. Another option is to simply forget about accessing nodes via IPv4 or outbound IPv4 internet access (tradeoff: GitHub is a notable website that only serves via IPv4, so cut ties)
=> [aws] Add option for using only IPv6 public addresses

CHANGES.md, bare-metal/fedora-coreos/kubernetes/worker/matchbox.tf
* Similar to https://github.com/poseidon/typhoon/pull/1602, but for those who use the standalone worker module directly
* Closes #1624
=> Fix Fedora CoreOS kernel image URL/name in worker module
