README.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/network.tf, google-cloud/container-linux/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/workers/cl/worker.yaml.tmpl
Running in two colocations, GCE, and Digital Ocean. Migrated all workloads.
=> Update Kubernetes from v1.7.1 to v1.7.3

README.md, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, docs/bare-metal.md, docs/concepts.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, google-cloud/container-linux/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/workers/cl/worker.yaml.tmpl
Update hyperkube to v1.7.5_coreos.0
Update etcd-operator to v0.5.0
Update pod-checkpointer
Update flannel-cni to v0.2.0
Change etcd-operator TPR to CRD
Testing:
* Working on all platforms.
rel: https://github.com/poseidon/bootkube-terraform/pull/11
=> Update Kubernetes from v1.7.3 to v1.7.5

bare-metal/container-linux/kubernetes/variables.tf, docs/bare-metal.md, docs/google-cloud.md, google-cloud/container-linux/kubernetes/variables.tf
* Switch networking default from flannel to calico
Details in #14
=> Change bare-metal and GCE networking default to calico

digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/container-linux/kubernetes/ssh.tf, digital-ocean/container-linux/kubernetes/workers.tf
* Keep `kubeconfig` out of DigitalOcean metadata user-data
=> digital-ocean: Distribute kubeconfig via Terraform null_resource

aws/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
* Network policy [improvements](https://github.com/projectcalico/calico/releases/tag/v2.6.0)
* Update cni sidecar image from v1.10.0 to v1.11.0
* Lower log level in Calico CNI config from debug to info
=> Update from Calico v2.5.1 to v2.6.1

aws/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
* https://security.googleblog.com/2017/10/behind-masq-yet-more-dns-and-dhcp.html
* Quick verification on each platform
=> Update kube-dns image to address dnsmasq vulnerability

CHANGES.md, README.md, aws/container-linux/kubernetes/README.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/README.md, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, docs/aws.md, docs/bare-metal.md, docs/concepts.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
* Update from bootkube v0.6.2 to v0.7.0
* Use renamed module [terraform-render-bootkube](https://github.com/poseidon/terraform-render-bootkube). Renamed from bootkube-terraform to meet Terraform Module requirements.
=> Update Kubernetes from v1.7.5 to v1.7.7

docs/google-cloud.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
Followup to #33 
rel: https://github.com/kubernetes-incubator/bootkube/issues/740
=> Update Google Cloud Kubernetes from v1.7.7 to v1.8.1

bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl
* Kubelet will search path for flexvolume plugins
rel: #57
=> Add kubelet --volume-plugin-dir flag on bare-metal

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl
* https://github.com/coreos/etcd/releases/tag/v3.2.14
=> Update etcd from 3.2.13 to 3.2.14

README.md, docs/index.md
* Typhoon remains independently maintained. Its goals remain unchanged.
=> Update author's employment disclosure

CHANGES.md, README.md, aws/container-linux/kubernetes/README.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, bare-metal/container-linux/pxe-worker/cl/bootkube-worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/README.md, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, docs/aws.md, docs/bare-metal.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, docs/topics/maintenance.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
* Add flannel service account and limited RBAC cluster role
* Change DaemonSets to tolerate NoSchedule and NoExecute taints
* Remove deprecated apiserver --etcd-quorum-read flag
* Update Calico from v3.0.1 to v3.0.2
* Add Calico GlobalNetworkSet CRD
* https://github.com/poseidon/terraform-render-bootkube/pull/44
=> Update Kubernetes from v1.9.2 to v1.9.3

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl
* Minor bootkube manifest bumps as well
=> Update etcd from v3.2.15 to v3.3.1

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/cl/worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
* Set Kubelet search path for flexvolume plugins to `/var/lib/kubelet/volumeplugins`
* Add support for flexvolume plugins on AWS, GCE, and DO
* See #61 which added flexvolume support for bare-metal
rel: #61
=> Add kubelet --volume-plugin-dir flag

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl
* https://github.com/coreos/etcd/releases/tag/v3.3.2
=> Update etcd from v3.3.1 to v3.3.2

README.md, aws/container-linux/kubernetes/README.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/README.md, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, docs/advanced/worker-pools.md, docs/aws.md, docs/bare-metal.md, docs/digital-ocean.md, docs/google-cloud.md, docs/index.md, docs/topics/maintenance.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/controllers/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
* Update Kubernetes from v1.9.6 to v1.10.0
* Update control plane manifests https://github.com/poseidon/terraform-render-bootkube/pull/50
* https://github.com/kubernetes/kubernetes/issues/61750
=> Update Kubernetes from v1.9.6 to v1.10.x

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/container-linux/kubernetes/workers/cl/worker.yaml.tmpl, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/worker.yaml.tmpl, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/worker.yaml.tmpl, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml.tmpl
* https://github.com/projectcalico/calico/releases/tag/v3.1.1
* https://github.com/projectcalico/calico/releases/tag/v3.1.0
* https://github.com/poseidon/terraform-render-bootkube/pull/56
=> Update Calico from v3.0.4 to v3.1.1

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl
* https://github.com/coreos/etcd/releases/tag/v3.3.4
=> Update etcd from v3.3.3 to v3.3.4

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v5.1.1
* https://github.com/grafana/grafana/releases/tag/v5.1.0
=> Update Grafana from v5.0.4 to v5.1.1

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl
* https://github.com/coreos/etcd/releases/tag/v3.3.5
=> Update etcd from v3.3.4 to v3.3.5

CHANGES.md, addons/nginx-ingress/aws/service.yaml, addons/nginx-ingress/digital-ocean/service.yaml, addons/nginx-ingress/google-cloud/service.yaml, google-cloud/container-linux/kubernetes/network.tf, google-cloud/fedora-atomic/kubernetes/network.tf
* Add Google Cloud firewall rule to allow worker to worker access to health and metrics
=> Annotate nginx-ingress addon for Prometheus auto-discovery

CHANGES.md, bare-metal/container-linux/kubernetes/ssh.tf, bare-metal/fedora-atomic/kubernetes/ssh.tf
=> Fix possible deadlock for provisioning bare-metal clusters

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.16.2
* https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md
=> Update Nginx Ingress controller from 0.15.0 to 0.16.2

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl
* https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md#v3310-2018-10-10
=> Update etcd from v3.3.9 to v3.3.10

aws/container-linux/kubernetes/controllers.tf, aws/container-linux/kubernetes/workers/workers.tf, azure/container-linux/kubernetes/require.tf, azure/container-linux/kubernetes/workers/workers.tf, digital-ocean/container-linux/kubernetes/controllers.tf, digital-ocean/container-linux/kubernetes/workers.tf
Fix minor naming and commenting inconsistencies for data sources across platforms. This change should not impact functionality.
=> Fix minor data source naming inconsistencies

CHANGES.md, azure/container-linux/kubernetes/workers/workers.tf
* Required by terraform-provider-azurerm v1.17+
* https://github.com/terraform-providers/terraform-provider-azurerm/pull/2035
=> Add primary field to ip_configuration required by Azure

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl
* https://github.com/kubernetes-incubator/bootkube/releases/tag/v0.14.0
=> Update bootkube image version from v0.13.0 to v0.14.0

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* https://coredns.io/2019/01/13/coredns-1.3.1-release/
=> Update CoreDNS from v1.3.0 to v1.3.1

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* https://github.com/coreos/flannel/releases/tag/v0.11.0
=> Update flannel from v0.10.0 to v0.11.0

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, digital-ocean/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/fedora-atomic/kubernetes/cloudinit/controller.yaml.tmpl
* https://github.com/etcd-io/etcd/releases/tag/v3.3.12
=> Update etcd from v3.3.11 to v3.3.12

CHANGES.md, addons/grafana/config.yaml, addons/grafana/datasources.yaml, addons/grafana/deployment.yaml, addons/grafana/providers.yaml
* Upgrade Grafana from v5.4.3 to v6.0.0-beta2
* Enable Grafana Explore UI while still using only the Viewer role (inspect/edit without saving)
* http://docs.grafana.org/guides/whats-new-in-v6-0/
=> Upgrade Grafana to v6.0.0-beta2 and enable Explore UI

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* https://github.com/poseidon/terraform-render-bootkube/pull/115
=> Add a readiness probe to CoreDNS

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* https://docs.projectcalico.org/v3.5/releases/
=> Update Calico from v3.5.1 to v3.5.2

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v6.0.0
* http://docs.grafana.org/guides/whats-new-in-v6-0/
=> Update Grafana from v6.0.0-beta3 to v6.0.0

docs/topics/hardware.md
* Show creation of a PXE-enabled network boot environment when using dnsmasq as the DHCP server
* Recommend TFTP be served from /config/tftpboot since /config is preserved between firmware upgrades
* Recommend compiling undionly.kpxe from source to enable TLS features
* Add a note that equal-cost multi-path service IP routing (e.g. for ingress) requires EdgeOS v2.0. Previously, it was known that TLS handshakes couldn't be completed with packet balacing.
I've verified this is no longer the case when using the v2.0 EdgeOS firmware, ECMP works as expected.
=> Update documentation for use with Ubiquiti EdgeOS

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.8.0
=> Update Prometheus from v2.7.2 to v2.8.0

CHANGES.md, addons/grafana/dashboards-etcd.yaml, addons/grafana/dashboards-k8s.yaml, addons/grafana/deployment.yaml, addons/prometheus/rules.yaml
* Refresh rules and dashboards from upstreams
* Organize dashboards and stay below the ConfigMap size limit
=> Refresh Prometheus rules and Grafana dashboards

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* https://docs.projectcalico.org/v3.6/release-notes/
=> Update Calico from v3.6.0 to v3.6.1

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v6.1.0
=> Update Grafana from v6.0.2 to v6.1.0

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.24.1
* https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.24.0
=> Update nginx-ingress from v0.23.0 to v0.24.1

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v6.1.6
=> Update Grafana from v6.1.4 to v6.1.6

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* https://docs.projectcalico.org/v3.7/release-notes/
* https://github.com/poseidon/terraform-render-bootkube/pull/131
=> Upgrade Calico from v3.6.1 to v3.7.0

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/container-linux/kubernetes/security.tf, aws/fedora-atomic/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/security.tf, azure/container-linux/kubernetes/bootkube.tf, azure/container-linux/kubernetes/security.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/network.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/network.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/network.tf
* Change flannel port from the kernel default 8472 to the IANA assigned VXLAN port 4789
* Update firewall rules or security groups for VXLAN
* Why now? Calico now offers its own VXLAN backend so standardizing on the IANA port will simplify config
* https://github.com/coreos/flannel/blob/master/Documentation/backends.md#vxlan
=> Change flannel port from 8472 to 4789

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* https://docs.projectcalico.org/v3.7/release-notes/
=> Update Calico from v3.7.0 to v3.7.2

CHANGES.md, addons/prometheus/exporters/node-exporter/daemonset.yaml
* https://github.com/prometheus/node_exporter/releases/tag/v0.18.0
=> Update node_exporter from v0.17.0 to v0.18.0

addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* Rel: https://github.com/kubernetes/kubernetes/pull/78397
=> Update addon-resizer base image to distroless

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-atomic/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-atomic/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, digital-ocean/fedora-atomic/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf, google-cloud/fedora-atomic/kubernetes/bootkube.tf
* https://docs.projectcalico.org/v3.7/release-notes/
=> Update Calico from v3.7.2 to v3.7.3

README.md
* [DigitalOcean](https://www.digitalocean.com/) kindly provides credits to support Typhoon test clusters. Many thanks!
=> Acknowledge DigitalOcean providing credits for test clusters

README.md
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>
=> README.md: fix link to azure module

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
* https://docs.projectcalico.org/v3.7/release-notes/
Rel: https://github.com/poseidon/terraform-render-bootkube/pull/140
=> Update Calico from v3.7.3 to v3.7.4

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
* Enable CNI bandwidth plugin for traffic shaping
* https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#support-traffic-shaping
Rel: https://github.com/poseidon/terraform-render-bootkube/pull/143
=> Upgrade Calico from v3.7.4 to v3.8.0

CHANGES.md, addons/grafana/dashboards-etcd.yaml, addons/grafana/dashboards-k8s-nodes.yaml, addons/grafana/dashboards-k8s-resources.yaml, addons/grafana/dashboards-prom.yaml, addons/grafana/deployment.yaml, addons/prometheus/rules.yaml
* Refresh rules, alerts, and dashboards from upstreams
=> Refresh Prometheus rules/alerts and Grafana dashboards

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-coreos/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-coreos/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
* https://docs.projectcalico.org/v3.8/release-notes/
=> Update Calico from v3.8.0 to v3.8.1

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl
* https://github.com/etcd-io/etcd/releases/tag/v3.3.14
=> Update etcd from v3.3.13 to v3.3.14

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl
* https://github.com/etcd-io/etcd/releases/tag/v3.4.0
=> Update etcd from v3.3.15 to v3.4.0

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl
* https://github.com/etcd-io/etcd/releases/tag/v3.4.1
=> Update etcd from v3.4.0 to v3.4.1

CHANGES.md, aws/container-linux/kubernetes/bootkube.tf, aws/fedora-coreos/kubernetes/bootkube.tf, azure/container-linux/kubernetes/bootkube.tf, bare-metal/container-linux/kubernetes/bootkube.tf, bare-metal/fedora-coreos/kubernetes/bootkube.tf, digital-ocean/container-linux/kubernetes/bootkube.tf, google-cloud/container-linux/kubernetes/bootkube.tf
* https://docs.projectcalico.org/v3.9/release-notes/
=> Update Calico from v3.8.2 to v3.9.1

CHANGES.md, digital-ocean/container-linux/kubernetes/variables.tf, docs/cl/azure.md, docs/cl/digital-ocean.md
* Review variables available in DigitalOcean kubernetes module and sync with documentation
* Promote Calico for DigitalOcean and Azure beyond experimental (its the primary mode I've used since it was introduced)
=> Add stricter types for DigitalOcean module

CHANGES.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/bare-metal.md, requirements.txt
* Update mkdocs-material from v4.4.2 to v4.4.3
* Update recommended Terraform provider versions
* Cleanup the changelog before release
=> Update docs, CHANGES, and mkdocs-material

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml.tmpl, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml.tmpl, google-cloud/container-linux/kubernetes/cl/controller.yaml.tmpl
* https://github.com/etcd-io/etcd/releases/tag/v3.4.2
=> Update etcd from v3.4.1 to v3.4.2

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* https://docs.projectcalico.org/v3.10/release-notes/
=> Update Calico from v3.10.0 to v3.10.1

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* https://docs.projectcalico.org/v3.10/release-notes/
=> Update Calico from v3.10.1 to v3.10.2

CHANGES.md, README.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/bare-metal.md, docs/index.md
* Update recommended Terraform and provider plugin versions
* Update the rough count of resources created per cluster since its not been refreshed in a while (will vary based on cluster options)
=> Update CHANGES and tutorial notes for release

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* https://docs.projectcalico.org/v3.11/release-notes/
=> Update Calico from v3.10.2 to v3.11.1

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.15.2
=> Update Prometheus from v2.15.1 to v2.15.2

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf
* https://docs.projectcalico.org/v3.11/release-notes/
=> Update Calico from v3.11.1 to v3.11.2

CHANGES.md, README.md, docs/announce.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/bare-metal.md, docs/index.md
* Add an announcement to the website as well
=> Promote Fedora CoreOS from preview to alpha in docs

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.28.0
=> Update nginx-ingress from v0.27.1 to v0.28.0

CHANGES.md, README.md, docs/fedora-coreos/google-cloud.md, docs/index.md, google-cloud/fedora-coreos/kubernetes/LICENSE, google-cloud/fedora-coreos/kubernetes/README.md, google-cloud/fedora-coreos/kubernetes/apiserver.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/controllers.tf, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/ingress.tf, google-cloud/fedora-coreos/kubernetes/network.tf, google-cloud/fedora-coreos/kubernetes/outputs.tf, google-cloud/fedora-coreos/kubernetes/ssh.tf, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/versions.tf, google-cloud/fedora-coreos/kubernetes/workers.tf, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/workers/outputs.tf, google-cloud/fedora-coreos/kubernetes/workers/target_pool.tf, google-cloud/fedora-coreos/kubernetes/workers/variables.tf, google-cloud/fedora-coreos/kubernetes/workers/versions.tf, google-cloud/fedora-coreos/kubernetes/workers/workers.tf, mkdocs.yml
* Add Typhoon Fedora CoreOS on Google Cloud as alpha
* Add docs on uploading the Fedora CoreOS GCP gzipped tarball to Google Cloud storage to create a boot disk image
=> Add module for Fedora CoreOS on Google Cloud

CHANGES.md, README.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/bare-metal.md, docs/index.md
* Remove alpha warnings from docs headers
=> Promote Fedora CoreOS AWS/bare-metal to beta

docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/google-cloud.md
* Sync the documented Terraform versions and provider plugin versions to those that are actively used/tested by the author
=> Update recommended Terraform versions and providers

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.29.0
=> Update nginx-ingress from v0.28.0 to v0.29.0

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.4.4
=> Update etcd from v3.4.3 to v3.4.4

CHANGES.md, README.md, docs/index.md
* Promote Fedora CoreOS AWS to stable
* Promote Fedora CoreOS GCP to beta
=> Promote Fedora CoreOS AWS and Google Cloud

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.4.5
=> Update etcd from v3.4.4 to v3.4.5

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.17.0-rc.3
=> Update Prometheus from v2.16.0 to v2.17.0-rc.3

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.17.0
=> Update Prometheus from v2.17.0-rc.3 to v2.17.0

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/container-linux/kubernetes/cl/controller.yaml, aws/container-linux/kubernetes/workers/cl/worker.yaml, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/container-linux/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/cl/controller.yaml, azure/container-linux/kubernetes/workers/cl/worker.yaml, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/worker.yaml, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/container-linux/kubernetes/cl/worker.yaml, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/workers/cl/worker.yaml, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml
* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/178
=> Update Kubernetes from v1.17.4 to v1.18.0

README.md, aws/container-linux/kubernetes/README.md, aws/container-linux/kubernetes/workers/cl/worker.yaml, aws/fedora-coreos/kubernetes/README.md, azure/container-linux/kubernetes/README.md, bare-metal/container-linux/kubernetes/README.md, bare-metal/fedora-coreos/kubernetes/README.md, digital-ocean/container-linux/kubernetes/README.md, docs/advanced/worker-pools.md, docs/cl/aws.md, docs/cl/azure.md, docs/cl/bare-metal.md, docs/cl/digital-ocean.md, docs/cl/google-cloud.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/google-cloud.md, docs/index.md, docs/topics/maintenance.md, google-cloud/container-linux/kubernetes/README.md, google-cloud/fedora-coreos/kubernetes/README.md
* Update docs which were missed in the new bump process https://github.com/poseidon/typhoon/pull/675
=> Update docs from Kubernetes v1.17.4 to v1.18.0

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v6.7.2
=> Update Grafana from v6.7.1 to v6.7.2

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.4.7
* https://github.com/etcd-io/etcd/releases/tag/v3.4.6
=> Update etcd from v3.4.5 to v3.4.7

CHANGES.md, README.md, docs/index.md
* Change order of OSes in the README
=> Update CHANGES for v1.18.1 release

CHANGES.md, README.md, azure/fedora-coreos/kubernetes/LICENSE, azure/fedora-coreos/kubernetes/README.md, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/controllers.tf, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/lb.tf, azure/fedora-coreos/kubernetes/network.tf, azure/fedora-coreos/kubernetes/outputs.tf, azure/fedora-coreos/kubernetes/security.tf, azure/fedora-coreos/kubernetes/ssh.tf, azure/fedora-coreos/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/versions.tf, azure/fedora-coreos/kubernetes/workers.tf, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/workers/variables.tf, azure/fedora-coreos/kubernetes/workers/versions.tf, azure/fedora-coreos/kubernetes/workers/workers.tf, docs/advanced/worker-pools.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, docs/index.md
* Add `azure/fedora-coreos/kubernetes` module
=> Add support for Fedora CoreOS on Azure

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://docs.projectcalico.org/v3.13/release-notes/
=> Update Calico from v3.13.1 to v3.13.3

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.18.0-rc.1
=> Update Prometheus from v2.17.2 to v2.18.0-rc.1

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.18.1
=> Update Prometheus from v2.18.0 to v2.18.1

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://docs.projectcalico.org/v3.14/release-notes/
=> Update Calico from v3.13.3 to v3.14.0

aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md#v348-2020-05-18
=> Update etcd from v3.4.7 to v3.4.8

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md#v349-2020-05-20
=> Update etcd from v3.4.8 to v3.4.9

CHANGES.md, addons/prometheus/exporters/node-exporter/daemonset.yaml
* https://github.com/prometheus/node_exporter/releases/tag/v1.0.0
=> Update node-exporter from v1.0.0-rc.1 to v1.0.0

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.0.1
=> Update Grafana from v7.0.0 to v7.0.1

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://docs.projectcalico.org/v3.14/release-notes/
=> Update Calico from v3.14.0 to v3.14.1

docs/advanced/customization.md, docs/topics/security.md
* Use security@psdn.io across github.com/poseidon projects
=> Update security disclosure contact email

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-0.33.0
=> Update nginx-ingress from v0.32.0 to v0.33.0

aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.8.0
* Also remove experimental kube-router option
=> Update Cilium from v1.8.0-rc4 to v1.8.0

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.0.4
=> Update Grafana from v7.0.3 to v7.0.4

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://docs.projectcalico.org/v3.15/release-notes/
=> Update Calico from v3.14.1 to v3.15.0

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.19.2
=> Update Prometheus from v2.19.1 to v2.19.2

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.0.5
=> Update Grafana from v7.0.4 to v7.0.5

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.8.1
=> Update Cilium from v1.8.0 to v1.8.1

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.0.6
=> Update Grafana from v7.0.5 to v7.0.6

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* Switch to ingress-nginx controller images from us.grc.io (eu, asia can also be used if desired)
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.34.1
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.34.0
=> Update ingress-nginx from v0.33.0 to v0.34.1

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.1.0
=> Update Grafana from v7.0.6 to v7.1.0

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.4.10
=> Update etcd from v3.4.9 to v3.4.10

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.8.2
=> Update Cilium from v1.8.1 to v1.8.2

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.1.1
=> Update Grafana from v7.1.0 to v7.1.1

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.20.0
=> Update Prometheus from v2.19.2 to v2.20.0

CHANGES.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/google-cloud.md, docs/topics/maintenance.md, requirements.txt
* Sync Terraform provider plugin versions to those used internally
* Update mkdocs-material from v5.5.1 to v5.5.6
* Fix minor details in docs
=> Update recommended Terraform provider versions

CHANGES.md, aws/container-linux/kubernetes/cl/controller.yaml, aws/fedora-coreos/kubernetes/fcc/controller.yaml, azure/container-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/container-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/container-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/container-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml
* https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md
=> Update etcd from v3.4.10 to v3.4.12

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.1.5
=> Update Grafana from v7.1.4 to v7.1.5

CHANGES.md, docs/addons/fleetlock.md, docs/addons/overview.md, docs/architecture/operating-systems.md, mkdocs.yml
* Add links to fleetlock for Fedora CoreOS reboot coordination
* https://github.com/poseidon/fleetlock
=> Add fleetlock addon docs and links

docs/advanced/worker-pools.md, mkdocs.yml
* Show Fedora CoreOS and Flatcar Linux examples in separate tabs, rather than trying to show one
* Add copyright footer for the poseidon org
=> Add code group blocks to improve worker pool docs

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* Repo changed to k8s.gcr.io/ingress-nginx/controller
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.35.0
=> Update nginx-ingress from v0.34.1 to v0.35.0

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.8.3
=> Update Cilium from v1.8.2 to v1.8.3

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.21.0
=> Update Prometheus from v2.20.0 to v2.21.0

addons/grafana/dashboards-k8s-nodes.yaml, addons/grafana/dashboards-k8s-resources-2.yaml, addons/prometheus/rules.yaml
* Fix Kubelet pod and container count metrics dashboard
* https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/499
=> Update Grafana dashboard for Kubelet v1.19

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.2.0
=> Update Grafana from v7.1.5 to v7.2.0

CHANGES.md, aws/container-linux/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/bootstrap.tf, azure/container-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/container-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/container-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/container-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.8.4
=> Update Cilium from v1.8.3 to v1.8.4

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.40.0
=> Update nginx-ingress from v0.35.0 to v0.40.0

docs/architecture/operating-systems.md, mkdocs.yml, requirements.txt
* Update OS kernel, systemd, and docker verisons
=> Update mkdocs-material from v5.5.12 to v6.0.1

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.40.2
=> Update nginx-ingress from v0.40.0 to v0.40.2

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.2.1
=> Update Grafana from v7.2.0 to v7.2.1

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.22.0
=> Update Prometheus from v2.21.0 to v2.22.0

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.2.2
=> Update Grafana from v7.2.1 to v7.2.2

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.3.0
=> Update Grafana from v7.2.2 to v7.3.0

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.8.5
=> Update Cilium from v1.8.4 to v1.8.5

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/poseidon/terraform-render-bootstrap/pull/224
=> Update Cilium from v1.8.5 to v1.9.0-rc3

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.41.0
=> Update nginx-ingress from v0.40.2 to v0.41.0

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/projectcalico/calico/releases/tag/v3.16.5
=> Update Calico from v3.16.4 to v3.16.5

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.9.0
=> Update Cilium from v1.9.0-rc3 to v1.9.0

CHANGES.md, aws/flatcar-linux/kubernetes/cl/controller.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml
* Use docker to run `bootstrap.service` container
* Background https://github.com/poseidon/typhoon/pull/855
=> Change bootstrap.service container from rkt to docker

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.41.2
=> Update nginx-ingress from v0.41.0 to v0.41.2

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.3.3
=> Update Grafana from v7.3.2 to v7.3.3

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.22.2
=> Update Prometheus from v2.22.1 to v2.22.2

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Enable Calico MTU auto-detection
* Remove [workaround](https://github.com/poseidon/typhoon/pull/724) to Calico cni-plugin [issue](https://github.com/projectcalico/cni-plugin/issues/874)
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/230
=> Update Calico from v3.16.5 to v3.17.0

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.3.4
=> Update Grafana from v7.3.3 to v7.3.4

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-alpha.3
=> Update kube-state-metrics from v2.0.0-alpha.2 to v2.0.0-alpha.3

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.23.0
=> Update Prometheus from v2.23.0-rc.0 to v2.23.0

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/flatcar-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.4.14
=> Update etcd from v3.4.12 to v3.4.14

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.9.1
=> Update Cilium from v1.9.0 to v1.9.1

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/versions.tf, aws/fedora-coreos/kubernetes/workers/versions.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/versions.tf, aws/flatcar-linux/kubernetes/workers/versions.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/versions.tf, azure/fedora-coreos/kubernetes/workers/versions.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/versions.tf, azure/flatcar-linux/kubernetes/workers/versions.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/versions.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/versions.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/versions.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/versions.tf, docs/topics/maintenance.md, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/versions.tf, google-cloud/fedora-coreos/kubernetes/workers/versions.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/versions.tf, google-cloud/flatcar-linux/kubernetes/workers/versions.tf
* Support Terraform v0.13.x and v0.14.x
=> Add support for Terraform v0.14.x

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/projectcalico/calico/releases/tag/v3.17.1
=> Update Calico from v3.17.0 to v3.17.1

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.3.5
=> Update Grafana from v7.3.4 to v7.3.5

CHANGES.md, aws/fedora-coreos/kubernetes/versions.tf, aws/fedora-coreos/kubernetes/workers/versions.tf, aws/flatcar-linux/kubernetes/versions.tf, aws/flatcar-linux/kubernetes/workers/versions.tf, azure/fedora-coreos/kubernetes/versions.tf, azure/fedora-coreos/kubernetes/workers/versions.tf, azure/flatcar-linux/kubernetes/versions.tf, azure/flatcar-linux/kubernetes/workers/versions.tf, bare-metal/fedora-coreos/kubernetes/versions.tf, bare-metal/flatcar-linux/kubernetes/versions.tf, digital-ocean/fedora-coreos/kubernetes/versions.tf, digital-ocean/flatcar-linux/kubernetes/versions.tf, docs/topics/maintenance.md, google-cloud/fedora-coreos/kubernetes/versions.tf, google-cloud/fedora-coreos/kubernetes/workers/versions.tf, google-cloud/flatcar-linux/kubernetes/versions.tf, google-cloud/flatcar-linux/kubernetes/workers/versions.tf
* This reverts commit 968febb050a8dc4f504c5e644895dc7fe0280270
* Terraform v0.14 will not make the release cutoff
=> Revert "Add support for Terraform v0.14.x"

CHANGES.md, addons/grafana/dashboards-coredns.yaml, addons/grafana/dashboards-k8s-nodes.yaml, addons/grafana/dashboards-k8s-resources-1.yaml, addons/grafana/dashboards-k8s-resources-2.yaml, addons/grafana/dashboards-k8s.yaml, addons/grafana/dashboards-nginx-ingress.yaml, addons/grafana/dashboards-node-exporter.yaml, addons/grafana/dashboards-prom.yaml, addons/grafana/deployment.yaml, addons/prometheus/rules.yaml
* Update Grafana from v7.3.5 to v7.3.6
=> Update Prometheus rules and Grafana dashboards

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.43.0
* https://github.com/kubernetes/ingress-nginx/issues/6696
=> Update nginx-ingress from v0.41.2 to v0.43.0

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.24.0-rc.0
=> Update Prometheus v2.23.0 to v2.24.0-rc.0

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.24.0
=> Update Prometheus from v2.24.0-rc.0 to v2.24.0

CHANGES.md, aws/fedora-coreos/kubernetes/versions.tf, aws/fedora-coreos/kubernetes/workers/versions.tf, aws/flatcar-linux/kubernetes/versions.tf, aws/flatcar-linux/kubernetes/workers/versions.tf, azure/fedora-coreos/kubernetes/versions.tf, azure/fedora-coreos/kubernetes/workers/versions.tf, azure/flatcar-linux/kubernetes/versions.tf, azure/flatcar-linux/kubernetes/workers/versions.tf, bare-metal/fedora-coreos/kubernetes/versions.tf, bare-metal/flatcar-linux/kubernetes/versions.tf, digital-ocean/fedora-coreos/kubernetes/versions.tf, digital-ocean/flatcar-linux/kubernetes/versions.tf, docs/topics/maintenance.md, google-cloud/fedora-coreos/kubernetes/versions.tf, google-cloud/fedora-coreos/kubernetes/workers/versions.tf, google-cloud/flatcar-linux/kubernetes/versions.tf, google-cloud/flatcar-linux/kubernetes/workers/versions.tf
* Support Terraform v0.13.x and v0.14.4+
=> Add support for Terraform v0.14.4+

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.3.7
=> Update Grafana from v7.3.6 to v7.3.7

README.md, docs/index.md
* Update the Social Contract and Sponsors
=> Link to Github Sponsors in README and docs

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.9.2
=> Update Cilium from v1.9.1 to v1.9.2

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.9.3
=> Update Cilium from v1.9.2 to v1.9.3

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.9.4
=> Update Cilium from v1.9.3 to v1.9.4

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/projectcalico/calico/releases/tag/v3.17.2
=> Update Calico from v3.17.1 to v3.17.2

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.44.0
=> Update nginx-ingress from v0.43.0 to v0.44.0

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.24.1
=> Update Prometheus from v2.24.0 to v2.24.1

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.4.0
=> Update Grafana from v7.3.7 to v7.4.0

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/poseidon/flannel-cni/releases/tag/v0.4.2
=> Update flannel-cni from v0.4.1 to v0.4.2

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/flatcar-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.4.15
=> Update etcd from v3.4.14 to v3.4.15

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.25.1
=> Update Prometheus from v2.25.0 to v2.25.1

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://docs.projectcalico.org/archive/v3.18/release-notes/
=> Update Calico from v3.17.3 to v3.18.1

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.9.5
=> Update Cilium from v1.9.4 to v1.9.5

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.25.2
=> Update Prometheus from v2.25.1 to v2.25.2

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.4.5
=> Update Grafana from v7.4.3 to v7.4.5

.github/dependabot.yaml, requirements.txt
* Watch for PyPi package updates for mkdocs website
* Update requirements.txt packages for mkdocs
=> Add dependabot update watcher for docs pypi packages

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/poseidon/terraform-render-bootstrap/pull/254
=> Update CoreDNS from v1.7.0 to v1.8.0

README.md, docs/index.md
* Include DigitalOcean logo and link on repo and site
=> Add DigitalOcean as a OSS sponsorship partner

CHANGES.md, addons/grafana/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-rc.1
* https://github.com/grafana/grafana/releases/tag/v7.5.1
=> Update kube-state-metrics and Grafana

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.5.2
=> Update Grafana from v7.5.1 to v7.5.2

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/poseidon/terraform-render-bootstrap/pull/257
=> Update static Pod manifests for Kubernetes v1.21.0

.github/FUNDING.yml
* Add sponsorship badge to Github repo sidebar
=> Add sponsorship badge to Github repo

CHANGES.md, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0
=> Update kube-state-metrics from v2.0.0-rc.1 to v2.0.0

CHANGES.md, addons/grafana/deployment.yaml
* https://github.com/grafana/grafana/releases/tag/v7.5.4
=> Update Grafana from v7.5.3 to v7.5.4

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.9.6
=> Update Cilium from v1.9.5 to v1.9.6

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.46.0
=> Update nginx-ingress from v0.45.0 to v0.46.0

CHANGES.md, addons/grafana/deployment.yaml, addons/prometheus/deployment.yaml
* Update Grafana from v7.5.4 to v7.5.6
* https://github.com/prometheus/prometheus/releases/tag/v2.27.0
* https://github.com/grafana/grafana/releases/tag/v7.5.6
=> Update Prometheus from v2.25.2 to v2.27.0

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/flatcar-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml
* https://github.com/etcd-io/etcd/blob/main/CHANGELOG-3.4.md
=> Update etcd from v3.4.15 to v3.4.16

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.47.0
=> Update nginx-ingress from v0.46.0 to v0.47.0

CHANGES.md, addons/grafana/deployment.yaml, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.28.0
* https://github.com/grafana/grafana/releases/tag/v8.0.3
=> Update Prometheus and Grafana addons

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.10.2
=> Update Cilium from v1.10.1 to v1.10.2

CHANGES.md, aws/fedora-coreos/kubernetes/versions.tf, aws/fedora-coreos/kubernetes/workers/versions.tf, aws/flatcar-linux/kubernetes/versions.tf, aws/flatcar-linux/kubernetes/workers/versions.tf, azure/fedora-coreos/kubernetes/versions.tf, azure/fedora-coreos/kubernetes/workers/versions.tf, azure/flatcar-linux/kubernetes/versions.tf, azure/flatcar-linux/kubernetes/workers/versions.tf, bare-metal/fedora-coreos/kubernetes/versions.tf, bare-metal/flatcar-linux/kubernetes/versions.tf, digital-ocean/fedora-coreos/kubernetes/versions.tf, digital-ocean/flatcar-linux/kubernetes/versions.tf, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/bare-metal.md, docs/flatcar-linux/digitalocean.md, docs/flatcar-linux/google-cloud.md, docs/topics/maintenance.md, google-cloud/fedora-coreos/kubernetes/versions.tf, google-cloud/fedora-coreos/kubernetes/workers/versions.tf, google-cloud/flatcar-linux/kubernetes/versions.tf, google-cloud/flatcar-linux/kubernetes/workers/versions.tf
* Continue targeting Ignition v3.2.0 for some time
=> Update poseidon/ct provider from v0.8.0 to v0.9.0

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/fedora-coreos/kubernetes/variables.tf, aws/fedora-coreos/kubernetes/workers/fcc/worker.yaml, aws/fedora-coreos/kubernetes/workers/variables.tf, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/fedora-coreos/kubernetes/variables.tf, azure/fedora-coreos/kubernetes/workers/fcc/worker.yaml, azure/fedora-coreos/kubernetes/workers/variables.tf, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/worker.yaml, bare-metal/fedora-coreos/kubernetes/variables.tf, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/worker.yaml, digital-ocean/fedora-coreos/kubernetes/variables.tf, docs/advanced/customization.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/workers/fcc/worker.yaml, google-cloud/fedora-coreos/kubernetes/workers/variables.tf
* Rename Fedora CoreOS Config (FCC) to Butane Config
* Require any snippets customizations use version v1.4.0
=> Update Butane Config from v1.2.0 to v1.4.0

aws/fedora-coreos/kubernetes/controllers.tf, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/flatcar-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml
* Use multi-arch container image instead of a special "-arm64" suffix on arm64
* https://github.com/etcd-io/etcd/releases/tag/v3.5.0
=> Update etcd from v3.4.16 to v3.5.0

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml, addons/prometheus/exporters/node-exporter/daemonset.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.0.0-beta.1
=> Update nginx-ingress from v0.47.0 to v1.0.0-beta.1

docs/topics/faq.md
=> Remove mention of freenode IRC

CHANGES.md, google-cloud/fedora-coreos/kubernetes/versions.tf, google-cloud/fedora-coreos/kubernetes/workers/versions.tf, google-cloud/flatcar-linux/kubernetes/versions.tf, google-cloud/flatcar-linux/kubernetes/workers/versions.tf
* https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.0.0
=> Allow use of google Terraform provider v4.0+

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://coredns.io/2021/10/07/coredns-1.8.6-release/
=> Update CoreDNS from v1.8.4 to v1.8.6

docs/architecture/operating-systems.md
=> Update operating system notes in architecture docs

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.11.0
=> Update Cilium from v1.10.5 to v1.11.0

CHANGES.md, azure/fedora-coreos/kubernetes/lb.tf, azure/flatcar-linux/kubernetes/lb.tf, bare-metal/fedora-coreos/kubernetes/profiles.tf
* Change to `backend_address_pool_ids` list
=> Fix Azure `backend_address_pool_id` deprecation warning

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/flatcar-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.5.2
=> Update etcd from v3.5.1 to v3.5.2

CHANGES.md, addons/grafana/deployment.yaml, addons/nginx-ingress/aws/class.yaml, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/class.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/class.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/class.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/class.yaml, addons/nginx-ingress/google-cloud/deployment.yaml, addons/prometheus/deployment.yaml
* Align `nginx-ingress` `--controller-class` with `IngressClass` to provide a better example (e.g. if extended to multiple ingress controllers)
=> Update nginx-ingress, Prometheus, and Grafana addons

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.11.2
=> Update Cilium from v1.11.1 to v1.11.2

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/projectcalico/calico/releases/tag/v3.22.1
* Fix https://github.com/projectcalico/calico/issues/5011
=> Update Calico from v3.21.2 to v3.22.1

CHANGES.md, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.1.2
=> Update nginx-ingress from v1.1.1 to v1.1.2

CHANGES.md, addons/grafana/deployment.yaml, addons/prometheus/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
* Update Prometheus, kube-state-metrics, and Grafana
=> Update monitoring addon components

docs/architecture/operating-systems.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/digitalocean.md, docs/flatcar-linux/google-cloud.md
* Update a few OS component details
=> Refresh Terraform providers shown in docs

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.11.3
=> Update Cilium from v1.11.2 to v1.11.3

CHANGES.md, aws/fedora-coreos/kubernetes/fcc/controller.yaml, aws/flatcar-linux/kubernetes/cl/controller.yaml, azure/fedora-coreos/kubernetes/fcc/controller.yaml, azure/flatcar-linux/kubernetes/cl/controller.yaml, bare-metal/fedora-coreos/kubernetes/fcc/controller.yaml, bare-metal/flatcar-linux/kubernetes/cl/controller.yaml, digital-ocean/fedora-coreos/kubernetes/fcc/controller.yaml, digital-ocean/flatcar-linux/kubernetes/cl/controller.yaml, google-cloud/fedora-coreos/kubernetes/fcc/controller.yaml, google-cloud/flatcar-linux/kubernetes/cl/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.5.4
=> Update etcd from v3.5.2 to v3.5.4

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/poseidon/terraform-render-bootstrap/pull/309
=> Update Cilium from v1.11.4 to v1.11.5

CHANGES.md, addons/grafana/deployment.yaml, addons/prometheus/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml
=> Update Prometheus, kube-state-metrics, and Grafana addons

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Update Cilium from v1.11.5 to v1.11.6
* Update Calico from v3.22.2 to v3.23.1
=> Update Cilium and Calico CNI providers

CHANGES.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/digitalocean.md, docs/flatcar-linux/google-cloud.md, requirements.txt
* Sync Terraform provider versions with those used internally
=> Add warning about Terraform AWS provider version

CHANGES.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/google-cloud.md
* Update Terraform provider versions as well
=> Add release note about master to main branch rename

docs/CNAME, mkdocs.yml, theme/main.html
* Add Twitter card customizations that have been kept in an internal fork
* Add CNAME needed for GitHub pages
=> Migrate from internal hosting to GitHub pages

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/projectcalico/calico/releases/tag/v3.23.3
=> Update Calico from v3.23.1 to v3.23.3

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.12.0
=> Update Cilium from v1.11.7 to v1.12.0

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/318
=> Upgrade CoreDNS from v1.8.5 to v1.9.3

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Announce: https://groups.google.com/g/kubernetes-sig-testing/c/U7b_im9vRrM
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/319
=> Switch Kubernetes image registry from k8s.gcr.io to registry.k8s.io

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.12.1
=> Update Cilium from v1.12.0 to v1.12.1

docs/fedora-coreos/aws.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/google-cloud.md
* Although I don't plan to keep these in sync, some users are confused when the docs don't match the actual resource count
=> Update docs showing the terraform plan resources count

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/projectcalico/calico/releases/tag/v3.24.1
=> Update Calico from v3.23.3 to v3.24.1

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.12.2
=> Update Cilium from v1.12.1 to v1.12.2

CHANGES.md, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml
* https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md#v355
=> Update etcd from v3.5.4 to v3.5.5

CHANGES.md, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/worker.yaml
* Kubelet v1.25.1 has the fix https://github.com/kubernetes/kubernetes/pull/112157
=> Remove workaround for preventing search . propagation

CHANGES.md, addons/prometheus/deployment.yaml
* https://github.com/prometheus/prometheus/releases/tag/v2.39.1
=> Update Prometheus from v2.38.0 to v2.39.1

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.12.3
=> Update Cilium from v1.12.2 to v1.12.3

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/projectcalico/calico/releases/tag/v3.24.2
=> Update Calico from v3.24.1 to v3.24.2

CHANGES.md
=> Update CHANGELOG links

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.12.4
=> Update Cilium from v1.12.3 to v1.12.4

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/flannel-io/flannel/releases/tag/v0.20.1
=> Update flannel from v0.15.1 to v0.20.1

aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/poseidon/terraform-render-bootstrap/pull/336
=> Fix flannel container image registry location

CHANGES.md, README.md
=> Add Equinix to the sponsors list

CHANGES.md, addons/grafana/deployment.yaml, addons/nginx-ingress/aws/deployment.yaml, addons/nginx-ingress/azure/deployment.yaml, addons/nginx-ingress/bare-metal/deployment.yaml, addons/nginx-ingress/digital-ocean/daemonset.yaml, addons/nginx-ingress/google-cloud/deployment.yaml, addons/prometheus/deployment.yaml, addons/prometheus/exporters/kube-state-metrics/deployment.yaml, addons/prometheus/exporters/node-exporter/daemonset.yaml
* Update ingress-nginx, Prometheus, node-exporter, and kube-state-metrics
=> Update Nginx Ingress and monitoring addon components

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.12.5
=> Update Cilium from v1.12.4 to v1.12.5

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/poseidon/terraform-render-bootstrap/pull/342
=> Update Calico from v3.24.5 to v3.25.0

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.12.6
=> Update Cilium from v1.12.5 to v1.12.6

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.13.0
=> Update Cilium from v1.12.6 to v1.13.0

CHANGES.md, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.5.8
=> Update etcd from v3.5.7 to v3.5.8

CHANGES.md, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.5.9
=> Update etcd from v3.5.8 to v3.5.9

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Also update flannel v0.21.2 to v0.22.0
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/355
=> Update Cilium from v1.13.2 to v1.13.3

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Add new CRD bgpfilters and new ClusterRoles calico-cni-plugin
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/358
=> Upgrade Calico from v3.25.1 to v3.26.1

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/poseidon/terraform-render-bootstrap/pull/360
* Also update flannel from v0.22.0 to v0.22.1
=> Upgrade Cilium from v1.13.4 to v1.14.0

aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
Rel: https://github.com/poseidon/terraform-render-bootstrap/pull/362
=> Fix Cilium v1.14 support for HostPort pods

aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Details: https://github.com/poseidon/terraform-render-bootstrap/pull/363
=> Emulate Cilium KubeProxyReplacement partial mode

CHANGES.md, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.5.10
=> Update etcd from v3.5.9 to v3.5.10

aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml
* https://github.com/etcd-io/etcd/releases/tag/v3.5.11
* https://github.com/etcd-io/etcd/releases/tag/v3.5.12
=> Update etcd from v3.5.10 to v3.5.12

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.15.1
=> Update Cilium from v1.14.3 to v1.15.1

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/fedora-coreos/kubernetes/butane/controller.yaml, aws/flatcar-linux/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/butane/controller.yaml, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/butane/controller.yaml, azure/flatcar-linux/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/butane/controller.yaml, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/butane/controller.yaml, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/butane/controller.yaml, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/butane/controller.yaml, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/butane/controller.yaml, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/butane/controller.yaml, google-cloud/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/butane/controller.yaml
* Update Cilium from v1.15.2 to v1.15.3
* Update Calico from v3.27.2 to v3.27.3
=> Update etcd from v3.5.12 to v3.5.13 and bump Calico/Cilium

requirements.txt
* There was a bit of discussion upstream about the pinning but that is resolved https://github.com/squidfunk/mkdocs-material/issues/7076
=> Update mkdocs and mkdocs-material together

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Update Cilium from v1.15.3 to v1.25.4
* Update flannel from v0.24.4 to v0.25.1
=> Update Cilium and flannel container images

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* https://github.com/cilium/cilium/releases/tag/v1.15.5
=> Update Cilium from v1.15.4 to v1.15.5

CHANGES.md, google-cloud/fedora-coreos/kubernetes/controllers.tf, google-cloud/fedora-coreos/kubernetes/variables.tf, google-cloud/fedora-coreos/kubernetes/workers.tf, google-cloud/flatcar-linux/kubernetes/controllers.tf, google-cloud/flatcar-linux/kubernetes/variables.tf, google-cloud/flatcar-linux/kubernetes/workers.tf
* Add `controller_disk_size` and `worker_disk_size` variables
* Remove `disk_size` variable
=> google: Configure controller and worker disk sizes

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
=> Fix flannel-cni container image

README.md, docs/fedora-coreos/aws.md, docs/fedora-coreos/azure.md, docs/fedora-coreos/bare-metal.md, docs/fedora-coreos/digitalocean.md, docs/fedora-coreos/google-cloud.md, docs/flatcar-linux/aws.md, docs/flatcar-linux/azure.md, docs/flatcar-linux/bare-metal.md, docs/flatcar-linux/digitalocean.md, docs/flatcar-linux/google-cloud.md, docs/index.md
It's only documentation, but kubeconfig file contains sensitive info so it's better to secure it a little
=> doc: set file_permission 0600 for kubeconfig file

CHANGES.md, aws/fedora-coreos/kubernetes/security.tf, aws/flatcar-linux/kubernetes/security.tf, google-cloud/fedora-coreos/kubernetes/network.tf, google-cloud/flatcar-linux/kubernetes/network.tf
* These rules are no longer needed since Calico is no longer supported
=> Remove Calico BGP and IPIP firewall/security rules

CHANGES.md, aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Also update flannel from v0.26.2 to v0.26.5
=> Update Cilium from v1.17.1 to v1.17.2

aws/fedora-coreos/kubernetes/bootstrap.tf, aws/flatcar-linux/kubernetes/bootstrap.tf, azure/fedora-coreos/kubernetes/bootstrap.tf, azure/flatcar-linux/kubernetes/bootstrap.tf, bare-metal/fedora-coreos/kubernetes/bootstrap.tf, bare-metal/flatcar-linux/kubernetes/bootstrap.tf, digital-ocean/fedora-coreos/kubernetes/bootstrap.tf, digital-ocean/flatcar-linux/kubernetes/bootstrap.tf, google-cloud/fedora-coreos/kubernetes/bootstrap.tf, google-cloud/flatcar-linux/kubernetes/bootstrap.tf
* Cilium v1.17.6 is broken, see https://github.com/cilium/cilium/issues/40571
=> Rollback Cilium from v1.17.6 to v1.17.5
